import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, AppState, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { router, useLocalSearchParams } from 'expo-router';
import { useAppDialog } from '../../src/components/AppDialog';
import { useDatabase } from '../../src/db/DatabaseProvider';
import { useAccessibility } from '../../src/features/accessibility/AccessibilityProvider';
import { createDelayedRecallRounds } from '../../src/features/practice/delayed-recall';
import { getDelayedRecallProgress, recordDelayedRecallAnswer } from '../../src/features/practice/delayed-recall.repository';
import { completePracticeSession, resolveDelayedRecallSeconds } from '../../src/features/practice/session.repository';
import { usePracticeSession } from '../../src/features/practice/usePracticeSession';
import { useHaptics } from '../../src/features/settings/HapticsProvider';
import { useTheme } from '../../src/theme/ThemeProvider';
import { radius, ThemeColors } from '../../src/theme/tokens';

type Phase = 'memorize' | 'question' | 'feedback';
export default function DelayedRecallScreen() {
  const database = useDatabase(); const { colors } = useTheme(); const styles = createStyles(colors); const { announce } = useAccessibility(); const haptics = useHaptics(); const { showDialog } = useAppDialog();
  const { sessionId, mixedSessionId } = useLocalSearchParams<{ sessionId: string; mixedSessionId?: string }>(); const id = Number(sessionId); const { data, loading, error, reload } = usePracticeSession(id);
  const recallSeconds = resolveDelayedRecallSeconds(data?.config); const [answeredIds, setAnsweredIds] = useState<Set<number>>(new Set()); const [appActive, setAppActive] = useState(AppState.currentState === 'active'); const [progressLoading, setProgressLoading] = useState(true); const [phase, setPhase] = useState<Phase>('memorize'); const [seconds, setSeconds] = useState(recallSeconds); const [selected, setSelected] = useState<number>(); const [saving, setSaving] = useState(false); const questionStarted = useRef(Date.now());
  const rounds = useMemo(() => createDelayedRecallRounds(data?.items ?? [], id), [data?.items, id]); const roundIndex = rounds.findIndex((round) => !answeredIds.has(round.target.id)); const round = rounds[roundIndex];
  useEffect(() => { if (!data) return; getDelayedRecallProgress(database, id).then(async (progress) => { setAnsweredIds(progress.answeredIds); if (progress.answeredIds.size >= Math.floor(data.items.length / 3)) { if (!data.session.completedAt) await completePracticeSession(database, data.session.id, data.session.startedAt); router.replace(mixedSessionId ? { pathname: '/practice/mixed', params: { sessionId: mixedSessionId } } : { pathname: '/practice/delayed-recall-result', params: { sessionId } }); } }).catch(console.error).finally(() => setProgressLoading(false)); }, [data, database, id, sessionId]);
  useEffect(() => { setPhase('memorize'); setSeconds(recallSeconds); setSelected(undefined); }, [recallSeconds, roundIndex]);
  useEffect(() => AppState.addEventListener('change', (state) => { const active = state === 'active'; setAppActive(active); if (active) { setPhase('memorize'); setSeconds(recallSeconds); setSelected(undefined); } }).remove, [recallSeconds]);
  useEffect(() => { if (!appActive || phase !== 'memorize' || !round) return; const durationMs = recallSeconds * 1000; const end = Date.now() + durationMs; const tick = setInterval(() => setSeconds(Math.max(0, Math.ceil((end - Date.now()) / 1000))), 200); const timer = setTimeout(() => { clearInterval(tick); setSeconds(0); setPhase('question'); questionStarted.current = Date.now(); announce(`Apa arti ${round.target.sourceText}?`); }, durationMs); return () => { clearInterval(tick); clearTimeout(timer); }; }, [announce, appActive, phase, recallSeconds, round]);
  if (loading || progressLoading) return <View style={styles.center}><ActivityIndicator color={colors.primary} /><Text style={styles.muted}>Menyiapkan ingatan…</Text></View>;
  if (error || !data || !round) return <View style={styles.center}><Text style={styles.error}>{error || 'Materi sesi tidak tersedia.'}</Text>{error ? <Pressable onPress={reload}><Text style={styles.link}>Coba lagi</Text></Pressable> : null}<Pressable onPress={() => router.dismissTo('/practice')}><Text style={styles.link}>Kembali ke latihan</Text></Pressable></View>;
  const sessionData = data; const totalRounds = rounds.length; const completed = answeredIds.size;
  function requestExit() { showDialog({ title: 'Jeda sesi?', message: 'Jawaban yang sudah diberikan tetap tersimpan. Ronde aktif akan dimulai ulang dengan waktu mengingat yang dipilih saat dilanjutkan.', icon: 'pause-circle-outline', actions: [{ label: 'Jeda & keluar', tone: 'primary', onPress: () => router.dismissTo('/practice') }, { label: 'Lanjut mengingat', tone: 'neutral' }] }); }
  async function answer(optionId: number) {
    if (saving || phase !== 'question') return; const correct = optionId === round.target.id; setSelected(optionId); setPhase('feedback'); void haptics.notification(correct ? Haptics.NotificationFeedbackType.Success : Haptics.NotificationFeedbackType.Error); announce(correct ? 'Tepat' : `Belum tepat. Jawabannya ${round.target.translatedText}`);
    try { setSaving(true); await recordDelayedRecallAnswer(database, { sessionId: sessionData.session.id, entryId: round.target.id, deckId: round.target.deckId, selectedEntryId: optionId, isCorrect: correct, responseTimeMs: Date.now() - questionStarted.current });
      const next = new Set(answeredIds).add(round.target.id); await new Promise((resolve) => setTimeout(resolve, 650)); setAnsweredIds(next); if (next.size >= totalRounds) { await completePracticeSession(database, sessionData.session.id, sessionData.session.startedAt); router.replace(mixedSessionId ? { pathname: '/practice/mixed', params: { sessionId: mixedSessionId } } : { pathname: '/practice/delayed-recall-result', params: { sessionId } }); }
    } catch (cause) { console.error(cause); setPhase('question'); showDialog({ title: 'Jawaban belum tersimpan', message: 'Coba pilih jawaban kembali.', icon: 'alert-circle-outline' }); } finally { setSaving(false); }
  }
  return <View style={styles.screen}><View style={styles.top}><Pressable accessibilityLabel="Jeda dan keluar" hitSlop={9} onPress={requestExit}><Ionicons name="close" size={27} color={colors.ink} /></Pressable><View style={styles.heading}><Text style={styles.counter}>Ronde {roundIndex + 1} / {totalRounds}</Text><Text style={styles.deck} numberOfLines={1}>{round.items[0].deckName}</Text></View><Text style={styles.remaining}>{completed}/{totalRounds}</Text></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${completed / totalRounds * 100}%` }]} /></View>
    {phase === 'memorize' ? <View style={styles.stage}><View style={styles.timer}><Text accessibilityLiveRegion="polite" style={styles.timerText}>{seconds}</Text></View><Text style={styles.eyebrow}>INGAT URUTANNYA</Text><Text style={styles.title}>Tiga kata. {recallSeconds} detik.</Text><View style={styles.wordStack}>{round.items.map((item, index) => <View key={item.id} style={styles.wordCard}><Text style={styles.number}>0{index + 1}</Text><Text adjustsFontSizeToFit numberOfLines={2} style={styles.word}>{item.sourceText}</Text></View>)}</View></View> : <View style={styles.stage}><View style={styles.hidden}><Ionicons name="eye-off-outline" size={27} color={colors.primary} /></View><Text style={styles.eyebrow}>{phase === 'feedback' ? 'HASIL' : 'KATA SUDAH DISEMBUNYIKAN'}</Text><Text style={styles.question}>Apa arti dari{`\n`}<Text style={styles.target}>{round.target.sourceText}</Text>?</Text><View style={styles.options}>{round.options.map((option) => { const chosen = selected === option.id; const correct = option.id === round.target.id; return <Pressable accessibilityRole="radio" accessibilityState={{ checked: chosen, disabled: phase !== 'question' }} disabled={phase !== 'question'} key={option.id} onPress={() => void answer(option.id)} style={[styles.option, phase === 'feedback' && correct && styles.correct, phase === 'feedback' && chosen && !correct && styles.wrong]}><Text style={[styles.optionText, phase === 'feedback' && correct && styles.correctText]}>{option.translatedText}</Text>{phase === 'feedback' && (correct || chosen) ? <Ionicons name={correct ? 'checkmark-circle' : 'close-circle'} size={22} color={correct ? colors.primary : colors.danger} /> : null}</Pressable>; })}</View></View>}
  </View>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10, padding: 24, backgroundColor: colors.paper }, muted: { color: colors.inkMuted }, error: { color: colors.danger, fontWeight: '800' }, link: { color: colors.primary, fontWeight: '900' }, screen: { flex: 1, paddingTop: 58, paddingHorizontal: 18, backgroundColor: colors.paper }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, heading: { alignItems: 'center' }, counter: { color: colors.ink, fontWeight: '900' }, deck: { maxWidth: 180, color: colors.inkMuted, fontSize: 10, marginTop: 2 }, remaining: { minWidth: 35, color: colors.primary, fontWeight: '900', textAlign: 'right' }, progress: { height: 5, marginTop: 18, borderRadius: 5, backgroundColor: colors.line }, progressFill: { height: 5, borderRadius: 5, backgroundColor: colors.primary }, stage: { flex: 1, alignItems: 'center', paddingTop: 34 }, timer: { width: 62, height: 62, alignItems: 'center', justifyContent: 'center', borderRadius: 31, borderWidth: 2, borderColor: colors.primary, backgroundColor: colors.primarySoft }, timerText: { color: colors.primary, fontSize: 28, fontWeight: '900' }, hidden: { width: 62, height: 62, alignItems: 'center', justifyContent: 'center', borderRadius: 31, backgroundColor: colors.primarySoft }, eyebrow: { color: colors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 1.3, marginTop: 17 }, title: { color: colors.ink, fontSize: 25, fontWeight: '900', marginTop: 5 }, wordStack: { width: '100%', gap: 10, marginTop: 28 }, wordCard: { minHeight: 92, flexDirection: 'row', alignItems: 'center', gap: 15, padding: 18, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, number: { color: colors.primary, fontSize: 12, fontWeight: '900', letterSpacing: 1 }, word: { flex: 1, color: colors.ink, fontSize: 25, fontWeight: '900' }, question: { color: colors.ink, fontSize: 20, lineHeight: 32, fontWeight: '800', textAlign: 'center', marginTop: 17 }, target: { color: colors.primary, fontSize: 30, fontWeight: '900' }, options: { width: '100%', gap: 10, marginTop: 25 }, option: { minHeight: 65, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, paddingHorizontal: 18, paddingVertical: 12, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, correct: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, wrong: { borderColor: colors.danger, backgroundColor: colors.dangerSoft }, optionText: { flex: 1, color: colors.ink, fontSize: 15, lineHeight: 21, fontWeight: '800' }, correctText: { color: colors.primary }, });
