import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { useAppDialog } from '../../src/components/AppDialog';
import { isDictationCorrect } from '../../src/features/practice/answer';
import { getDictationProgress, recordDictationAnswer } from '../../src/features/practice/dictation.repository';
import { useDatabase } from '../../src/db/DatabaseProvider';
import { completePracticeSession } from '../../src/features/practice/session.repository';
import { usePracticeSession } from '../../src/features/practice/usePracticeSession';
import { radius, ThemeColors } from '../../src/theme/tokens';
import { useSpeech } from '../../src/features/speech/SpeechProvider';
import { useTheme } from '../../src/theme/ThemeProvider';

export default function DictationScreen() {
  const { colors } = useTheme(); const styles = createStyles(colors); const database = useDatabase(); const { showDialog } = useAppDialog(); const { sessionId } = useLocalSearchParams<{ sessionId: string }>(); const id = Number(sessionId);
  const { data, loading, error } = usePracticeSession(id); const { speak, stop, speakingKey } = useSpeech();
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(''); const [autoResult, setAutoResult] = useState<boolean | null>(null); const [finalResult, setFinalResult] = useState<boolean | null>(null); const [progressLoading, setProgressLoading] = useState(true); const [saving, setSaving] = useState(false); const startedAt = useRef(Date.now());
  const item = data?.items[index]; const variant = data?.config?.dictationVariant ?? 'audio_to_source';
  useEffect(() => { if (!data) return; getDictationProgress(database, id).then(async ({ answeredIds }) => { const next = data.items.findIndex((entry) => !answeredIds.has(entry.id)); if (next < 0) { if (!data.session.completedAt) await completePracticeSession(database, data.session.id, data.session.startedAt); router.replace({ pathname: '/practice/dictation-result', params: { sessionId } }); } else setIndex(next); }).catch(console.error).finally(() => setProgressLoading(false)); }, [data, database, id, sessionId]);
  useEffect(() => { startedAt.current = Date.now(); setAnswer(''); setAutoResult(null); setFinalResult(null); if (item && variant === 'audio_to_source' && !progressLoading) void speak(item.sourceText, item.sourceLanguage, 'dictation'); return () => { void stop(); }; }, [item?.id, variant, progressLoading]);
  if (loading || progressLoading) return <View style={styles.center}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>Menyiapkan dikte…</Text></View>;
  if (error || !data || !item) return <View style={styles.center}><Text style={styles.error}>{error || 'Materi sesi tidak tersedia.'}</Text><Pressable onPress={() => router.dismissTo('/practice')}><Text style={styles.back}>Kembali ke latihan</Text></Pressable></View>;
  function check() { const correct = isDictationCorrect(answer, item!.sourceText, item!.sourceLanguage); setAutoResult(correct); setFinalResult(correct); void stop(); void Haptics.notificationAsync(correct ? Haptics.NotificationFeedbackType.Success : Haptics.NotificationFeedbackType.Warning); }
  function requestExit() { showDialog({ title: 'Jeda sesi?', message: 'Jawaban yang sudah disimpan tetap ada. Teks yang belum disimpan akan dibuang.', icon: 'pause-circle-outline', actions: [{ label: 'Jeda & keluar', tone: 'primary', onPress: () => { void stop(); router.dismissTo('/practice'); } }, { label: 'Lanjut latihan', tone: 'neutral' }] }); }
  async function saveAndNext() { if (saving || autoResult === null || finalResult === null || !data || !item) return; try { setSaving(true); await recordDictationAnswer(database, { sessionId: data.session.id, entryId: item.id, deckId: item.deckId, userAnswer: answer, autoIsCorrect: autoResult, isCorrect: finalResult, responseTimeMs: Date.now() - startedAt.current }); if (index < data.items.length - 1) { setIndex(index + 1); setSaving(false); } else { await completePracticeSession(database, data.session.id, data.session.startedAt); router.replace({ pathname: '/practice/dictation-result', params: { sessionId } }); } } catch (cause) { console.error(cause); showDialog({ title: 'Jawaban belum tersimpan', message: 'Coba simpan kembali.', icon: 'alert-circle-outline' }); setSaving(false); } }
  return <KeyboardAvoidingView style={styles.screen} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={12}>
    <View style={styles.top}><Pressable accessibilityLabel="Jeda dan keluar" hitSlop={9} onPress={requestExit}><Ionicons name="close" size={27} color={colors.ink} /></Pressable><View style={styles.counterBlock}><Text style={styles.counter}>Dikte · {index + 1} / {data.items.length}</Text><Text style={styles.deck} numberOfLines={1}>{item.deckName}</Text></View><View style={{ width: 27 }} /></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${(index / data.items.length) * 100}%` }]} /></View>
    <ScrollView contentContainerStyle={styles.main} keyboardShouldPersistTaps="handled">{variant === 'audio_to_source' ? <><Text style={styles.eyebrow}>DENGARKAN, LALU TULIS</Text><Pressable accessibilityLabel={speakingKey === 'dictation' ? 'Hentikan audio' : 'Dengarkan teks'} onPress={() => speakingKey === 'dictation' ? void stop() : void speak(item.sourceText, item.sourceLanguage, 'dictation')} style={({ pressed }) => [styles.listen, speakingKey === 'dictation' && styles.listening, pressed && { transform: [{ scale: 0.97 }] }]}><Ionicons name={speakingKey === 'dictation' ? 'stop' : 'volume-high'} size={40} color={colors.primaryInk} /></Pressable><Text style={styles.replay}>{speakingKey === 'dictation' ? 'Sedang diputar…' : 'Ketuk untuk memutar ulang'}</Text></> : <><Text style={styles.eyebrow}>LIHAT ARTI, LALU TULIS TEKS ASLI</Text><View style={styles.meaning}><Text style={styles.meaningLabel}>ARTI</Text><Text selectable style={styles.meaningText}>{item.translatedText}</Text></View></>}
      <TextInput accessibilityLabel="Jawaban dikte" editable={autoResult === null && !saving} value={answer} onChangeText={setAnswer} multiline autoCorrect={false} autoCapitalize="sentences" placeholder="Tulis jawabanmu…" placeholderTextColor={colors.muted} style={[styles.input, autoResult !== null && styles.inputChecked]} /><Text style={styles.tolerance}>Kapital, spasi berlebih, simbol, dan tanda baca diabaikan. Diakritik tetap bermakna.</Text>
      {autoResult !== null && finalResult !== null ? <View style={[styles.result, !finalResult && styles.resultWrong]}><View style={styles.resultHeading}><Ionicons name={finalResult ? 'checkmark-circle' : 'close-circle'} size={24} color={finalResult ? colors.moss : colors.coral} /><Text style={styles.resultTitle}>{finalResult ? 'Dinilai tepat' : 'Dinilai belum tepat'}</Text>{autoResult !== finalResult ? <Text style={styles.corrected}>DIKOREKSI</Text> : null}</View><View style={styles.comparison}><Text style={styles.comparisonLabel}>JAWABANMU</Text><Text selectable style={styles.comparisonText}>{answer.trim()}</Text><Text style={styles.comparisonLabel}>JAWABAN ACUAN</Text><Text selectable style={styles.expected}>{item.sourceText}</Text></View><Text style={styles.reviewQuestion}>Hasil otomatis keliru?</Text><View style={styles.corrections}><Pressable onPress={() => setFinalResult(true)} style={[styles.correction, finalResult && styles.correctionActive]}><Ionicons name="checkmark" size={17} color={finalResult ? colors.primaryInk : colors.moss} /><Text style={[styles.correctionText, finalResult && styles.correctionTextActive]}>Seharusnya benar</Text></Pressable><Pressable onPress={() => setFinalResult(false)} style={[styles.correction, !finalResult && styles.correctionWrong]}><Ionicons name="close" size={17} color={!finalResult ? colors.white : colors.coral} /><Text style={[styles.correctionText, !finalResult && styles.correctionWrongText]}>Seharusnya salah</Text></Pressable></View></View> : null}
    </ScrollView><Pressable accessibilityRole="button" onPress={autoResult === null ? check : () => void saveAndNext()} disabled={!answer.trim() || saving} style={[styles.button, (!answer.trim() || saving) && styles.disabled]}>{saving ? <ActivityIndicator color={colors.primaryInk} /> : <><Text style={styles.buttonText}>{autoResult === null ? 'Periksa jawaban' : index === data.items.length - 1 ? 'Simpan & lihat hasil' : 'Simpan & lanjut'}</Text><Ionicons name={autoResult === null ? 'search' : 'arrow-forward'} size={20} color={colors.primaryInk} /></>}</Pressable>
  </KeyboardAvoidingView>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  center: { flex: 1, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center', gap: 10, padding: 24 }, loadingText: { color: colors.inkMuted, fontSize: 12 }, error: { color: colors.danger, fontWeight: '800' }, back: { color: colors.primary, fontWeight: '900' }, screen: { flex: 1, backgroundColor: colors.paper, paddingTop: 58, paddingHorizontal: 20, paddingBottom: 20 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, counterBlock: { alignItems: 'center' }, counter: { color: colors.ink, fontWeight: '900' }, deck: { maxWidth: 170, color: colors.inkMuted, fontSize: 10, marginTop: 2 }, progress: { height: 5, backgroundColor: colors.line, borderRadius: 5, marginTop: 20 }, progressFill: { height: 5, backgroundColor: colors.moss, borderRadius: 5 }, main: { flexGrow: 1, alignItems: 'center', paddingTop: 31, paddingBottom: 18 }, eyebrow: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.25 },
  listen: { width: 104, height: 104, borderRadius: 52, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginTop: 23, shadowColor: colors.primary, shadowOpacity: 0.22, shadowRadius: 15, shadowOffset: { width: 0, height: 8 } }, listening: { borderWidth: 5, borderColor: colors.primarySoft }, replay: { color: colors.muted, fontSize: 11, marginTop: 12 }, meaning: { width: '100%', minHeight: 112, alignItems: 'center', justifyContent: 'center', padding: 20, marginTop: 18, borderRadius: radius.lg, backgroundColor: colors.mossSoft }, meaningLabel: { color: colors.moss, fontSize: 10, fontWeight: '900', letterSpacing: 1.2 }, meaningText: { color: colors.ink, fontSize: 23, lineHeight: 31, fontWeight: '900', textAlign: 'center', marginTop: 8 }, input: { width: '100%', minHeight: 105, textAlignVertical: 'top', backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.line, padding: 17, marginTop: 25, color: colors.ink, fontSize: 18, lineHeight: 26, fontWeight: '600' }, inputChecked: { backgroundColor: colors.paperRaised, color: colors.inkMuted }, tolerance: { alignSelf: 'flex-start', color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 8 },
  result: { width: '100%', backgroundColor: colors.mossSoft, borderRadius: radius.lg, padding: 15, marginTop: 15 }, resultWrong: { backgroundColor: colors.dangerSoft }, resultHeading: { flexDirection: 'row', alignItems: 'center', gap: 8 }, resultTitle: { flex: 1, color: colors.ink, fontWeight: '900' }, corrected: { color: colors.ink, fontSize: 9, fontWeight: '900', letterSpacing: 0.8, backgroundColor: colors.highlightSoft, paddingHorizontal: 7, paddingVertical: 4, borderRadius: 8 }, comparison: { marginTop: 13, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.line }, comparisonLabel: { color: colors.inkMuted, fontSize: 9, fontWeight: '900', letterSpacing: 1, marginBottom: 3 }, comparisonText: { color: colors.ink, fontSize: 13, marginBottom: 10 }, expected: { color: colors.ink, fontSize: 16, lineHeight: 22, fontWeight: '900' }, reviewQuestion: { color: colors.inkMuted, fontSize: 10, fontWeight: '800', marginTop: 15, marginBottom: 7 }, corrections: { flexDirection: 'row', gap: 7 }, correction: { flex: 1, minHeight: 39, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, correctionActive: { backgroundColor: colors.primary, borderColor: colors.primary }, correctionWrong: { backgroundColor: colors.coral, borderColor: colors.coral }, correctionText: { color: colors.ink, fontSize: 10, fontWeight: '900' }, correctionTextActive: { color: colors.primaryInk }, correctionWrongText: { color: colors.white },
  button: { minHeight: 55, borderRadius: radius.md, backgroundColor: colors.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 }, disabled: { opacity: 0.42 }, buttonText: { color: colors.primaryInk, fontSize: 15, fontWeight: '900' },
});
