import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { Ionicons } from '@expo/vector-icons';
import { useAppDialog } from '../../src/components/AppDialog';
import { radius, ThemeColors } from '../../src/theme/tokens';
import { useSpeech } from '../../src/features/speech/SpeechProvider';
import { completePracticeSession } from '../../src/features/practice/session.repository';
import { FlashcardRating, getFlashcardProgress, recordFlashcardRating } from '../../src/features/practice/flashcard.repository';
import { useDatabase } from '../../src/db/DatabaseProvider';
import { usePracticeSession } from '../../src/features/practice/usePracticeSession';
import { useTheme } from '../../src/theme/ThemeProvider';

const ratings: { value: FlashcardRating; label: string; icon: keyof typeof Ionicons.glyphMap; tone: 'danger' | 'highlight' | 'primary' | 'strong' }[] = [
  { value: 'again', label: 'Lupa', icon: 'refresh-outline', tone: 'danger' }, { value: 'hard', label: 'Sulit', icon: 'trail-sign-outline', tone: 'highlight' },
  { value: 'good', label: 'Ingat', icon: 'checkmark-outline', tone: 'primary' }, { value: 'easy', label: 'Kuat', icon: 'sparkles-outline', tone: 'strong' },
];

export default function FlashcardScreen() {
  const { colors } = useTheme(); const styles = createStyles(colors); const database = useDatabase(); const { showDialog } = useAppDialog(); const { sessionId } = useLocalSearchParams<{ sessionId: string }>(); const id = Number(sessionId);
  const { data, loading, error } = usePracticeSession(id); const { speak, stop, speakingKey } = useSpeech();
  const [revealed, setRevealed] = useState(false); const [index, setIndex] = useState(0); const [progressLoading, setProgressLoading] = useState(true); const [saving, setSaving] = useState(false); const cardStartedAt = useRef(Date.now());
  useEffect(() => { if (!data) return; getFlashcardProgress(database, id).then(async ({ answeredIds }) => { const next = data.items.findIndex((item) => !answeredIds.has(item.id)); if (next < 0) { if (!data.session.completedAt) await completePracticeSession(database, data.session.id, data.session.startedAt); router.replace({ pathname: '/practice/flashcard-result', params: { sessionId } }); } else setIndex(next); }).catch(console.error).finally(() => setProgressLoading(false)); }, [data, database, id, sessionId]);
  useEffect(() => { cardStartedAt.current = Date.now(); setRevealed(false); }, [index]);
  const toneColors = useMemo(() => ({ danger: colors.danger, highlight: colors.highlight, primary: colors.primary, strong: colors.ink }), [colors]);
  if (loading || progressLoading) return <View style={styles.center}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>Membuka tumpukan kartu…</Text></View>;
  const item = data?.items[index]; if (error || !data || !item) return <View style={styles.center}><Text style={styles.error}>{error || 'Materi sesi tidak tersedia.'}</Text><Pressable onPress={() => router.dismissTo('/practice')}><Text style={styles.back}>Kembali ke latihan</Text></Pressable></View>;
  const direction = data.config?.flashcardDirection === 'mixed' ? (item.position % 2 ? 'target_to_source' : 'source_to_target') : data.config?.flashcardDirection ?? 'source_to_target';
  const prompt = direction === 'target_to_source' ? item.translatedText : item.sourceText; const answer = direction === 'target_to_source' ? item.sourceText : item.translatedText;
  const language = revealed ? (direction === 'target_to_source' ? item.sourceLanguage : item.targetLanguage) : (direction === 'target_to_source' ? item.targetLanguage : item.sourceLanguage);
  function requestExit() { showDialog({ title: 'Jeda sesi?', message: 'Jawaban yang sudah dinilai tetap tersimpan. Kamu dapat melanjutkan sesi ini dari halaman Latihan.', icon: 'pause-circle-outline', actions: [{ label: 'Jeda & keluar', tone: 'primary', onPress: () => { void stop(); router.dismissTo('/practice'); } }, { label: 'Lanjut latihan', tone: 'neutral' }] }); }
  async function rate(rating: FlashcardRating) { if (saving || !data || !item) return; try { setSaving(true); void stop(); await recordFlashcardRating(database, data.session.id, item.id, item.deckId, rating, Date.now() - cardStartedAt.current); void Haptics.impactAsync(rating === 'again' ? Haptics.ImpactFeedbackStyle.Medium : Haptics.ImpactFeedbackStyle.Light); if (index < data.items.length - 1) { setIndex(index + 1); setSaving(false); } else { await completePracticeSession(database, data.session.id, data.session.startedAt); router.replace({ pathname: '/practice/flashcard-result', params: { sessionId } }); } } catch (cause) { console.error(cause); showDialog({ title: 'Rating belum tersimpan', message: 'Coba pilih rating kembali.', icon: 'alert-circle-outline' }); setSaving(false); } }
  return <View style={styles.screen}>
    <View style={styles.top}><Pressable accessibilityLabel="Jeda dan keluar" hitSlop={9} onPress={requestExit}><Ionicons name="close" size={27} color={colors.ink} /></Pressable><View style={styles.counterBlock}><Text style={styles.counter}>{index + 1} / {data.items.length}</Text><Text style={styles.deck} numberOfLines={1}>{item.deckName}</Text></View><Pressable accessibilityLabel="Dengarkan kartu" hitSlop={9} onPress={() => speakingKey === 'flashcard' ? void stop() : void speak(revealed ? answer : prompt, language, 'flashcard')}><Ionicons name={speakingKey === 'flashcard' ? 'stop-circle-outline' : 'volume-medium-outline'} size={26} color={colors.primary} /></Pressable></View>
    <View style={styles.progress}><View style={[styles.progressFill, { width: `${(index / data.items.length) * 100}%` }]} /></View>
    <Text style={styles.hint}>{revealed ? 'NILAI INGATANMU, BUKAN KESULITAN KATANYA' : 'INGAT JAWABANNYA, LALU BALIK KARTU'}</Text>
    <Pressable accessibilityRole="button" accessibilityLabel={revealed ? 'Kartu sudah dibalik' : 'Balik kartu'} onPress={() => { if (!revealed) { setRevealed(true); void Haptics.selectionAsync(); } }} style={({ pressed }) => [styles.card, revealed && styles.cardBack, pressed && !revealed && { transform: [{ scale: 0.99 }] }]}>
      <View style={styles.cardTop}><Text style={styles.lang}>{revealed ? 'JAWABAN' : 'PERTANYAAN'}</Text><Text style={styles.direction}>{direction === 'target_to_source' ? `${item.targetLanguage.slice(0, 2).toUpperCase()} → ${item.sourceLanguage.slice(0, 2).toUpperCase()}` : `${item.sourceLanguage.slice(0, 2).toUpperCase()} → ${item.targetLanguage.slice(0, 2).toUpperCase()}`}</Text></View>
      <View style={styles.cardBody}><Text selectable style={styles.word}>{revealed ? answer : prompt}</Text>{!revealed && item.exampleText && direction === 'source_to_target' ? <Text style={styles.sentence}>{item.exampleText}</Text> : null}{revealed ? <View style={styles.answerRule} /> : null}</View>
      <Pressable accessibilityLabel={speakingKey === 'flashcard' ? 'Hentikan audio' : 'Dengarkan teks'} onPress={(event) => { event.stopPropagation(); speakingKey === 'flashcard' ? void stop() : void speak(revealed ? answer : prompt, language, 'flashcard'); }} style={[styles.speaker, speakingKey === 'flashcard' && styles.speakerActive]}><Ionicons name={speakingKey === 'flashcard' ? 'stop' : 'volume-medium'} size={24} color={speakingKey === 'flashcard' ? colors.primaryInk : colors.moss} /></Pressable>
      {!revealed ? <Text style={styles.flip}>Ketuk untuk melihat jawaban</Text> : null}
    </Pressable>
    {revealed ? <><View style={styles.ratings}>{ratings.map((rating) => <Pressable accessibilityRole="button" disabled={saving} key={rating.value} style={({ pressed }) => [styles.rating, pressed && { opacity: 0.65 }]} onPress={() => void rate(rating.value)}><View style={[styles.ratingBar, { backgroundColor: toneColors[rating.tone] }]} /><Ionicons name={rating.icon} size={18} color={toneColors[rating.tone]} /><Text style={styles.ratingText}>{rating.label}</Text></Pressable>)}</View><Text style={styles.ratingHelp}>Ingat/Kuat = berhasil mengingat · Lupa/Sulit = masih perlu latihan</Text></> : <Text style={styles.foot}>Coba ucapkan jawabannya sebelum membalik kartu.</Text>}
  </View>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  center: { flex: 1, backgroundColor: colors.paper, alignItems: 'center', justifyContent: 'center', gap: 10, padding: 24 }, loadingText: { color: colors.inkMuted, fontSize: 12 }, error: { color: colors.danger, fontWeight: '800' }, back: { color: colors.primary, fontWeight: '900' }, screen: { flex: 1, backgroundColor: colors.paper, paddingTop: 58, paddingHorizontal: 20 }, top: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, counterBlock: { alignItems: 'center' }, counter: { color: colors.ink, fontWeight: '900' }, deck: { maxWidth: 160, color: colors.inkMuted, fontSize: 10, marginTop: 2 }, progress: { height: 5, backgroundColor: colors.line, borderRadius: 5, marginTop: 20 }, progressFill: { height: 5, backgroundColor: colors.moss, borderRadius: 5 }, hint: { textAlign: 'center', color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.05, marginTop: 31, marginBottom: 13 },
  card: { minHeight: 378, backgroundColor: colors.surface, borderRadius: 28, borderWidth: 1, borderColor: colors.line, padding: 25, shadowColor: colors.shadow, shadowOpacity: 0.08, shadowRadius: 18, shadowOffset: { width: 0, height: 9 } }, cardBack: { backgroundColor: colors.mossSoft }, cardTop: { flexDirection: 'row', justifyContent: 'space-between' }, lang: { color: colors.moss, fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, direction: { color: colors.inkMuted, fontSize: 10, fontWeight: '800' }, cardBody: { flex: 1, alignItems: 'center', justifyContent: 'center' }, word: { color: colors.ink, fontSize: 31, lineHeight: 39, fontWeight: '900', textAlign: 'center' }, sentence: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 14, fontStyle: 'italic', textAlign: 'center' }, answerRule: { width: 66, height: 3, borderRadius: 3, backgroundColor: colors.highlight, marginTop: 20, transform: [{ rotate: '-1.5deg' }] }, speaker: { alignSelf: 'center', width: 50, height: 50, borderRadius: 25, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center' }, speakerActive: { backgroundColor: colors.primary }, flip: { color: colors.inkMuted, fontSize: 11, textAlign: 'center', marginTop: 10 }, foot: { textAlign: 'center', color: colors.muted, fontSize: 13, marginTop: 24 },
  ratings: { flexDirection: 'row', gap: 7, marginTop: 18 }, rating: { flex: 1, minHeight: 64, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, overflow: 'hidden', alignItems: 'center', justifyContent: 'center', gap: 3 }, ratingBar: { position: 'absolute', top: 0, left: 0, right: 0, height: 4 }, ratingText: { color: colors.ink, fontSize: 11, fontWeight: '900' }, ratingHelp: { textAlign: 'center', color: colors.inkMuted, fontSize: 10, lineHeight: 15, marginTop: 9 },
});
