import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import DateTimePicker, { DateTimePickerEvent } from '@react-native-community/datetimepicker';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { PaperScreen } from '../../src/components/PaperScreen';
import { IconButton } from '../../src/components/ui';
import { useAppDialog } from '../../src/components/AppDialog';
import { useDatabase } from '../../src/db/DatabaseProvider';
import { getLanguage } from '../../src/features/decks/languages';
import { useDecks } from '../../src/features/decks/useDecks';
import { createMixedPracticeSession, loadMixedSetup, saveMixedSetup } from '../../src/features/practice/mixed.repository';
import { countPracticeCandidates, DelayedRecallDisplay, DictationAnswerMode, DictationCue, FillDifficulty, FlashcardDirection, GameMode, isValidPracticeDate, PracticeConfig } from '../../src/features/practice/session.repository';
import { backOrReplace } from '../../src/navigation/back';
import { useTheme } from '../../src/theme/ThemeProvider';
import { radius, ThemeColors } from '../../src/theme/tokens';

const games: { mode: GameMode; label: string; note: string; icon: keyof typeof Ionicons.glyphMap }[] = [
  { mode: 'flashcard', label: 'Kartu flash', note: 'Nilai ingatan', icon: 'copy-outline' },
  { mode: 'dictation', label: 'Dikte', note: 'Dengar atau lihat arti', icon: 'mic-outline' },
  { mode: 'matchup', label: 'Jodohkan', note: 'Pasangkan kata', icon: 'git-compare-outline' },
  { mode: 'delayed_recall', label: 'Ingat Lagi', note: 'Memori tertunda', icon: 'hourglass-outline' },
];
const gradeOptions = [{ value: 0, label: 'Baru' }, { value: 1, label: 'Dipelajari' }, { value: 2, label: 'Familiar' }, { value: 3, label: 'Dikuasai' }];
const initialConfig: PracticeConfig = { deckIds: [], grades: [0, 1, 2, 3], itemLimit: 10, shuffle: true, flashcardDirection: 'source_to_target', dictationVariant: 'audio_to_source', dictationCue: 'audio', dictationAnswerMode: 'full', fillDifficulty: 'easy', delayedRecallSeconds: 5, delayedRecallDisplay: 'source', mixedModes: ['flashcard', 'dictation', 'matchup', 'delayed_recall'] };

export default function MixedSetup() {
  const database = useDatabase(); const { colors, resolvedTheme } = useTheme(); const styles = createStyles(colors); const { decks, loading } = useDecks(); const { showDialog } = useAppDialog();
  const [step, setStep] = useState<1 | 2>(1); const [config, setConfig] = useState(initialConfig); const [available, setAvailable] = useState(0); const [starting, setStarting] = useState(false); const [datePicker, setDatePicker] = useState<'from' | 'to' | null>(null);
  const modes = config.mixedModes ?? []; const datesValid = (!config.dateFrom || isValidPracticeDate(config.dateFrom)) && (!config.dateTo || isValidPracticeDate(config.dateTo)) && (!config.dateFrom || !config.dateTo || config.dateFrom <= config.dateTo);
  useEffect(() => { loadMixedSetup().then((saved) => { if (!saved) return; showDialog({ title: 'Gunakan setup sebelumnya?', message: `${saved.mixedModes?.length ?? 0} game · ${saved.itemLimit} pergantian · ${saved.deckIds.length} deck`, icon: 'time-outline', actions: [{ label: 'Gunakan setup sebelumnya', tone: 'primary', onPress: () => setConfig(saved) }, { label: 'Buat setup baru', tone: 'neutral' }] }); }); }, [showDialog]);
  useEffect(() => { if (decks.length && !config.deckIds.length) setConfig((current) => ({ ...current, deckIds: decks.map((deck) => deck.id) })); }, [decks, config.deckIds.length]);
  useEffect(() => { if (!datesValid) return setAvailable(0); const timer = setTimeout(() => countPracticeCandidates(database, config).then(setAvailable).catch(() => setAvailable(0)), 160); return () => clearTimeout(timer); }, [database, config, datesValid]);
  function patch(values: Partial<PracticeConfig>) { setConfig((current) => ({ ...current, ...values })); }
  function toggleMode(mode: GameMode) { patch({ mixedModes: modes.includes(mode) ? modes.filter((item) => item !== mode) : [...modes, mode] }); }
  function toggleDeck(id: number) { patch({ deckIds: config.deckIds.includes(id) ? config.deckIds.filter((item) => item !== id) : [...config.deckIds, id] }); }
  function toggleGrade(value: number) { patch({ grades: config.grades.includes(value) ? config.grades.filter((grade) => grade !== value) : [...config.grades, value].sort() }); }
  function chooseDate(event: DateTimePickerEvent, value?: Date) { const kind = datePicker; setDatePicker(null); if (event.type !== 'set' || !value || !kind) return; const formatted = `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; patch(kind === 'from' ? { dateFrom: formatted } : { dateTo: formatted }); }
  const displayDate = (value?: string) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(`${value}T12:00:00`)) : 'Semua tanggal';
  async function start() { if (modes.length < 2 || !available || !datesValid) return; try { setStarting(true); await saveMixedSetup(config); const { session } = await createMixedPracticeSession(database, config); router.replace({ pathname: '/practice/mixed', params: { sessionId: String(session.id) } }); } catch (cause) { console.error(cause); showDialog({ title: 'Sesi belum dibuat', message: 'Pastikan minimal dua game dapat memakai materi yang dipilih.', icon: 'alert-circle-outline' }); setStarting(false); } }
  const canContinue = modes.length >= 2 && config.deckIds.length > 0 && config.grades.length > 0 && available > 0 && datesValid;

  return <PaperScreen keyboardShouldPersistTaps="handled">
    <View style={styles.top}><IconButton name="arrow-back" label="Kembali" onPress={() => step === 2 ? setStep(1) : backOrReplace('/practice')} /><View><Text style={styles.kicker}>Setup {step} dari 2</Text><Text style={styles.title}>Latihan campuran</Text></View></View>
    <View style={styles.steps}><View style={styles.stepActive} /><View style={step === 2 ? styles.stepActive : styles.step} /></View>
    {step === 1 ? <>
      <Text style={styles.heading}>Pilih bahan dan game</Text><Text style={styles.help}>Setelah satu pengerjaan selesai, game berikutnya langsung berganti secara acak.</Text>
      <Section title="Game" aside={`${modes.length} dipilih`} styles={styles}><View style={styles.gameGrid}>{games.map((game) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: modes.includes(game.mode) }} key={game.mode} onPress={() => toggleMode(game.mode)} style={[styles.game, modes.includes(game.mode) && styles.selected]}><Ionicons name={game.icon} size={23} color={modes.includes(game.mode) ? colors.primary : colors.inkMuted} /><Text style={styles.gameTitle}>{game.label}</Text><Text style={styles.note}>{game.note}</Text></Pressable>)}</View></Section>
      <Section title="Deck" aside={`${config.deckIds.length} dipilih`} styles={styles}>{loading ? <ActivityIndicator color={colors.primary} /> : <View style={styles.list}>{decks.map((deck) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: config.deckIds.includes(deck.id) }} key={deck.id} onPress={() => toggleDeck(deck.id)} style={[styles.deck, config.deckIds.includes(deck.id) && styles.selected]}><View style={[styles.dot, { backgroundColor: deck.color ?? colors.primary }]} /><View style={{ flex: 1 }}><Text style={styles.optionTitle}>{deck.name}</Text><Text style={styles.note}>{getLanguage(deck.sourceLanguage).short} → {getLanguage(deck.targetLanguage).short} · {deck.entryCount} entri</Text></View><Ionicons name={config.deckIds.includes(deck.id) ? 'checkbox' : 'square-outline'} size={21} color={colors.primary} /></Pressable>)}</View>}</Section>
      <Section title="Tanggal entri dibuat" aside="Opsional" styles={styles}><View style={styles.dateRow}>{(['from', 'to'] as const).map((kind) => <Pressable key={kind} onPress={() => setDatePicker(kind)} style={styles.date}><Ionicons name="calendar-outline" size={18} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.note}>{kind === 'from' ? 'Dari' : 'Sampai'}</Text><Text style={styles.optionTitle}>{displayDate(kind === 'from' ? config.dateFrom : config.dateTo)}</Text></View>{(kind === 'from' ? config.dateFrom : config.dateTo) ? <Pressable hitSlop={7} onPress={(event) => { event.stopPropagation(); patch(kind === 'from' ? { dateFrom: undefined } : { dateTo: undefined }); }}><Ionicons name="close-circle" size={18} color={colors.inkMuted} /></Pressable> : null}</Pressable>)}</View>{!datesValid ? <Text style={styles.error}>Tanggal awal melewati tanggal akhir.</Text> : null}{datePicker ? <DateTimePicker value={new Date(`${(datePicker === 'from' ? config.dateFrom : config.dateTo) ?? new Date().toISOString().slice(0, 10)}T12:00:00`)} mode="date" display="default" themeVariant={resolvedTheme} onChange={chooseDate} /> : null}</Section>
      <Section title="Tingkat penguasaan" aside={`${config.grades.length} dipilih`} styles={styles}><View style={styles.pills}>{gradeOptions.map((item) => <Pill key={item.value} label={item.label} active={config.grades.includes(item.value)} onPress={() => toggleGrade(item.value)} styles={styles} />)}</View></Section>
      <View style={styles.summary}><Text style={styles.summaryValue}>{available}</Text><Text style={styles.summaryText}>materi cocok · {modes.length} game dipilih</Text></View>
      <Action label="Lanjut ke pengaturan game" disabled={!canContinue} onPress={() => setStep(2)} styles={styles} colors={colors} />
    </> : <>
      <Text style={styles.heading}>Atur setiap game</Text><Text style={styles.help}>Jumlah berarti banyaknya pergantian game dalam sesi, bukan jumlah soal untuk setiap game.</Text>
      <Section title="Jumlah pengerjaan" styles={styles}><View style={styles.pills}>{[5, 10, 20, 50].map((value) => <Pill key={value} label={String(value)} active={config.itemLimit === value} onPress={() => patch({ itemLimit: value })} styles={styles} />)}</View><Pressable accessibilityRole="switch" accessibilityState={{ checked: config.shuffle }} onPress={() => patch({ shuffle: !config.shuffle })} style={styles.switch}><Ionicons name="shuffle" size={20} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.optionTitle}>Acak materi</Text><Text style={styles.note}>{config.shuffle ? 'Materi dipilih acak' : 'Urut dari entri terlama'}</Text></View><Ionicons name={config.shuffle ? 'toggle' : 'toggle-outline'} size={31} color={config.shuffle ? colors.primary : colors.inkMuted} /></Pressable></Section>
      {modes.includes('flashcard') ? <Section title="Kartu flash — arah kartu" styles={styles}><View style={styles.pills}>{([{ value: 'source_to_target', label: 'Teks → arti' }, { value: 'target_to_source', label: 'Arti → teks' }, { value: 'mixed', label: 'Campur' }] as { value: FlashcardDirection; label: string }[]).map((item) => <Pill key={item.value} label={item.label} active={config.flashcardDirection === item.value} onPress={() => patch({ flashcardDirection: item.value })} styles={styles} />)}</View></Section> : null}
      {modes.includes('dictation') ? <Section title="Dikte" styles={styles}><Text style={styles.smallTitle}>Petunjuk soal</Text><View style={styles.pills}>{([{ value: 'audio', label: 'Dengar audio' }, { value: 'meaning', label: 'Lihat arti' }] as { value: DictationCue; label: string }[]).map((item) => <Pill key={item.value} label={item.label} active={config.dictationCue === item.value} onPress={() => patch({ dictationCue: item.value, dictationVariant: item.value === 'meaning' ? 'meaning_to_source' : config.dictationAnswerMode === 'fill' ? 'fill_to_source' : 'audio_to_source' })} styles={styles} />)}</View><Text style={styles.smallTitle}>Cara menjawab</Text><View style={styles.pills}>{([{ value: 'full', label: 'Tulis lengkap' }, { value: 'fill', label: 'Isi bagian kosong' }] as { value: DictationAnswerMode; label: string }[]).map((item) => <Pill key={item.value} label={item.label} active={config.dictationAnswerMode === item.value} onPress={() => patch({ dictationAnswerMode: item.value, dictationVariant: config.dictationCue === 'meaning' ? 'meaning_to_source' : item.value === 'fill' ? 'fill_to_source' : 'audio_to_source' })} styles={styles} />)}</View>{config.dictationAnswerMode === 'fill' ? <><Text style={styles.smallTitle}>Tingkat kekosongan</Text><View style={styles.pills}>{([{ value: 'easy', label: 'Mudah' }, { value: 'medium', label: 'Sedang' }, { value: 'hard', label: 'Sulit' }] as { value: FillDifficulty; label: string }[]).map((item) => <Pill key={item.value} label={item.label} active={config.fillDifficulty === item.value} onPress={() => patch({ fillDifficulty: item.value })} styles={styles} />)}</View></> : null}</Section> : null}
      {modes.includes('matchup') ? <Section title="Jodohkan kata" styles={styles}><Info icon="git-compare-outline" text="Satu pengerjaan menampilkan maksimal lima pasangan, lalu langsung berganti ke game acak berikutnya." styles={styles} colors={colors} /></Section> : null}
      {modes.includes('delayed_recall') ? <Section title="Ingat Lagi" styles={styles}><Text style={styles.smallTitle}>Yang ditampilkan</Text><View style={styles.pills}>{([{ value: 'source', label: 'Kata' }, { value: 'meaning', label: 'Arti' }, { value: 'mixed', label: 'Acak' }] as { value: DelayedRecallDisplay; label: string }[]).map((item) => <Pill key={item.value} label={item.label} active={config.delayedRecallDisplay === item.value} onPress={() => patch({ delayedRecallDisplay: item.value })} styles={styles} />)}</View><Text style={styles.smallTitle}>Waktu mengingat</Text><View style={styles.pills}>{([3, 5, 8, 10] as const).map((value) => <Pill key={value} label={`${value} dtk`} active={config.delayedRecallSeconds === value} onPress={() => patch({ delayedRecallSeconds: value })} styles={styles} />)}</View><Text style={styles.note}>Satu pengerjaan memakai tiga kata sebelum berganti game.</Text></Section> : null}
      <View style={styles.summary}><Text style={styles.summaryValue}>{config.itemLimit}</Text><Text style={styles.summaryText}>pengerjaan · game berganti setelah setiap bagian</Text></View>
      <Action label={starting ? 'Menyiapkan sesi…' : 'Simpan & mulai sesi'} disabled={starting} onPress={() => void start()} styles={styles} colors={colors} icon="shuffle" />
    </>}
  </PaperScreen>;
}
function Section({ title, aside, children, styles }: { title: string; aside?: string; children: React.ReactNode; styles: ReturnType<typeof createStyles> }) { return <View style={styles.section}><View style={styles.sectionHead}><Text style={styles.sectionTitle}>{title}</Text>{aside ? <Text style={styles.aside}>{aside}</Text> : null}</View>{children}</View>; }
function Pill({ label, active, onPress, styles }: { label: string; active: boolean; onPress: () => void; styles: ReturnType<typeof createStyles> }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={onPress} style={[styles.pill, active && styles.pillActive]}><Text style={[styles.pillText, active && styles.pillTextActive]}>{label}</Text></Pressable>; }
function Info({ icon, text, styles, colors }: { icon: keyof typeof Ionicons.glyphMap; text: string; styles: ReturnType<typeof createStyles>; colors: ThemeColors }) { return <View style={styles.info}><Ionicons name={icon} size={23} color={colors.primary} /><Text style={styles.infoText}>{text}</Text></View>; }
function Action({ label, disabled, onPress, styles, colors, icon = 'arrow-forward' }: { label: string; disabled: boolean; onPress: () => void; styles: ReturnType<typeof createStyles>; colors: ThemeColors; icon?: keyof typeof Ionicons.glyphMap }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.action, disabled && styles.disabled]}><Text style={styles.actionText}>{label}</Text><Ionicons name={icon} size={19} color={colors.primaryInk} /></Pressable>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  top: { flexDirection: 'row', alignItems: 'center', gap: 12 }, kicker: { color: colors.primary, fontSize: 11, fontWeight: '900' }, title: { color: colors.ink, fontSize: 25, fontWeight: '900' }, steps: { flexDirection: 'row', gap: 6, marginTop: 17 }, step: { flex: 1, height: 4, borderRadius: 4, backgroundColor: colors.line }, stepActive: { flex: 1, height: 4, borderRadius: 4, backgroundColor: colors.primary }, heading: { color: colors.ink, fontSize: 21, fontWeight: '900', marginTop: 23 }, help: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: 5 },
  section: { paddingVertical: 20, borderBottomWidth: 1, borderBottomColor: colors.rule }, sectionHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 }, sectionTitle: { color: colors.ink, fontSize: 15, fontWeight: '900' }, aside: { color: colors.primary, fontSize: 11, fontWeight: '900' }, gameGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 }, game: { width: '48%', flexGrow: 1, minHeight: 104, padding: 13, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, selected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, gameTitle: { color: colors.ink, fontSize: 13, fontWeight: '900', marginTop: 8 }, note: { color: colors.inkMuted, fontSize: 10, lineHeight: 15, marginTop: 3 }, list: { gap: 7 }, deck: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 11, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, dot: { width: 9, height: 9, borderRadius: 5 }, optionTitle: { color: colors.ink, fontSize: 12, fontWeight: '900' }, dateRow: { gap: 8 }, date: { minHeight: 55, flexDirection: 'row', alignItems: 'center', gap: 9, padding: 11, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, error: { color: colors.danger, fontSize: 11, marginTop: 8 },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, pill: { minWidth: 67, alignItems: 'center', paddingHorizontal: 13, paddingVertical: 10, borderRadius: radius.pill, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, pillActive: { borderColor: colors.primary, backgroundColor: colors.primary }, pillText: { color: colors.inkMuted, fontSize: 11, fontWeight: '900' }, pillTextActive: { color: colors.primaryInk }, smallTitle: { color: colors.inkMuted, fontSize: 11, fontWeight: '900', marginTop: 14, marginBottom: 7 }, switch: { flexDirection: 'row', alignItems: 'center', gap: 10, padding: 13, marginTop: 13, borderRadius: radius.md, backgroundColor: colors.paperRaised }, info: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 13, borderRadius: radius.md, backgroundColor: colors.primarySoft }, infoText: { flex: 1, color: colors.ink, fontSize: 11, lineHeight: 17, fontWeight: '700' }, summary: { flexDirection: 'row', alignItems: 'baseline', gap: 8, padding: 17, marginTop: 20, borderRadius: radius.md, backgroundColor: colors.highlightSoft }, summaryValue: { color: colors.ink, fontSize: 28, fontWeight: '900' }, summaryText: { flex: 1, color: colors.inkMuted, fontSize: 11, fontWeight: '700' }, action: { minHeight: 55, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 16, borderRadius: radius.md, backgroundColor: colors.primary }, actionText: { color: colors.primaryInk, fontSize: 14, fontWeight: '900' }, disabled: { opacity: 0.4 },
});
