import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import DateTimePicker, { DateTimePickerEvent } from '@react-native-community/datetimepicker';
import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { PaperScreen } from '../../src/components/PaperScreen';
import { IconButton } from '../../src/components/ui';
import { useAppDialog } from '../../src/components/AppDialog';
import { useDatabase } from '../../src/db/DatabaseProvider';
import { getLanguage } from '../../src/features/decks/languages';
import { useDecks } from '../../src/features/decks/useDecks';
import { countPracticeCandidates, createPracticeSession, DictationVariant, FlashcardDirection, isValidPracticeDate, PracticeConfig, PracticeMode } from '../../src/features/practice/session.repository';
import { useTheme } from '../../src/theme/ThemeProvider';
import { backOrReplace } from '../../src/navigation/back';
import { radius, ThemeColors } from '../../src/theme/tokens';

const gradeOptions = [{ value: 0, label: 'Baru', note: 'Masih asing' }, { value: 1, label: 'Dipelajari', note: 'Sedang dibangun' }, { value: 2, label: 'Familiar', note: 'Mulai dikenal' }, { value: 3, label: 'Dikuasai', note: 'Sudah kuat' }];
const limits = [5, 10, 20, 50];
export default function PracticeSetupScreen() {
  const { mode: rawMode } = useLocalSearchParams<{ mode?: string }>(); const mode: PracticeMode = rawMode === 'dictation' ? 'dictation' : 'flashcard';
  const database = useDatabase(); const { colors, resolvedTheme } = useTheme(); const styles = createStyles(colors); const { decks, loading, error, reload } = useDecks(); const { showDialog } = useAppDialog();
  const [selectedDecks, setSelectedDecks] = useState<number[]>([]); const [grades, setGrades] = useState([0, 1, 2, 3]);
  const [dateFrom, setDateFrom] = useState(''); const [dateTo, setDateTo] = useState(''); const [datePicker, setDatePicker] = useState<'from' | 'to' | null>(null); const [itemLimit, setItemLimit] = useState(10); const [shuffle, setShuffle] = useState(true);
  const [flashcardDirection, setFlashcardDirection] = useState<FlashcardDirection>('source_to_target'); const [dictationVariant, setDictationVariant] = useState<DictationVariant>('audio_to_source');
  const [available, setAvailable] = useState(0); const [counting, setCounting] = useState(false); const [starting, setStarting] = useState(false);
  useEffect(() => { if (decks.length && !selectedDecks.length) setSelectedDecks(decks.map((deck) => deck.id)); }, [decks, selectedDecks.length]);
  const datesValid = (!dateFrom || isValidPracticeDate(dateFrom)) && (!dateTo || isValidPracticeDate(dateTo)) && (!dateFrom || !dateTo || dateFrom <= dateTo);
  const config = useMemo<PracticeConfig>(() => ({ deckIds: selectedDecks, dateFrom: dateFrom || undefined, dateTo: dateTo || undefined, grades, itemLimit, shuffle, flashcardDirection, dictationVariant }), [selectedDecks, dateFrom, dateTo, grades, itemLimit, shuffle, flashcardDirection, dictationVariant]);
  useEffect(() => { if (!datesValid) return setAvailable(0); const timer = setTimeout(async () => { try { setCounting(true); setAvailable(await countPracticeCandidates(database, config)); } catch (cause) { console.error(cause); setAvailable(0); } finally { setCounting(false); } }, 180); return () => clearTimeout(timer); }, [database, config, datesValid]);
  function toggleDeck(id: number) { setSelectedDecks((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]); }
  function toggleGrade(grade: number) { setGrades((current) => current.includes(grade) ? current.filter((value) => value !== grade) : [...current, grade].sort()); }
  function openDate(kind: 'from' | 'to') { setDatePicker(kind); }
  function chooseDate(event: DateTimePickerEvent, value?: Date) { const kind = datePicker; setDatePicker(null); if (event.type !== 'set' || !value || !kind) return; const formatted = `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; if (kind === 'from') setDateFrom(formatted); else setDateTo(formatted); }
  const displayDate = (value: string) => value ? new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium' }).format(new Date(`${value}T12:00:00`)) : 'Semua tanggal';
  async function start() { if (!selectedDecks.length) return showDialog({ title: 'Pilih deck', message: 'Pilih setidaknya satu deck untuk latihan.', icon: 'albums-outline' }); if (!grades.length) return showDialog({ title: 'Pilih tingkat penguasaan', message: 'Pilih setidaknya satu status mastery.', icon: 'ribbon-outline' }); if (!datesValid) return showDialog({ title: 'Rentang tanggal belum valid', message: 'Pastikan tanggal awal tidak melewati tanggal akhir.', icon: 'calendar-outline' }); if (!available) return showDialog({ title: 'Tidak ada materi', message: 'Ubah deck, tanggal, atau status mastery agar ada materi yang cocok.', icon: 'search-outline' }); try { setStarting(true); const { session } = await createPracticeSession(database, mode, config); router.replace({ pathname: mode === 'dictation' ? '/practice/dictation' : '/practice/flashcard', params: { sessionId: String(session.id) } }); } catch (cause) { console.error(cause); showDialog({ title: 'Sesi belum dapat dimulai', message: 'Coba lagi setelah memeriksa pilihan materi.', icon: 'alert-circle-outline' }); setStarting(false); } }

  return <PaperScreen keyboardShouldPersistTaps="handled">
    <View style={styles.topbar}><IconButton name="arrow-back" label="Kembali" onPress={() => backOrReplace('/practice')} /><View style={styles.heading}><Text style={styles.note}>Siapkan sesi</Text><Text style={styles.title}>{mode === 'dictation' ? 'Dikte' : 'Kartu flash'}</Text></View></View>
    <Text style={styles.intro}>Pilih bahan latihanmu. Semua filter dapat digabungkan.</Text>
    {loading ? <ActivityIndicator color={colors.primary} /> : null}{error ? <Pressable onPress={reload}><Text style={styles.error}>{error} Muat ulang.</Text></Pressable> : null}

    <Section title="Deck" aside={`${selectedDecks.length} dipilih`} styles={styles}><View style={styles.list}>{decks.map((deck) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selectedDecks.includes(deck.id) }} key={deck.id} onPress={() => toggleDeck(deck.id)} style={[styles.deck, selectedDecks.includes(deck.id) && styles.selected]}><View style={[styles.dot, { backgroundColor: deck.color ?? colors.primary }]} /><View style={{ flex: 1 }}><Text style={styles.optionTitle}>{deck.name}</Text><Text style={styles.optionNote}>{getLanguage(deck.sourceLanguage).short} → {getLanguage(deck.targetLanguage).short} · {deck.entryCount} entri</Text></View><Ionicons name={selectedDecks.includes(deck.id) ? 'checkbox' : 'square-outline'} size={22} color={selectedDecks.includes(deck.id) ? colors.primary : colors.inkMuted} /></Pressable>)}</View></Section>
    <Section title="Tanggal entri dibuat" aside="Opsional" styles={styles}><Text style={styles.help}>Pilih awal dan akhir rentang. Biarkan kosong untuk semua tanggal.</Text><View style={styles.dateRow}><DateField label="Dari" value={dateFrom} display={displayDate(dateFrom)} onPress={() => openDate('from')} onClear={() => setDateFrom('')} styles={styles} colors={colors} /><Text style={styles.dateArrow}>→</Text><DateField label="Sampai" value={dateTo} display={displayDate(dateTo)} onPress={() => openDate('to')} onClear={() => setDateTo('')} styles={styles} colors={colors} /></View>{!datesValid ? <Text style={styles.error}>Tanggal awal melewati tanggal akhir.</Text> : null}{datePicker ? <DateTimePicker value={new Date(`${(datePicker === 'from' ? dateFrom : dateTo) || new Date().toISOString().slice(0, 10)}T12:00:00`)} mode="date" display="default" maximumDate={datePicker === 'from' && dateTo ? new Date(`${dateTo}T12:00:00`) : undefined} minimumDate={datePicker === 'to' && dateFrom ? new Date(`${dateFrom}T12:00:00`) : undefined} themeVariant={resolvedTheme} onChange={chooseDate} /> : null}</Section>
    <Section title="Tingkat penguasaan" aside={`${grades.length} dipilih`} styles={styles}><View style={styles.grid}>{gradeOptions.map((grade) => <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: grades.includes(grade.value) }} key={grade.value} onPress={() => toggleGrade(grade.value)} style={[styles.grade, grades.includes(grade.value) && styles.selected]}><Ionicons name={grades.includes(grade.value) ? 'checkmark-circle' : 'ellipse-outline'} size={20} color={grades.includes(grade.value) ? colors.primary : colors.inkMuted} /><View><Text style={styles.optionTitle}>{grade.label}</Text><Text style={styles.optionNote}>{grade.note}</Text></View></Pressable>)}</View></Section>
    {mode === 'dictation' ? <Section title="Cara bermain dikte" styles={styles}><Choice active={dictationVariant === 'audio_to_source'} icon="headset-outline" title="Dengar lalu tulis" note="Dengarkan teks bahasa yang dipelajari, lalu tulis kembali." onPress={() => setDictationVariant('audio_to_source')} styles={styles} colors={colors} /><Choice active={dictationVariant === 'meaning_to_source'} icon="create-outline" title="Lihat arti lalu tulis" note="Lihat terjemahan, lalu tulis teks bahasa yang dipelajari." onPress={() => setDictationVariant('meaning_to_source')} styles={styles} colors={colors} /></Section> : <Section title="Arah kartu" styles={styles}><View style={styles.pills}>{[{ value: 'source_to_target', label: 'Teks → arti' }, { value: 'target_to_source', label: 'Arti → teks' }, { value: 'mixed', label: 'Campur' }].map((item) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: flashcardDirection === item.value }} key={item.value} onPress={() => setFlashcardDirection(item.value as FlashcardDirection)} style={[styles.pillChoice, flashcardDirection === item.value && styles.pillSelected]}><Text style={[styles.pillText, flashcardDirection === item.value && styles.pillTextSelected]}>{item.label}</Text></Pressable>)}</View></Section>}
    <Section title="Jumlah & urutan" styles={styles}><View style={styles.pills}>{limits.map((limit) => <Pressable accessibilityRole="radio" accessibilityLabel={`${limit} materi`} accessibilityState={{ checked: itemLimit === limit }} key={limit} onPress={() => setItemLimit(limit)} style={[styles.limit, itemLimit === limit && styles.pillSelected]}><Text style={[styles.pillText, itemLimit === limit && styles.pillTextSelected]}>{limit}</Text></Pressable>)}</View><Pressable accessibilityRole="switch" accessibilityState={{ checked: shuffle }} onPress={() => setShuffle(!shuffle)} style={styles.shuffle}><Ionicons name={shuffle ? 'shuffle' : 'reorder-three-outline'} size={21} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.optionTitle}>Acak materi</Text><Text style={styles.optionNote}>{shuffle ? 'Urutan berbeda setiap sesi' : 'Urut dari entri terlama'}</Text></View><Ionicons name={shuffle ? 'toggle' : 'toggle-outline'} size={31} color={shuffle ? colors.primary : colors.inkMuted} /></Pressable></Section>
    <View style={styles.result}><View><Text style={styles.resultLabel}>Materi cocok</Text><Text style={styles.resultValue}>{counting ? '…' : available}</Text></View><View style={styles.resultCopy}><Text style={styles.resultText}>{Math.min(available, itemLimit)} akan masuk sesi</Text><Text style={styles.optionNote}>{selectedDecks.length} deck · {grades.length} status</Text></View></View>
    <Pressable accessibilityRole="button" accessibilityState={{ disabled: starting || !available || !datesValid, busy: starting }} disabled={starting || !available || !datesValid} onPress={start} style={[styles.start, (starting || !available || !datesValid) && { opacity: 0.45 }]}><Text style={styles.startText}>{starting ? 'Menyiapkan sesi…' : 'Mulai latihan'}</Text><Ionicons name="arrow-forward" size={20} color={colors.primaryInk} /></Pressable>
  </PaperScreen>;
}
function DateField({ label, value, display, onPress, onClear, styles, colors }: { label: string; value: string; display: string; onPress: () => void; onClear: () => void; styles: ReturnType<typeof createStyles>; colors: ThemeColors }) { return <View style={{ flex: 1 }}><Text style={styles.smallLabel}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={`${label}, ${display}`} accessibilityHint="Membuka pemilih tanggal" onPress={onPress} style={styles.dateInput}><Ionicons name="calendar-outline" size={18} color={colors.primary} /><Text numberOfLines={1} style={[styles.dateText, !value && styles.datePlaceholder]}>{display}</Text>{value ? <Pressable accessibilityLabel={`Hapus tanggal ${label}`} hitSlop={7} onPress={(event) => { event.stopPropagation(); onClear(); }}><Ionicons name="close-circle" size={18} color={colors.inkMuted} /></Pressable> : null}</Pressable></View>; }
function Section({ title, aside, children, styles }: { title: string; aside?: string; children: React.ReactNode; styles: ReturnType<typeof createStyles> }) { return <View style={styles.section}><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{aside ? <Text style={styles.aside}>{aside}</Text> : null}</View>{children}</View>; }
function Choice({ active, icon, title, note, onPress, styles, colors }: { active: boolean; icon: keyof typeof Ionicons.glyphMap; title: string; note: string; onPress: () => void; styles: ReturnType<typeof createStyles>; colors: ThemeColors }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={onPress} style={[styles.choice, active && styles.selected]}><Ionicons name={icon} size={25} color={active ? colors.primary : colors.inkMuted} /><View style={{ flex: 1 }}><Text style={styles.optionTitle}>{title}</Text><Text style={styles.optionNote}>{note}</Text></View><Ionicons name={active ? 'radio-button-on' : 'radio-button-off'} size={21} color={active ? colors.primary : colors.inkMuted} /></Pressable>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  topbar: { flexDirection: 'row', alignItems: 'center', gap: 13 }, heading: { flex: 1 }, note: { color: colors.primary, fontSize: 12, fontWeight: '900' }, title: { color: colors.ink, fontSize: 27, fontWeight: '900' }, intro: { color: colors.inkMuted, fontSize: 13, lineHeight: 20, marginTop: 13, marginBottom: 8 },
  section: { paddingVertical: 21, borderBottomWidth: 1, borderBottomColor: colors.rule }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 11 }, sectionTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, aside: { color: colors.primary, fontSize: 12, fontWeight: '800' }, help: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, marginBottom: 10 }, list: { gap: 8 }, deck: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 11, padding: 12, borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, selected: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, dot: { width: 10, height: 10, borderRadius: 5 }, optionTitle: { color: colors.ink, fontSize: 13, fontWeight: '900' }, optionNote: { color: colors.inkMuted, fontSize: 11, lineHeight: 16, marginTop: 2 },
  dateRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 }, smallLabel: { color: colors.inkMuted, fontSize: 11, fontWeight: '800', marginBottom: 6 }, dateInput: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule, borderRadius: radius.md, paddingHorizontal: 10 }, dateText: { flex: 1, color: colors.ink, fontSize: 11, fontWeight: '800' }, datePlaceholder: { color: colors.inkMuted, fontWeight: '600' }, dateArrow: { color: colors.inkMuted, paddingBottom: 14 }, invalid: { borderColor: colors.danger }, error: { color: colors.danger, fontSize: 12, lineHeight: 18, marginTop: 8 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, grade: { width: '48%', flexGrow: 1, minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: 9, padding: 11, borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, choice: { flexDirection: 'row', alignItems: 'center', gap: 11, padding: 14, marginBottom: 8, borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, pills: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, pillChoice: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 12, paddingVertical: 11, borderRadius: radius.pill, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, limit: { minWidth: 52, alignItems: 'center', paddingVertical: 11, borderRadius: radius.pill, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, pillSelected: { backgroundColor: colors.primary, borderColor: colors.primary }, pillText: { color: colors.inkMuted, fontSize: 12, fontWeight: '900' }, pillTextSelected: { color: colors.primaryInk }, shuffle: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 14, padding: 13, borderRadius: radius.md, backgroundColor: colors.paperRaised },
  result: { flexDirection: 'row', alignItems: 'center', marginTop: 23, padding: 18, borderRadius: radius.lg, backgroundColor: colors.highlightSoft }, resultLabel: { color: colors.inkMuted, fontSize: 11, fontWeight: '800' }, resultValue: { color: colors.ink, fontSize: 28, fontWeight: '900' }, resultCopy: { marginLeft: 'auto', alignItems: 'flex-end' }, resultText: { color: colors.ink, fontSize: 13, fontWeight: '900' }, start: { minHeight: 56, marginTop: 13, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, borderRadius: radius.md, backgroundColor: colors.primary }, startText: { color: colors.primaryInk, fontSize: 15, fontWeight: '900' },
});
