import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../theme/ThemeProvider';
import { radius, ThemeColors } from '../../theme/tokens';
import type { EntryFilters, EntrySort, EntryType } from './entry.repository';
import { useAccessibility } from '../accessibility/AccessibilityProvider';

export type LibraryFilterState = Pick<EntryFilters, 'type' | 'favoritesOnly' | 'grade' | 'tag' | 'sort'>;
type Props = { search: string; onSearchChange: (value: string) => void; filters: LibraryFilterState; onFiltersChange: (value: LibraryFilterState) => void; tags: { name: string; count: number }[]; open: boolean; onOpen: () => void; onClose: () => void };
const sorts: { value: EntrySort; label: string }[] = [{ value: 'alphabetical', label: 'A–Z' }, { value: 'newest', label: 'Terbaru' }, { value: 'oldest', label: 'Terlama' }, { value: 'updated', label: 'Baru diubah' }];
const types: { value: EntryType | undefined; label: string }[] = [{ value: undefined, label: 'Semua' }, { value: 'word', label: 'Kata' }, { value: 'phrase', label: 'Frasa' }, { value: 'sentence', label: 'Kalimat' }];
const grades = [{ value: undefined, label: 'Semua' }, { value: 0, label: 'Baru' }, { value: 1, label: 'Dipelajari' }, { value: 2, label: 'Familiar' }, { value: 3, label: 'Dikuasai' }];

export function activeFilterCount(filters: LibraryFilterState) { return Number(Boolean(filters.type)) + Number(Boolean(filters.favoritesOnly)) + Number(filters.grade !== undefined) + Number(Boolean(filters.tag)); }

export function LibraryControls({ search, onSearchChange, filters, onFiltersChange, tags, open, onOpen, onClose }: Props) {
  const { colors } = useTheme(); const { reduceMotion } = useAccessibility(); const styles = createStyles(colors); const count = activeFilterCount(filters);
  return <>
    <View style={styles.row}><View style={styles.search}><Ionicons name="search-outline" size={20} color={colors.inkMuted} /><TextInput accessibilityLabel="Cari entri" value={search} onChangeText={onSearchChange} autoCorrect={false} returnKeyType="search" placeholder="Cari kata, arti, catatan, atau tag" placeholderTextColor={colors.inkFaint} style={styles.input} />{search ? <Pressable accessibilityLabel="Hapus pencarian" onPress={() => onSearchChange('')} hitSlop={7}><Ionicons name="close-circle" size={19} color={colors.inkMuted} /></Pressable> : null}</View><Pressable accessibilityRole="button" accessibilityLabel={`Filter pustaka${count ? `, ${count} aktif` : ''}`} onPress={onOpen} style={[styles.filterButton, count > 0 && styles.filterActive]}><Ionicons name="options-outline" size={21} color={count ? colors.primaryInk : colors.ink} />{count ? <Text style={styles.badge}>{count}</Text> : null}</Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.quickRow}><Quick label="Favorit" active={Boolean(filters.favoritesOnly)} icon="star-outline" onPress={() => onFiltersChange({ ...filters, favoritesOnly: !filters.favoritesOnly })} styles={styles} colors={colors} />{filters.type ? <Quick label={types.find((item) => item.value === filters.type)?.label ?? ''} active onPress={() => onFiltersChange({ ...filters, type: undefined })} styles={styles} colors={colors} /> : null}{filters.tag ? <Quick label={`#${filters.tag}`} active onPress={() => onFiltersChange({ ...filters, tag: undefined })} styles={styles} colors={colors} /> : null}</ScrollView>
    <Modal visible={open} transparent animationType={reduceMotion ? "none" : "slide"} accessibilityViewIsModal onRequestClose={onClose}><Pressable style={styles.scrim} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.sheetHeader}><View><Text style={styles.sheetTitle}>Filter & urutkan</Text><Text style={styles.sheetNote}>Temukan halaman yang kamu cari.</Text></View><Pressable accessibilityLabel="Tutup filter" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.ink} /></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.sheetContent}>
      <ChoiceSection title="Urutkan" values={sorts} selected={filters.sort ?? 'alphabetical'} onSelect={(sort) => onFiltersChange({ ...filters, sort: sort as EntrySort })} styles={styles} />
      <ChoiceSection title="Jenis entri" values={types} selected={filters.type} onSelect={(type) => onFiltersChange({ ...filters, type: type as EntryType | undefined })} styles={styles} />
      <ChoiceSection title="Status mastery" values={grades} selected={filters.grade} onSelect={(grade) => onFiltersChange({ ...filters, grade: grade as number | undefined })} styles={styles} />
      <Text style={styles.sectionTitle}>Tag</Text>{tags.length ? <View style={styles.choices}><Choice label="Semua" active={!filters.tag} onPress={() => onFiltersChange({ ...filters, tag: undefined })} styles={styles} />{tags.map((tag) => <Choice key={tag.name} label={`${tag.name} · ${tag.count}`} active={filters.tag === tag.name} onPress={() => onFiltersChange({ ...filters, tag: tag.name })} styles={styles} />)}</View> : <Text style={styles.noTags}>Belum ada tag di deck ini.</Text>}
      <View style={styles.sheetActions}><Pressable onPress={() => onFiltersChange({ sort: 'alphabetical' })} style={styles.reset}><Text style={styles.resetText}>Reset semua</Text></Pressable><Pressable onPress={onClose} style={styles.apply}><Text style={styles.applyText}>Lihat hasil</Text></Pressable></View>
    </ScrollView></View></Modal>
  </>;
}
function Quick({ label, active, icon, onPress, styles, colors }: { label: string; active: boolean; icon?: keyof typeof Ionicons.glyphMap; onPress: () => void; styles: ReturnType<typeof createStyles>; colors: ThemeColors }) { return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: active }} onPress={onPress} style={[styles.quick, active && styles.quickActive]}>{icon ? <Ionicons name={icon} size={15} color={active ? colors.primary : colors.inkMuted} /> : null}<Text style={[styles.quickText, active && styles.quickTextActive]}>{label}</Text>{active && !icon ? <Ionicons name="close" size={14} color={colors.primary} /> : null}</Pressable>; }
function ChoiceSection({ title, values, selected, onSelect, styles }: { title: string; values: { value: unknown; label: string }[]; selected: unknown; onSelect: (value: unknown) => void; styles: ReturnType<typeof createStyles> }) { return <><Text style={styles.sectionTitle}>{title}</Text><View style={styles.choices}>{values.map((item) => <Choice key={String(item.value)} label={item.label} active={item.value === selected} onPress={() => onSelect(item.value)} styles={styles} />)}</View></>; }
function Choice({ label, active, onPress, styles }: { label: string; active: boolean; onPress: () => void; styles: ReturnType<typeof createStyles> }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  row: { flexDirection: 'row', gap: 9 }, search: { flex: 1, height: 48, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule, borderRadius: radius.md }, input: { flex: 1, color: colors.ink, fontSize: 14, paddingVertical: 0 }, filterButton: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, filterActive: { backgroundColor: colors.primary, borderColor: colors.primary }, badge: { position: 'absolute', top: -5, right: -4, minWidth: 19, height: 19, borderRadius: 10, backgroundColor: colors.highlight, color: colors.primaryInk, textAlign: 'center', lineHeight: 19, fontSize: 10, fontWeight: '900' },
  quickRow: { gap: 7, paddingVertical: 11 }, quick: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 11, borderRadius: radius.pill, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, quickActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, quickText: { color: colors.inkMuted, fontSize: 12, fontWeight: '800' }, quickTextActive: { color: colors.primary },
  scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.45)' }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, maxHeight: '84%', backgroundColor: colors.paper, borderTopLeftRadius: 25, borderTopRightRadius: 25, paddingTop: 9 }, handle: { alignSelf: 'center', width: 41, height: 4, borderRadius: 3, backgroundColor: colors.rule }, sheetHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 15, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.rule }, sheetTitle: { color: colors.ink, fontSize: 21, fontWeight: '900' }, sheetNote: { color: colors.inkMuted, fontSize: 12, marginTop: 2 }, close: { marginLeft: 'auto', width: 42, height: 42, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperRaised }, sheetContent: { paddingHorizontal: 20, paddingBottom: 34 }, sectionTitle: { color: colors.ink, fontSize: 13, fontWeight: '900', marginTop: 19, marginBottom: 9 }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, choice: { minHeight: 39, justifyContent: 'center', paddingHorizontal: 13, borderRadius: radius.pill, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, choiceActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, choiceText: { color: colors.inkMuted, fontSize: 12, fontWeight: '800' }, choiceTextActive: { color: colors.primary }, noTags: { color: colors.inkMuted, fontSize: 13 }, sheetActions: { flexDirection: 'row', gap: 10, marginTop: 27 }, reset: { flex: 1, minHeight: 49, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule }, resetText: { color: colors.ink, fontWeight: '900' }, apply: { flex: 1, minHeight: 49, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primary }, applyText: { color: colors.primaryInk, fontWeight: '900' },
});
