import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { IconButton, SectionTitle } from '../../src/components/ui';
import { useDatabase } from '../../src/db/DatabaseProvider';
import { getGlobalStatistics, GlobalStatistics } from '../../src/features/statistics/statistics.repository';
import { ActivityBars, EmptyStatistics, formatDuration, MasteryBars, Metric, ModeBreakdown } from '../../src/features/statistics/StatisticsViews';
import { useTheme } from '../../src/theme/ThemeProvider';
import { radius, ThemeColors } from '../../src/theme/tokens';
export default function StatisticsScreen() { const database = useDatabase(); const { colors } = useTheme(); const styles = createStyles(colors); const [data, setData] = useState<GlobalStatistics>(); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); setData(await getGlobalStatistics(database)); } catch (cause) { console.error(cause); setError('Statistik belum dapat dihitung.'); } }, [database]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.top}><IconButton name="arrow-back" label="Kembali" onPress={() => router.back()} /><View style={styles.heading}><Text style={styles.note}>Bukti belajarmu</Text><Text style={styles.title}>Statistik</Text></View></View>{!data && !error ? <View style={styles.state}><ActivityIndicator color={colors.primary} /></View> : error ? <View style={styles.state}><Ionicons name="alert-circle-outline" size={29} color={colors.danger} /><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Coba lagi</Text></Pressable></View> : data ? <>
    <View style={styles.hero}><View><Text style={styles.heroValue}>{data.accuracy == null ? '—' : `${data.accuracy}%`}</Text><Text style={styles.heroLabel}>akurasi seluruh latihan</Text></View><View style={styles.heroRule} /><View><Text style={styles.heroSmall}>{data.currentStreak}</Text><Text style={styles.heroLabel}>hari streak saat ini</Text></View></View>
    <View style={styles.metrics}><Metric value={data.answers} label="Jawaban" detail={`${data.sessions} sesi selesai`} /><Metric value={formatDuration(data.durationMs)} label="Waktu sesi" /><Metric value={data.entries} label="Entri" detail={`${data.decks} deck aktif · ${data.archivedDecks} arsip`} /><Metric value={data.mastered} label="Dikuasai" detail={`${data.favorites} favorit`} /></View>
    {data.answers ? <><SectionTitle>14 hari terakhir</SectionTitle><ActivityBars data={data.daily} /><SectionTitle>Menurut permainan</SectionTitle><ModeBreakdown data={data.modes} /></> : <EmptyStatistics onPractice={() => router.push(data.entries ? '/practice/setup' : '/starter-decks')} actionLabel={data.entries ? 'Mulai latihan' : 'Pilih deck siap pakai'} />}
    <SectionTitle>Distribusi mastery</SectionTitle><MasteryBars data={data.mastery} />
    {data.topDecks.length ? <><SectionTitle>Deck paling sering dilatih</SectionTitle>{data.topDecks.map((deck) => <Pressable key={deck.id} onPress={() => router.push(`/statistics/deck/${deck.id}`)} style={styles.deck}><View style={[styles.dot, { backgroundColor: deck.color ?? colors.primary }]} /><View style={styles.grow}><Text style={styles.deckName}>{deck.name}</Text><Text style={styles.deckMeta}>{deck.answers} jawaban · {deck.answers ? Math.round(deck.correct / deck.answers * 100) : 0}% berhasil</Text></View><Ionicons name="chevron-forward" size={18} color={colors.inkMuted} /></Pressable>)}</> : null}
    <View style={styles.noteBox}><Ionicons name="information-circle-outline" size={20} color={colors.primary} /><Text style={styles.noteText}>Statistik memakai hasil final yang tersimpan. Koreksi manual Dikte ikut dihitung; mastery manual tidak mengubah akurasi.</Text></View>
  </> : null}</ScrollView>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 38 }, top: { flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 25 }, heading: { flex: 1 }, note: { color: colors.highlight, fontSize: 13, fontWeight: '900' }, title: { color: colors.ink, fontSize: 27, fontWeight: '900' }, state: { minHeight: 300, alignItems: 'center', justifyContent: 'center', gap: 9 }, error: { color: colors.danger, fontWeight: '800' }, retry: { color: colors.primary, fontWeight: '900' }, hero: { flexDirection: 'row', alignItems: 'center', padding: 19, borderRadius: radius.lg, backgroundColor: colors.primary, marginBottom: 11 }, heroValue: { color: colors.primaryInk, fontSize: 30, fontWeight: '900' }, heroSmall: { color: colors.primaryInk, fontSize: 24, fontWeight: '900' }, heroLabel: { color: colors.primaryInk, opacity: 0.8, fontSize: 10, marginTop: 2 }, heroRule: { width: 1, height: 46, backgroundColor: colors.primaryInk, opacity: 0.25, marginHorizontal: 23 }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 25 }, deck: { flexDirection: 'row', alignItems: 'center', gap: 11, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.rule }, dot: { width: 10, height: 10, borderRadius: 5 }, grow: { flex: 1 }, deckName: { color: colors.ink, fontSize: 14, fontWeight: '900' }, deckMeta: { color: colors.inkMuted, fontSize: 10, marginTop: 3 }, noteBox: { flexDirection: 'row', gap: 10, padding: 14, borderRadius: radius.md, marginTop: 27, backgroundColor: colors.primarySoft }, noteText: { flex: 1, color: colors.inkMuted, fontSize: 10, lineHeight: 16 } });
