import { GestureResponderEvent, Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../theme/ThemeProvider';
import { radius, ThemeColors } from '../../theme/tokens';
import { speechRates, useSpeech } from './SpeechProvider';

export function SpeakButton({ text, language, speechKey, label, compact = false }: { text: string; language: string; speechKey: string; label: string; compact?: boolean }) {
  const { colors } = useTheme(); const styles = createStyles(colors); const { speakingKey, speak, stop } = useSpeech(); const active = speakingKey === speechKey;
  return <Pressable accessibilityRole="button" accessibilityLabel={active ? `Hentikan ${label}` : `Dengarkan ${label}`} accessibilityState={{ busy: active }} hitSlop={6} onPress={(event: GestureResponderEvent) => { event.stopPropagation(); active ? void stop() : void speak(text, language, speechKey); }} style={({ pressed }) => [compact ? styles.compact : styles.button, active && styles.active, pressed && { opacity: 0.7 }]}><Ionicons name={active ? 'stop' : 'volume-medium-outline'} size={compact ? 19 : 21} color={active ? colors.primaryInk : colors.primary} />{compact ? null : <Text style={[styles.buttonText, active && styles.activeText]}>{active ? 'Stop' : 'Dengarkan'}</Text>}</Pressable>;
}

export function SpeechNotice() {
  const { colors } = useTheme(); const styles = createStyles(colors); const { error, clearError } = useSpeech();
  if (!error) return null;
  return <View accessibilityRole="alert" style={styles.notice}><Ionicons name="volume-mute-outline" size={20} color={colors.danger} /><Text style={styles.noticeText}>{error}</Text><Pressable accessibilityLabel="Tutup pesan audio" hitSlop={8} onPress={clearError}><Ionicons name="close" size={18} color={colors.danger} /></Pressable></View>;
}

export function SpeechSettings({ visible, languages, onClose }: { visible: boolean; languages: { code: string; name: string }[]; onClose: () => void }) {
  const { colors } = useTheme(); const styles = createStyles(colors); const { loadingVoices, rate, setRate, configuredVoice, selectedVoice, setVoice, compatibleVoices, refreshVoices, stop } = useSpeech();
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.scrim} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><View><Text style={styles.title}>Suara & kecepatan</Text><Text style={styles.subtitle}>Menggunakan suara yang terpasang di perangkat.</Text></View><Pressable accessibilityLabel="Tutup pengaturan suara" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.ink} /></Pressable></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <Text style={styles.section}>Kecepatan bicara</Text><View style={styles.choices}>{speechRates.map((item) => <Choice key={item.value} label={item.label} detail={`${item.value}×`} active={rate === item.value} onPress={() => { void stop(); setRate(item.value); }} styles={styles} />)}</View>
    {languages.map((language) => { const compatible = compatibleVoices(language.code); const selected = selectedVoice(language.code); return <View key={language.code} style={styles.languageBlock}><Text style={styles.section}>{language.name}</Text>{loadingVoices ? <Text style={styles.help}>Memeriksa suara lokal…</Text> : compatible.length === 0 ? <View style={styles.missing}><Ionicons name="cloud-download-outline" size={20} color={colors.highlight} /><Text style={styles.missingText}>Belum ada voice {language.code}. Pasang paket bahasa melalui pengaturan text-to-speech perangkat.</Text></View> : <View style={styles.voiceList}><Choice label="Otomatis" detail={selected ? `Memakai ${selected.name}` : 'Rekomendasi perangkat'} active={!configuredVoice(language.code)} onPress={() => { void stop(); setVoice(language.code); }} styles={styles} />{compatible.map((voice) => <Choice key={voice.identifier} label={voice.name} detail={`${voice.language}${voice.quality === 'Enhanced' ? ' · Enhanced' : ''}`} active={configuredVoice(language.code) === voice.identifier} onPress={() => { void stop(); setVoice(language.code, voice.identifier); }} styles={styles} />)}</View>}</View>; })}
    <Pressable onPress={() => void refreshVoices()} style={styles.refresh}><Ionicons name="refresh" size={18} color={colors.primary} /><Text style={styles.refreshText}>Periksa ulang voice perangkat</Text></Pressable><Text style={styles.footnote}>Untuk penggunaan sepenuhnya offline, unduh voice bahasa dari pengaturan text-to-speech Android atau Spoken Content iOS. Pada iPhone fisik, silent mode dapat membuat speech tidak terdengar.</Text>
  </ScrollView></View></Modal>;
}
function Choice({ label, detail, active, onPress, styles }: { label: string; detail?: string; active: boolean; onPress: () => void; styles: ReturnType<typeof createStyles> }) { return <Pressable accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><View style={{ flex: 1 }}><Text style={[styles.choiceLabel, active && styles.choiceLabelActive]}>{label}</Text>{detail ? <Text style={styles.choiceDetail}>{detail}</Text> : null}</View>{active ? <Ionicons name="checkmark-circle" size={20} color={styles.choiceLabelActive.color} /> : null}</Pressable>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  button: { alignSelf: 'flex-start', minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 12, borderRadius: radius.md, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primary }, buttonText: { color: colors.primary, fontSize: 12, fontWeight: '900' }, compact: { width: 38, height: 38, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, backgroundColor: colors.primarySoft }, active: { backgroundColor: colors.primary }, activeText: { color: colors.primaryInk },
  notice: { flexDirection: 'row', alignItems: 'flex-start', gap: 9, padding: 13, marginBottom: 14, borderRadius: radius.md, backgroundColor: colors.dangerSoft }, noticeText: { flex: 1, color: colors.danger, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.45)' }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, maxHeight: '86%', backgroundColor: colors.paper, borderTopLeftRadius: 25, borderTopRightRadius: 25, paddingTop: 9 }, handle: { alignSelf: 'center', width: 41, height: 4, borderRadius: 3, backgroundColor: colors.rule }, header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 15, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: colors.rule }, title: { color: colors.ink, fontSize: 21, fontWeight: '900' }, subtitle: { color: colors.inkMuted, fontSize: 12, marginTop: 2 }, close: { marginLeft: 'auto', width: 42, height: 42, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperRaised }, content: { paddingHorizontal: 20, paddingBottom: 34 }, section: { color: colors.ink, fontSize: 14, fontWeight: '900', marginTop: 20, marginBottom: 9 }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, choice: { minWidth: '47%', flexGrow: 1, minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 13, paddingVertical: 10, borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, choiceActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, choiceLabel: { color: colors.ink, fontSize: 13, fontWeight: '800' }, choiceLabelActive: { color: colors.primary }, choiceDetail: { color: colors.inkMuted, fontSize: 10, marginTop: 2 }, languageBlock: { marginTop: 3 }, voiceList: { gap: 7 }, help: { color: colors.inkMuted, fontSize: 13 }, missing: { flexDirection: 'row', gap: 9, padding: 13, borderRadius: radius.md, backgroundColor: colors.highlightSoft }, missingText: { flex: 1, color: colors.ink, fontSize: 12, lineHeight: 18 }, refresh: { marginTop: 23, minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule }, refreshText: { color: colors.primary, fontWeight: '900', fontSize: 13 }, footnote: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, marginTop: 14 },
});
