import { englishDeck } from './english-builder';

export const englishStarterDecks = [
  englishDeck({ id: 'en-id-a1-daily-foundations', name: 'Inggris A1 · Dasar Sehari-hari', summary: 'Perkenalan, keluarga, rumah, makanan, waktu, tempat, dan kebutuhan dasar.', description: '300 materi Inggris A1 untuk membangun percakapan pertama dalam kehidupan sehari-hari.', level: 'pemula', category: 'sehari-hari', color: '#365D7A', featured: true, tag: 'dasar-harian', nouns: [
    ['name','nama'],['family','keluarga'],['friend','teman'],['home','rumah'],['room','kamar'],['table','meja'],['chair','kursi'],['food','makanan'],['water','air'],['coffee','kopi'],['breakfast','sarapan'],['shop','toko'],['price','harga'],['school','sekolah'],['teacher','guru'],['street','jalan'],['station','stasiun'],['ticket','tiket'],['time','waktu'],['question','pertanyaan'],
  ], verbs: [['introduce myself','memperkenalkan diri'],['speak','berbicara'],['learn','belajar'],['live here','tinggal di sini'],['eat','makan'],['drink','minum'],['buy this','membeli ini'],['ask','bertanya'],['answer','menjawab'],['help','membantu']] }),
  englishDeck({ id: 'en-id-a2-routines-services', name: 'Inggris A2 · Rutinitas & Layanan', summary: 'Jadwal, hobi, kesehatan, belanja, transportasi, layanan, dan pekerjaan awal.', description: '300 materi Inggris A2 untuk menangani rutinitas dan layanan umum dengan lebih mandiri.', level: 'pemula', category: 'sehari-hari', color: '#4C7458', featured: true, tag: 'rutinitas-layanan', nouns: [
    ['schedule','jadwal'],['appointment','janji'],['weekend','akhir pekan'],['hobby','hobi'],['exercise','olahraga'],['invitation','undangan'],['clothing','pakaian'],['size','ukuran'],['receipt','struk'],['discount','diskon'],['package','paket'],['account','rekening'],['health','kesehatan'],['medicine','obat'],['symptom','gejala'],['clinic','klinik'],['journey','perjalanan'],['reservation','reservasi'],['course','kursus'],['workplace','tempat kerja'],
  ], verbs: [['arrange a meeting','mengatur pertemuan'],['postpone the plan','menunda rencana'],['join the activity','mengikuti kegiatan'],['try this on','mencoba ini'],['return the item','mengembalikan barang'],['send the package','mengirim paket'],['make an appointment','membuat janji'],['describe the problem','menjelaskan masalah'],['book a room','memesan kamar'],['apply for the job','melamar pekerjaan']] }),
  englishDeck({ id: 'en-id-b1-work-social-travel', name: 'Inggris B1 · Kerja, Sosial & Perjalanan', summary: 'Proyek, studi, komunikasi kerja, berita, hubungan sosial, dan perjalanan mandiri.', description: '300 materi Inggris B1 untuk menjelaskan pengalaman, berdiskusi, dan memecahkan masalah praktis.', level: 'menengah', category: 'kerja', color: '#6F587D', featured: true, tag: 'kerja-sosial', nouns: [
    ['project','proyek'],['deadline','tenggat'],['meeting','rapat'],['application','lamaran'],['experience','pengalaman'],['research','penelitian'],['result','hasil'],['discussion','diskusi'],['opinion','pendapat'],['argument','argumen'],['relationship','hubungan'],['community','komunitas'],['event','acara'],['news','berita'],['website','situs web'],['privacy','privasi'],['complaint','keluhan'],['solution','solusi'],['insurance','asuransi'],['connection','koneksi perjalanan'],
  ], verbs: [['organize the project','mengatur proyek'],['present the result','mempresentasikan hasil'],['apply for the position','melamar posisi'],['participate in the meeting','berpartisipasi dalam rapat'],['explain the issue','menjelaskan persoalan'],['express an opinion','menyampaikan pendapat'],['disagree politely','menyangkal dengan sopan'],['report the news','melaporkan berita'],['solve the problem','menyelesaikan masalah'],['change trains','berganti kereta']] }),
  englishDeck({ id: 'en-id-c1-academic-professional', name: 'Inggris C1 · Akademik & Profesional', summary: 'Analisis, riset, argumentasi, kebijakan, strategi, negosiasi, dan evaluasi.', description: '300 materi Inggris C1 untuk komunikasi akademik dan profesional yang tepat serta bernuansa.', level: 'lanjutan', category: 'kerja', color: '#76513F', featured: true, tag: 'akademik-profesional', nouns: [
    ['analysis','analisis'],['methodology','metodologi'],['hypothesis','hipotesis'],['evidence','bukti'],['source','sumber'],['dataset','kumpulan data'],['finding','temuan'],['publication','publikasi'],['framework','kerangka kerja'],['implication','implikasi'],['strategy','strategi'],['negotiation','negosiasi'],['agreement','kesepakatan'],['resource','sumber daya'],['priority','prioritas'],['requirement','persyaratan'],['implementation','pelaksanaan'],['policy','kebijakan'],['inequality','ketimpangan'],['perspective','perspektif'],
  ], verbs: [['analyze the evidence','menganalisis bukti'],['evaluate the method','menilai metode'],['cite the source','mengutip sumber'],['challenge the assumption','mempertanyakan asumsi'],['justify the decision','memberi alasan atas keputusan'],['negotiate the agreement','merundingkan kesepakatan'],['prioritize the requirement','memprioritaskan persyaratan'],['implement the strategy','melaksanakan strategi'],['assess the impact','menilai dampak'],['summarize the findings','merangkum temuan']] }),
];
