import { germanDeck } from './german-builder';

export const germanStarterDecks = [
  germanDeck({ id: 'de-id-a1-perkenalan', name: 'Jerman A1 · Perkenalan', summary: 'Sapaan, identitas, asal, bahasa, keluarga, dan percakapan pertama.', description: '300 kata, frasa, dan kalimat untuk memperkenalkan diri dan mengenal orang lain.', level: 'pemula', category: 'sehari-hari', color: '#315C49', featured: true, tag: 'perkenalan', nouns: [
    ['Name','nama','m'],['Vorname','nama depan','m'],['Nachname','nama belakang','m'],['Person','orang','f'],['Mann','pria','m'],['Frau','wanita','f'],['Kind','anak','n'],['Freund','teman laki-laki','m'],['Freundin','teman perempuan','f'],['Familie','keluarga','f'],['Vater','ayah','m'],['Mutter','ibu','f'],['Bruder','saudara laki-laki','m'],['Schwester','saudara perempuan','f'],['Beruf','profesi','m'],['Student','mahasiswa','m'],['Studentin','mahasiswi','f'],['Sprache','bahasa','f'],['Land','negara','n'],['Stadt','kota','f'],
  ], verbs: [['grüßen','zu grüßen','menyapa'],['sich vorstellen','sich vorzustellen','memperkenalkan diri'],['fragen','zu fragen','bertanya'],['antworten','zu antworten','menjawab'],['erzählen','zu erzählen','bercerita'],['zuhören','zuzuhören','mendengarkan'],['notieren','zu notieren','mencatat'],['erklären','zu erklären','menjelaskan'],['wiederholen','zu wiederholen','mengulangi'],['buchstabieren','zu buchstabieren','mengeja']] }),
  germanDeck({ id: 'de-id-a1-rumah-keluarga', name: 'Jerman A1 · Rumah & Keluarga', summary: 'Ruangan, perabot, pekerjaan rumah, keluarga, dan rutinitas di rumah.', description: '300 materi praktis untuk menyebut benda, mencari barang, dan berbicara tentang kehidupan rumah.', level: 'pemula', category: 'sehari-hari', color: '#8A593E', featured: true, tag: 'rumah', nouns: [
    ['Haus','rumah','n'],['Wohnung','apartemen','f'],['Zimmer','kamar','n'],['Wohnzimmer','ruang keluarga','n'],['Schlafzimmer','kamar tidur','n'],['Badezimmer','kamar mandi','n'],['Küche','dapur','f'],['Balkon','balkon','m'],['Garten','taman rumah','m'],['Tür','pintu','f'],['Fenster','jendela','n'],['Tisch','meja','m'],['Stuhl','kursi','m'],['Bett','tempat tidur','n'],['Schrank','lemari','m'],['Sofa','sofa','n'],['Lampe','lampu','f'],['Schlüssel','kunci','m'],['Nachbar','tetangga laki-laki','m'],['Miete','uang sewa','f'],
  ], verbs: [['wohnen','zu wohnen','tinggal'],['kochen','zu kochen','memasak'],['putzen','zu putzen','membersihkan'],['aufräumen','aufzuräumen','merapikan'],['öffnen','zu öffnen','membuka'],['schließen','zu schließen','menutup'],['schlafen','zu schlafen','tidur'],['waschen','zu waschen','mencuci'],['reparieren','zu reparieren','memperbaiki'],['umziehen','umzuziehen','pindah rumah']] }),
  germanDeck({ id: 'de-id-a1-makanan-belanja', name: 'Jerman A1 · Makanan & Belanja', summary: 'Bahan makanan, restoran, harga, pembayaran, dan kebutuhan belanja.', description: '300 materi dasar untuk berbelanja, memesan makanan, dan berbicara tentang selera.', level: 'pemula', category: 'sehari-hari', color: '#A46F24', featured: true, tag: 'makanan-belanja', nouns: [
    ['Brot','roti','n'],['Reis','nasi','m'],['Fleisch','daging','n'],['Fisch','ikan','m'],['Gemüse','sayuran','n'],['Obst','buah-buahan','n'],['Apfel','apel','m'],['Banane','pisang','f'],['Kartoffel','kentang','f'],['Wasser','air','n'],['Kaffee','kopi','m'],['Tee','teh','m'],['Milch','susu','f'],['Frühstück','sarapan','n'],['Mittagessen','makan siang','n'],['Abendessen','makan malam','n'],['Supermarkt','supermarket','m'],['Preis','harga','m'],['Rechnung','tagihan','f'],['Speisekarte','menu makanan','f'],
  ], verbs: [['essen','zu essen','makan'],['trinken','zu trinken','minum'],['kaufen','zu kaufen','membeli'],['bezahlen','zu bezahlen','membayar'],['bestellen','zu bestellen','memesan'],['probieren','zu probieren','mencicipi'],['schneiden','zu schneiden','memotong'],['vorbereiten','vorzubereiten','menyiapkan'],['suchen','zu suchen','mencari'],['kochen','zu kochen','memasak']] }),
  germanDeck({ id: 'de-id-a1-kota-perjalanan', name: 'Jerman A1 · Kota, Taman & Perjalanan', summary: 'Taman, tempat umum, arah, transportasi, tiket, hotel, dan perjalanan dasar.', description: '300 materi untuk beraktivitas di taman, bergerak di kota, bertanya arah, dan menangani perjalanan sederhana.', level: 'pemula', category: 'perjalanan', color: '#356A78', featured: true, tag: 'kota-perjalanan', nouns: [
    ['Bahnhof','stasiun kereta','m'],['Haltestelle','halte','f'],['Flughafen','bandara','m'],['Hotel','hotel','n'],['Straße','jalan','f'],['Kreuzung','persimpangan','f'],['Spielplatz','taman bermain','m'],['Wiese','padang rumput','f'],['Park','taman kota','m'],['Baum','pohon','m'],['Apotheke','apotek','f'],['Krankenhaus','rumah sakit','n'],['Blume','bunga','f'],['Brücke','jembatan','f'],['Zug','kereta','m'],['Bus','bus','m'],['Fahrrad','sepeda','n'],['Fahrkarte','tiket perjalanan','f'],['Koffer','koper','m'],['Reisepass','paspor','m'],
  ], verbs: [['fahren','zu fahren','pergi dengan kendaraan'],['gehen','zu gehen','pergi berjalan kaki'],['reisen','zu reisen','bepergian'],['ankommen','anzukommen','tiba'],['abfahren','abzufahren','berangkat'],['umsteigen','umzusteigen','berganti kendaraan'],['reservieren','zu reservieren','memesan tempat'],['warten','zu warten','menunggu'],['zeigen','zu zeigen','menunjukkan'],['finden','zu finden','menemukan']] }),
  germanDeck({ id: 'de-id-a1-percakapan-harian', name: 'Jerman A1 · Percakapan Harian', summary: 'Waktu, cuaca, janji, perasaan, bantuan, dan interaksi sopan sehari-hari.', description: '300 materi serbaguna untuk percakapan singkat yang paling sering dibutuhkan setiap hari.', level: 'pemula', category: 'sehari-hari', color: '#6B5686', featured: true, tag: 'percakapan-harian', nouns: [
    ['Tag','hari','m'],['Woche','minggu','f'],['Monat','bulan','m'],['Jahr','tahun','n'],['Morgen','pagi','m'],['Abend','malam','m'],['Uhr','jam','f'],['Zeit','waktu','f'],['Termin','janji','m'],['Pause','istirahat','f'],['Wetter','cuaca','n'],['Regen','hujan','m'],['Sonne','matahari','f'],['Problem','masalah','n'],['Frage','pertanyaan','f'],['Antwort','jawaban','f'],['Hilfe','bantuan','f'],['Idee','ide','f'],['Nachricht','pesan','f'],['Telefon','telepon','n'],
  ], verbs: [['fragen','zu fragen','bertanya'],['antworten','zu antworten','menjawab'],['helfen','zu helfen','membantu'],['anrufen','anzurufen','menelepon'],['warten','zu warten','menunggu'],['beginnen','zu beginnen','memulai'],['enden','zu enden','berakhir'],['treffen','zu treffen','bertemu'],['verstehen','zu verstehen','memahami'],['wiederholen','zu wiederholen','mengulangi']] }),
  germanDeck({ id: 'de-id-a2-rutinitas-waktu', name: 'Jerman A2 · Rutinitas & Waktu', summary: 'Jadwal, kebiasaan, pekerjaan rumah, janji, keterlambatan, dan rencana mingguan.', description: '320 materi A2 untuk menceritakan rutinitas, mengatur waktu, dan menjelaskan perubahan rencana.', level: 'pemula', category: 'sehari-hari', color: '#58764C', featured: true, tag: 'rutinitas-waktu', nouns: [
    ['Alltag','keseharian','m'],['Gewohnheit','kebiasaan','f'],['Tagesablauf','rutinitas harian','m'],['Wecker','jam alarm','m'],['Kalender','kalender','m'],['Stunde','jam','f'],['Minute','menit','f'],['Wochenende','akhir pekan','n'],['Feiertag','hari libur','m'],['Freizeit','waktu luang','f'],['Verabredung','janji bertemu','f'],['Verspätung','keterlambatan','f'],['Plan','rencana','m'],['Änderung','perubahan','f'],['Liste','daftar','f'],['Haushalt','rumah tangga','m'],['Wäsche','cucian','f'],['Müll','sampah','m'],['Einkauf','belanjaan','m'],['Ruhe','ketenangan','f'],
  ], verbs: [['aufstehen','aufzustehen','bangun tidur'],['sich beeilen','sich zu beeilen','bergegas'],['frühstücken','zu frühstücken','sarapan'],['erledigen','zu erledigen','menyelesaikan urusan'],['verschieben','zu verschieben','menunda'],['absagen','abzusagen','membatalkan'],['sich ausruhen','sich auszuruhen','beristirahat'],['vorbereiten','vorzubereiten','mempersiapkan'],['vergessen','zu vergessen','melupakan'],['sich erinnern','sich zu erinnern','mengingat'],['pünktlich kommen','pünktlich zu kommen','datang tepat waktu'],['Zeit sparen','Zeit zu sparen','menghemat waktu']] }),
  germanDeck({ id: 'de-id-a2-hobi-pergaulan', name: 'Jerman A2 · Hobi & Pergaulan', summary: 'Olahraga, musik, budaya, undangan, akhir pekan, dan hubungan pertemanan.', description: '320 materi A2 untuk berbicara tentang minat, mengajak orang, dan menceritakan kegiatan bersama.', level: 'pemula', category: 'sehari-hari', color: '#775C8A', featured: true, tag: 'hobi-pergaulan', nouns: [
    ['Hobby','hobi','n'],['Sport','olahraga','m'],['Mannschaft','tim','f'],['Training','latihan olahraga','n'],['Spiel','permainan','n'],['Musik','musik','f'],['Lied','lagu','n'],['Instrument','alat musik','n'],['Konzert','konser','n'],['Film','film','m'],['Kino','bioskop','n'],['Buch','buku','n'],['Geschichte','cerita','f'],['Ausflug','wisata singkat','m'],['Verein','perkumpulan','m'],['Party','pesta','f'],['Gast','tamu','m'],['Geschenk','hadiah','n'],['Bekannte','kenalan perempuan','f'],['Freundschaft','persahabatan','f'],
  ], verbs: [['trainieren','zu trainieren','berlatih'],['mitmachen','mitzumachen','ikut serta'],['gewinnen','zu gewinnen','menang'],['verlieren','zu verlieren','kalah'],['tanzen','zu tanzen','menari'],['singen','zu singen','bernyanyi'],['fotografieren','zu fotografieren','memotret'],['besuchen','zu besuchen','mengunjungi'],['sich verabreden','sich zu verabreden','membuat janji bertemu'],['sich unterhalten','sich zu unterhalten','mengobrol'],['Spaß haben','Spaß zu haben','bersenang-senang'],['kennenlernen','kennenzulernen','berkenalan']] }),
  germanDeck({ id: 'de-id-a2-pakaian-layanan', name: 'Jerman A2 · Pakaian & Layanan', summary: 'Ukuran, warna, mencoba pakaian, penukaran, salon, paket, bank, dan perbaikan.', description: '320 materi A2 untuk berbelanja lebih rinci serta menggunakan layanan sehari-hari.', level: 'pemula', category: 'sehari-hari', color: '#A0684E', featured: true, tag: 'pakaian-layanan', nouns: [
    ['Kleidung','pakaian','f'],['Hemd','kemeja','n'],['Hose','celana','f'],['Kleid','gaun','n'],['Jacke','jaket','f'],['Schuh','sepatu','m'],['Größe','ukuran','f'],['Farbe','warna','f'],['Umkleidekabine','kamar pas','f'],['Kasse','kasir','f'],['Kassenbon','struk belanja','m'],['Rabatt','diskon','m'],['Umtausch','penukaran barang','m'],['Garantie','garansi','f'],['Paket','paket','n'],['Friseur','penata rambut laki-laki','m'],['Werkstatt','bengkel','f'],['Konto','rekening','n'],['Geldautomat','mesin ATM','m'],['Kundendienst','layanan pelanggan','m'],
  ], verbs: [['anprobieren','anzuprobieren','mencoba pakaian'],['passen','zu passen','pas'],['umtauschen','umzutauschen','menukar barang'],['zurückgeben','zurückzugeben','mengembalikan barang'],['abholen','abzuholen','mengambil'],['schicken','zu schicken','mengirim'],['reparieren','zu reparieren','memperbaiki'],['überweisen','zu überweisen','mentransfer uang'],['abheben','abzuheben','menarik uang'],['sich anmelden','sich anzumelden','mendaftar'],['stornieren','zu stornieren','membatalkan pesanan'],['sich entscheiden','sich zu entscheiden','memutuskan']] }),
  germanDeck({ id: 'de-id-a2-kesehatan-tubuh', name: 'Jerman A2 · Kesehatan & Tubuh', summary: 'Bagian tubuh, gejala, apotek, janji dokter, kebiasaan sehat, dan saran sederhana.', description: '320 materi A2 untuk menggambarkan kondisi tubuh, meminta bantuan, dan memahami petunjuk kesehatan.', level: 'pemula', category: 'sehari-hari', color: '#3C7970', featured: true, tag: 'kesehatan-tubuh', nouns: [
    ['Kopf','kepala','m'],['Auge','mata','n'],['Ohr','telinga','n'],['Hals','tenggorokan','m'],['Rücken','punggung','m'],['Bauch','perut','m'],['Arm','lengan','m'],['Hand','tangan','f'],['Bein','tungkai','n'],['Fuß','kaki','m'],['Husten','batuk','m'],['Erkältung','pilek','f'],['Allergie','alergi','f'],['Tablette','tablet obat','f'],['Salbe','salep','f'],['Tropfen','obat tetes','pl'],['Sprechstunde','jam konsultasi','f'],['Krankmeldung','surat sakit','f'],['Bewegung','aktivitas fisik','f'],['Ernährung','pola makan','f'],
  ], verbs: [['wehtun','wehzutun','terasa sakit'],['abhusten','abzuhusten','mengeluarkan batuk'],['niesen','zu niesen','bersin'],['sich verletzen','sich zu verletzen','terluka'],['messen','zu messen','mengukur'],['einnehmen','einzunehmen','mengonsumsi obat'],['sich erholen','sich zu erholen','memulihkan diri'],['vermeiden','zu vermeiden','menghindari'],['sich bewegen','sich zu bewegen','bergerak aktif'],['atmen','zu atmen','bernapas'],['einen Termin machen','einen Termin zu machen','membuat janji'],['gesund bleiben','gesund zu bleiben','tetap sehat']] }),
  germanDeck({ id: 'de-id-a2-sekolah-pekerjaan', name: 'Jerman A2 · Sekolah & Pekerjaan Awal', summary: 'Pelajaran, kursus, magang, tugas kerja, jadwal, kemampuan, dan komunikasi dasar.', description: '320 materi A2 untuk mengikuti kelas, memulai pekerjaan, dan menjelaskan pengalaman sederhana.', level: 'pemula', category: 'kerja', color: '#48688A', featured: true, tag: 'sekolah-pekerjaan', nouns: [
    ['Schule','sekolah','f'],['Klasse','kelas','f'],['Kurs','kursus','m'],['Unterricht','pelajaran','m'],['Lehrer','guru laki-laki','m'],['Lehrerin','guru perempuan','f'],['Schüler','murid laki-laki','m'],['Übung','latihan soal','f'],['Fehler','kesalahan','m'],['Note','nilai','f'],['Ausbildung','pendidikan kejuruan','f'],['Praktikum','magang','n'],['Firma','perusahaan','f'],['Abteilung','departemen','f'],['Arbeitszeit','jam kerja','f'],['Schicht','giliran kerja','f'],['Kunde','pelanggan laki-laki','m'],['E-Mail','surel','f'],['Datei','berkas digital','f'],['Drucker','mesin pencetak','m'],
  ], verbs: [['üben','zu üben','berlatih'],['bestehen','zu bestehen','lulus'],['korrigieren','zu korrigieren','mengoreksi'],['sich melden','sich zu melden','menghubungi'],['sich bewerben','sich zu bewerben','melamar'],['verdienen','zu verdienen','memperoleh gaji'],['kopieren','zu kopieren','menyalin'],['drucken','zu drucken','mencetak'],['speichern','zu speichern','menyimpan'],['erklären','zu erklären','menjelaskan'],['Bescheid geben','Bescheid zu geben','memberi kabar'],['Erfahrung sammeln','Erfahrung zu sammeln','mengumpulkan pengalaman']] }),
  germanDeck({ id: 'de-id-b1-kerja-studi', name: 'Jerman B1 · Kerja & Studi', summary: 'Kantor, pendidikan, tugas, rapat, aplikasi kerja, dan komunikasi profesional.', description: '300 materi tingkat menengah untuk belajar, bekerja, menyusun tugas, dan berkolaborasi.', level: 'menengah', category: 'kerja', color: '#3E5F74', tag: 'kerja-studi', nouns: [
    ['Arbeitsplatz','tempat kerja','m'],['Büro','kantor','n'],['Kollege','rekan kerja laki-laki','m'],['Kollegin','rekan kerja perempuan','f'],['Chef','atasan laki-laki','m'],['Aufgabe','tugas','f'],['Projekt','proyek','n'],['Besprechung','rapat','f'],['Vertrag','kontrak','m'],['Bewerbung','lamaran kerja','f'],['Lebenslauf','riwayat hidup','m'],['Gehalt','gaji','n'],['Erfahrung','pengalaman','f'],['Universität','universitas','f'],['Prüfung','ujian','f'],['Vorlesung','kuliah','f'],['Hausaufgabe','pekerjaan rumah','f'],['Forschung','penelitian','f'],['Ergebnis','hasil','n'],['Frist','tenggat','f'],
  ], verbs: [['planen','zu planen','merencanakan'],['organisieren','zu organisieren','mengatur'],['erklären','zu erklären','menjelaskan'],['präsentieren','zu präsentieren','mempresentasikan'],['einstellen','einzustellen','merekrut'],['unterschreiben','zu unterschreiben','menandatangani'],['teilnehmen','teilzunehmen','berpartisipasi'],['vorbereiten','vorzubereiten','mempersiapkan'],['prüfen','zu prüfen','memeriksa'],['verbessern','zu verbessern','meningkatkan']] }),
  germanDeck({ id: 'de-id-b1-kesehatan-layanan', name: 'Jerman B1 · Kesehatan & Layanan', summary: 'Keluhan kesehatan, dokter, administrasi, layanan publik, dan pemecahan masalah.', description: '300 materi tingkat menengah untuk menjelaskan kebutuhan kesehatan dan mengurus layanan.', level: 'menengah', category: 'sehari-hari', color: '#397065', tag: 'kesehatan-layanan', nouns: [
    ['Gesundheit','kesehatan','f'],['Krankheit','penyakit','f'],['Arzt','dokter laki-laki','m'],['Ärztin','dokter perempuan','f'],['Praxis','tempat praktik dokter','f'],['Medikament','obat','n'],['Rezept','resep dokter','n'],['Schmerz','rasa sakit','m'],['Fieber','demam','n'],['Untersuchung','pemeriksaan','f'],['Versicherung','asuransi','f'],['Notfall','keadaan darurat','m'],['Behörde','instansi pemerintah','f'],['Formular','formulir','n'],['Antrag','permohonan resmi','m'],['Ausweis','kartu identitas','m'],['Gebühr','biaya layanan','f'],['Beratung','konsultasi','f'],['Beschwerde','keluhan resmi','f'],['Lösung','solusi','f'],
  ], verbs: [['untersuchen','zu untersuchen','memeriksa'],['behandeln','zu behandeln','mengobati'],['vereinbaren','zu vereinbaren','membuat kesepakatan'],['beantragen','zu beantragen','mengajukan permohonan'],['ausfüllen','auszufüllen','mengisi formulir'],['unterschreiben','zu unterschreiben','menandatangani'],['beraten','zu beraten','memberi konsultasi'],['erklären','zu erklären','menjelaskan'],['lösen','zu lösen','menyelesaikan'],['reklamieren','zu reklamieren','mengajukan keluhan']] }),
  germanDeck({ id: 'de-id-b1-sosial-media', name: 'Jerman B1 · Sosial & Media', summary: 'Hubungan sosial, acara, berita, internet, opini, dan diskusi sehari-hari.', description: '300 materi tingkat menengah untuk berdiskusi, menyampaikan opini, dan memahami media.', level: 'menengah', category: 'sehari-hari', color: '#85596B', tag: 'sosial-media', nouns: [
    ['Beziehung','hubungan','f'],['Gemeinschaft','komunitas','f'],['Einladung','undangan','f'],['Veranstaltung','acara','f'],['Feier','perayaan','f'],['Gespräch','percakapan','n'],['Meinung','pendapat','f'],['Argument','argumen','n'],['Nachricht','berita','f'],['Zeitung','surat kabar','f'],['Sendung','acara siaran','f'],['Internet','internet','n'],['Webseite','situs web','f'],['Beitrag','unggahan atau kontribusi','m'],['Kommentar','komentar','m'],['Foto','foto','n'],['Video','video','n'],['Datenschutz','perlindungan data','m'],['Gerücht','rumor','n'],['Wahrheit','kebenaran','f'],
  ], verbs: [['diskutieren','zu diskutieren','berdiskusi'],['zustimmen','zuzustimmen','menyetujui'],['widersprechen','zu widersprechen','menyangkal'],['berichten','zu berichten','melaporkan'],['veröffentlichen','zu veröffentlichen','menerbitkan'],['teilen','zu teilen','membagikan'],['kommentieren','zu kommentieren','mengomentari'],['einladen','einzuladen','mengundang'],['feiern','zu feiern','merayakan'],['vertrauen','zu vertrauen','memercayai']] }),
  germanDeck({ id: 'de-id-c1-argumen-masyarakat', name: 'Jerman C1 · Argumen & Masyarakat', summary: 'Nuansa argumen, kebijakan, masyarakat, ekonomi, hukum, dan analisis isu.', description: '300 materi lanjutan untuk membangun argumen terstruktur dan membahas isu sosial secara bernuansa.', level: 'lanjutan', category: 'lainnya', color: '#694B3F', tag: 'argumen-masyarakat', nouns: [
    ['Gesellschaft','masyarakat','f'],['Politik','politik','f'],['Regierung','pemerintah','f'],['Demokratie','demokrasi','f'],['Gesetz','undang-undang','n'],['Gerechtigkeit','keadilan','f'],['Freiheit','kebebasan','f'],['Verantwortung','tanggung jawab','f'],['Wirtschaft','ekonomi','f'],['Unternehmen','perusahaan','n'],['Wettbewerb','persaingan','m'],['Ungleichheit','ketimpangan','f'],['Bildung','pendidikan','f'],['Migration','migrasi','f'],['Integration','integrasi','f'],['Umwelt','lingkungan','f'],['Maßnahme','langkah kebijakan','f'],['Auswirkung','dampak','f'],['Zusammenhang','keterkaitan','m'],['Standpunkt','sudut pandang','m'],
  ], verbs: [['begründen','zu begründen','memberi alasan'],['behaupten','zu behaupten','mengklaim'],['widerlegen','zu widerlegen','membantah'],['berücksichtigen','zu berücksichtigen','mempertimbangkan'],['bewerten','zu bewerten','menilai'],['fördern','zu fördern','mendorong'],['verhindern','zu verhindern','mencegah'],['voraussetzen','vorauszusetzen','mensyaratkan'],['hinterfragen','zu hinterfragen','mempertanyakan secara kritis'],['schlussfolgern','zu schlussfolgern','menarik kesimpulan']] }),
  germanDeck({ id: 'de-id-c1-akademik-profesional', name: 'Jerman C1 · Akademik & Profesional', summary: 'Riset, strategi, negosiasi, presentasi, evaluasi, dan komunikasi formal.', description: '300 materi lanjutan untuk konteks akademik dan profesional yang menuntut ketepatan bahasa.', level: 'lanjutan', category: 'kerja', color: '#44526F', tag: 'akademik-profesional', nouns: [
    ['Analyse','analisis','f'],['Methode','metode','f'],['Hypothese','hipotesis','f'],['Theorie','teori','f'],['Nachweis','bukti','m'],['Quelle','sumber','f'],['Datensatz','kumpulan data','m'],['Fachgebiet','bidang keahlian','n'],['Veröffentlichung','publikasi','f'],['Erkenntnis','temuan','f'],['Strategie','strategi','f'],['Verhandlung','negosiasi','f'],['Vereinbarung','kesepakatan','f'],['Ressource','sumber daya','f'],['Risiko','risiko','n'],['Priorität','prioritas','f'],['Rückmeldung','umpan balik','f'],['Leistung','kinerja','f'],['Anforderung','persyaratan','f'],['Umsetzung','pelaksanaan','f'],
  ], verbs: [['analysieren','zu analysieren','menganalisis'],['nachweisen','nachzuweisen','membuktikan'],['zitieren','zu zitieren','mengutip'],['auswerten','auszuwerten','mengevaluasi data'],['verhandeln','zu verhandeln','bernegosiasi'],['abstimmen','abzustimmen','menyelaraskan'],['priorisieren','zu priorisieren','memprioritaskan'],['umsetzen','umzusetzen','melaksanakan'],['einschätzen','einzuschätzen','menaksir'],['zusammenfassen','zusammenzufassen','merangkum']] }),
];
