import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { radius, ThemeColors } from '../../theme/tokens';
import { useTheme } from '../../theme/ThemeProvider';
import type { DailyPoint, MasterySlice, ModeSlice } from './statistics.repository';

const gradeLabels = ['Baru', 'Dipelajari', 'Familiar', 'Dikuasai'];
export function Metric({ value, label, detail }: { value: string | number; label: string; detail?: string }) { const { colors } = useTheme(); const styles = createStyles(colors); return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text>{detail ? <Text style={styles.metricDetail}>{detail}</Text> : null}</View>; }
export function MasteryBars({ data }: { data: MasterySlice[] }) { const { colors } = useTheme(); const styles = createStyles(colors); const total = data.reduce((sum, row) => sum + row.count, 0); return <View style={styles.block}>{data.map((row) => { const percent = total ? Math.round(row.count / total * 100) : 0; return <View key={row.grade} style={styles.barRow}><View style={styles.barCopy}><Text style={styles.barLabel}>{gradeLabels[row.grade]}</Text><Text style={styles.barValue}>{row.count} · {percent}%</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${percent}%`, opacity: 0.48 + row.grade * 0.17 }]} /></View></View>; })}</View>; }
export function ModeBreakdown({ data }: { data: ModeSlice[] }) { const { colors } = useTheme(); const styles = createStyles(colors); return <View style={styles.modeGrid}>{data.map((row) => <View key={row.mode} style={styles.mode}><Ionicons name={row.mode === 'flashcard' ? 'copy-outline' : 'mic-outline'} size={21} color={colors.primary} /><Text style={styles.modeTitle}>{row.mode === 'flashcard' ? 'Kartu flash' : 'Dikte'}</Text><Text style={styles.modeValue}>{row.answers} jawaban</Text><Text style={styles.modeDetail}>{row.answers ? `${Math.round(row.correct / row.answers * 100)}% berhasil` : 'Belum dimainkan'}</Text></View>)}</View>; }
export function ActivityBars({ data }: { data: DailyPoint[] }) { const { colors } = useTheme(); const styles = createStyles(colors); const max = Math.max(1, ...data.map((row) => row.answers)); return <View><View style={styles.chart}>{data.map((row) => <View key={row.dateKey} accessibilityLabel={`${row.dateKey}, ${row.answers} jawaban`} style={styles.column}><View style={[styles.columnFill, { height: Math.max(row.answers ? 5 : 2, Math.round(row.answers / max * 70)), backgroundColor: row.answers ? colors.primary : colors.rule }]} /></View>)}</View><View style={styles.chartLabels}><Text style={styles.chartLabel}>14 hari lalu</Text><Text style={styles.chartLabel}>Hari ini</Text></View></View>; }
export function EmptyStatistics({ onPractice, actionLabel = 'Mulai latihan' }: { onPractice?: () => void; actionLabel?: string }) { const { colors } = useTheme(); const styles = createStyles(colors); return <View style={styles.empty}><Ionicons name="analytics-outline" size={31} color={colors.primary} /><Text style={styles.emptyTitle}>Belum ada bukti latihan</Text><Text style={styles.emptyText}>Statistik akan terbentuk dari rating Kartu flash dan hasil final Dikte.</Text>{onPractice ? <Pressable onPress={onPractice} style={styles.button}><Text style={styles.buttonText}>{actionLabel}</Text></Pressable> : null}</View>; }
export function formatDuration(ms: number) { const minutes = Math.round(ms / 60000); if (minutes < 1) return ms ? '<1 mnt' : '0 mnt'; if (minutes < 60) return `${minutes} mnt`; return `${Math.floor(minutes / 60)}j ${minutes % 60}m`; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ metric: { flex: 1, minWidth: '43%', padding: 15, borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, metricValue: { color: colors.ink, fontSize: 23, fontWeight: '900' }, metricLabel: { color: colors.primary, fontSize: 11, fontWeight: '900', marginTop: 3 }, metricDetail: { color: colors.inkMuted, fontSize: 9, marginTop: 4 }, block: { gap: 12 }, barRow: { gap: 6 }, barCopy: { flexDirection: 'row', justifyContent: 'space-between' }, barLabel: { color: colors.ink, fontSize: 12, fontWeight: '800' }, barValue: { color: colors.inkMuted, fontSize: 11 }, track: { height: 7, borderRadius: 5, backgroundColor: colors.primarySoft, overflow: 'hidden' }, fill: { height: 7, borderRadius: 5, backgroundColor: colors.primary }, modeGrid: { flexDirection: 'row', gap: 9 }, mode: { flex: 1, padding: 15, borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, modeTitle: { color: colors.ink, fontSize: 12, fontWeight: '900', marginTop: 9 }, modeValue: { color: colors.primary, fontSize: 17, fontWeight: '900', marginTop: 5 }, modeDetail: { color: colors.inkMuted, fontSize: 10, marginTop: 2 }, chart: { height: 78, flexDirection: 'row', alignItems: 'flex-end', gap: 4, paddingTop: 7, borderBottomWidth: 1, borderBottomColor: colors.rule }, column: { flex: 1, height: 70, justifyContent: 'flex-end' }, columnFill: { width: '100%', borderTopLeftRadius: 3, borderTopRightRadius: 3 }, chartLabels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 }, chartLabel: { color: colors.inkMuted, fontSize: 9 }, empty: { alignItems: 'center', padding: 27, borderRadius: radius.lg, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', marginTop: 10 }, emptyText: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 6 }, button: { marginTop: 15, paddingHorizontal: 15, paddingVertical: 10, borderRadius: radius.md, backgroundColor: colors.primary }, buttonText: { color: colors.primaryInk, fontSize: 12, fontWeight: '900' } });
