import { and, desc, eq, gte, sql } from 'drizzle-orm';
import type { Database } from '../decks/deck.repository';
import { decks, entries, masteryStates, practiceAnswers, practiceSessions } from '../../db/schema';
import { dateKey, startOfDay } from '../history/history.repository';

export type MasterySlice = { grade: number; count: number };
export type ModeSlice = { mode: 'flashcard' | 'dictation'; answers: number; correct: number; durationMs: number };
export type DailyPoint = { dateKey: string; answers: number; correct: number };
export type GlobalStatistics = { decks: number; archivedDecks: number; entries: number; favorites: number; mastered: number; sessions: number; answers: number; correct: number; accuracy: number | null; durationMs: number; corrected: number; activeDays: number; currentStreak: number; mastery: MasterySlice[]; modes: ModeSlice[]; daily: DailyPoint[]; topDecks: { id: number; name: string; color: string | null; answers: number; correct: number }[] };
export type DeckStatistics = { deck: { id: number; name: string; color: string | null }; entries: number; favorites: number; answers: number; correct: number; accuracy: number | null; lastPracticedAt: Date | null; mastery: MasterySlice[]; modes: ModeSlice[]; daily: DailyPoint[]; difficult: { id: number; sourceText: string; translatedText: string; attempts: number; correct: number }[] };
export type EntryStatistics = { answers: number; correct: number; accuracy: number | null; averageResponseMs: number | null; lastPracticedAt: Date | null; corrected: number; modes: ModeSlice[]; recent: { id: number; mode: 'flashcard' | 'dictation'; rating: 'again' | 'hard' | 'good' | 'easy' | null; isCorrect: boolean; manuallyCorrected: boolean; responseTimeMs: number; answeredAt: Date }[] };

const accuracy = (correct: number, answers: number) => answers ? Math.round(correct / answers * 100) : null;
function masteryRows(rows: { grade: number; count: number }[]) { return [0, 1, 2, 3].map((grade) => ({ grade, count: rows.find((row) => row.grade === grade)?.count ?? 0 })); }
function modeRows(rows: { mode: 'flashcard' | 'dictation'; answers: number; correct: number; durationMs: number }[]) { return (['flashcard', 'dictation'] as const).map((mode) => rows.find((row) => row.mode === mode) ?? { mode, answers: 0, correct: 0, durationMs: 0 }); }
function dailyPoints(rows: { answeredAt: Date; isCorrect: boolean }[], days = 14, now = new Date()) { const start = startOfDay(now); start.setDate(start.getDate() - days + 1); const map = new Map<string, DailyPoint>(); for (let day = new Date(start); day <= now; day.setDate(day.getDate() + 1)) { const key = dateKey(day); map.set(key, { dateKey: key, answers: 0, correct: 0 }); } rows.forEach((row) => { const point = map.get(dateKey(row.answeredAt)); if (point) { point.answers += 1; point.correct += Number(row.isCorrect); } }); return [...map.values()]; }
function streak(rows: { answeredAt: Date }[], now = new Date()) { const days = new Set(rows.map((row) => dateKey(row.answeredAt))); if (!days.size) return { activeDays: 0, currentStreak: 0 }; let cursor = startOfDay(now); if (!days.has(dateKey(cursor))) { cursor.setDate(cursor.getDate() - 1); if (!days.has(dateKey(cursor))) return { activeDays: days.size, currentStreak: 0 }; } let currentStreak = 0; while (days.has(dateKey(cursor))) { currentStreak += 1; cursor.setDate(cursor.getDate() - 1); } return { activeDays: days.size, currentStreak }; }

export async function getGlobalStatistics(database: Database, now = new Date()): Promise<GlobalStatistics> {
  const since = startOfDay(now); since.setDate(since.getDate() - 13);
  const [deckCounts, entryCounts, mastery, totals, modes, recent, allDates, topDecks] = await Promise.all([
    database.select({ decks: sql<number>`sum(case when ${decks.isArchived} = 0 then 1 else 0 end)`, archived: sql<number>`sum(case when ${decks.isArchived} = 1 then 1 else 0 end)` }).from(decks),
    database.select({ entries: sql<number>`count(*)`, favorites: sql<number>`sum(case when ${entries.isFavorite} = 1 then 1 else 0 end)` }).from(entries),
    database.select({ grade: masteryStates.grade, count: sql<number>`count(*)` }).from(masteryStates).groupBy(masteryStates.grade),
    database.select({ sessions: sql<number>`count(distinct case when ${practiceSessions.completedAt} is not null then ${practiceSessions.id} end)`, durationMs: sql<number>`coalesce(sum(case when ${practiceSessions.completedAt} is not null then ${practiceSessions.durationMs} else 0 end),0)` }).from(practiceSessions),
    database.select({ mode: practiceAnswers.mode, answers: sql<number>`count(*)`, correct: sql<number>`sum(case when ${practiceAnswers.isCorrect} = 1 then 1 else 0 end)`, durationMs: sql<number>`coalesce(sum(${practiceAnswers.responseTimeMs}),0)` }).from(practiceAnswers).groupBy(practiceAnswers.mode),
    database.select({ answeredAt: practiceAnswers.answeredAt, isCorrect: practiceAnswers.isCorrect }).from(practiceAnswers).where(gte(practiceAnswers.answeredAt, since)),
    database.select({ answeredAt: practiceAnswers.answeredAt }).from(practiceAnswers),
    database.select({ id: decks.id, name: decks.name, color: decks.color, answers: sql<number>`count(${practiceAnswers.id})`, correct: sql<number>`sum(case when ${practiceAnswers.isCorrect} = 1 then 1 else 0 end)` }).from(decks).innerJoin(entries, eq(entries.deckId, decks.id)).innerJoin(practiceAnswers, eq(practiceAnswers.entryId, entries.id)).groupBy(decks.id).orderBy(desc(sql`count(${practiceAnswers.id})`)).limit(5),
  ]);
  const mode = modeRows(modes); const answers = mode.reduce((sum, row) => sum + row.answers, 0); const correct = mode.reduce((sum, row) => sum + row.correct, 0); const correctedRows = await database.select({ count: sql<number>`count(*)` }).from(practiceAnswers).where(eq(practiceAnswers.manuallyCorrected, true)); const dayStats = streak(allDates, now);
  const masteryData = masteryRows(mastery); return { decks: deckCounts[0]?.decks ?? 0, archivedDecks: deckCounts[0]?.archived ?? 0, entries: entryCounts[0]?.entries ?? 0, favorites: entryCounts[0]?.favorites ?? 0, mastered: masteryData[3].count, sessions: totals[0]?.sessions ?? 0, answers, correct, accuracy: accuracy(correct, answers), durationMs: totals[0]?.durationMs ?? 0, corrected: correctedRows[0]?.count ?? 0, ...dayStats, mastery: masteryData, modes: mode, daily: dailyPoints(recent, 14, now), topDecks };
}

export async function getDeckStatistics(database: Database, deckId: number, now = new Date()): Promise<DeckStatistics | undefined> {
  const deck = await database.query.decks.findFirst({ where: eq(decks.id, deckId) }); if (!deck) return undefined; const since = startOfDay(now); since.setDate(since.getDate() - 13);
  const [counts, mastery, modes, recent, difficult, last] = await Promise.all([
    database.select({ entries: sql<number>`count(*)`, favorites: sql<number>`sum(case when ${entries.isFavorite} = 1 then 1 else 0 end)` }).from(entries).where(eq(entries.deckId, deckId)),
    database.select({ grade: masteryStates.grade, count: sql<number>`count(*)` }).from(entries).leftJoin(masteryStates, eq(masteryStates.entryId, entries.id)).where(eq(entries.deckId, deckId)).groupBy(masteryStates.grade),
    database.select({ mode: practiceAnswers.mode, answers: sql<number>`count(*)`, correct: sql<number>`sum(case when ${practiceAnswers.isCorrect} = 1 then 1 else 0 end)`, durationMs: sql<number>`coalesce(sum(${practiceAnswers.responseTimeMs}),0)` }).from(practiceAnswers).innerJoin(entries, eq(entries.id, practiceAnswers.entryId)).where(eq(entries.deckId, deckId)).groupBy(practiceAnswers.mode),
    database.select({ answeredAt: practiceAnswers.answeredAt, isCorrect: practiceAnswers.isCorrect }).from(practiceAnswers).innerJoin(entries, eq(entries.id, practiceAnswers.entryId)).where(and(eq(entries.deckId, deckId), gte(practiceAnswers.answeredAt, since))),
    database.select({ id: entries.id, sourceText: entries.sourceText, translatedText: entries.translatedText, attempts: sql<number>`count(${practiceAnswers.id})`, correct: sql<number>`sum(case when ${practiceAnswers.isCorrect} = 1 then 1 else 0 end)` }).from(entries).innerJoin(practiceAnswers, eq(practiceAnswers.entryId, entries.id)).where(eq(entries.deckId, deckId)).groupBy(entries.id).having(sql`count(${practiceAnswers.id}) >= 2`).orderBy(sql`1.0 * sum(case when ${practiceAnswers.isCorrect} = 1 then 1 else 0 end) / count(${practiceAnswers.id}) asc`, desc(sql`count(${practiceAnswers.id})`)).limit(5),
    database.select({ at: sql<Date | null>`max(${practiceAnswers.answeredAt})` }).from(practiceAnswers).innerJoin(entries, eq(entries.id, practiceAnswers.entryId)).where(eq(entries.deckId, deckId)),
  ]);
  const mode = modeRows(modes); const answers = mode.reduce((sum, row) => sum + row.answers, 0); const correct = mode.reduce((sum, row) => sum + row.correct, 0); return { deck: { id: deck.id, name: deck.name, color: deck.color }, entries: counts[0]?.entries ?? 0, favorites: counts[0]?.favorites ?? 0, answers, correct, accuracy: accuracy(correct, answers), lastPracticedAt: last[0]?.at ?? null, mastery: masteryRows(mastery.map((row) => ({ grade: row.grade ?? 0, count: row.count }))), modes: mode, daily: dailyPoints(recent, 14, now), difficult };
}

export async function getEntryStatistics(database: Database, entryId: number): Promise<EntryStatistics> {
  const [modes, totals, recent] = await Promise.all([
    database.select({ mode: practiceAnswers.mode, answers: sql<number>`count(*)`, correct: sql<number>`sum(case when ${practiceAnswers.isCorrect} = 1 then 1 else 0 end)`, durationMs: sql<number>`coalesce(sum(${practiceAnswers.responseTimeMs}),0)` }).from(practiceAnswers).where(eq(practiceAnswers.entryId, entryId)).groupBy(practiceAnswers.mode),
    database.select({ answers: sql<number>`count(*)`, correct: sql<number>`sum(case when ${practiceAnswers.isCorrect} = 1 then 1 else 0 end)`, response: sql<number>`coalesce(avg(${practiceAnswers.responseTimeMs}),0)`, corrected: sql<number>`sum(case when ${practiceAnswers.manuallyCorrected} = 1 then 1 else 0 end)`, last: sql<Date | null>`max(${practiceAnswers.answeredAt})` }).from(practiceAnswers).where(eq(practiceAnswers.entryId, entryId)),
    database.select({ id: practiceAnswers.id, mode: practiceAnswers.mode, rating: practiceAnswers.rating, isCorrect: practiceAnswers.isCorrect, manuallyCorrected: practiceAnswers.manuallyCorrected, responseTimeMs: practiceAnswers.responseTimeMs, answeredAt: practiceAnswers.answeredAt }).from(practiceAnswers).where(eq(practiceAnswers.entryId, entryId)).orderBy(desc(practiceAnswers.answeredAt)).limit(8),
  ]); const total = totals[0]; return { answers: total?.answers ?? 0, correct: total?.correct ?? 0, accuracy: accuracy(total?.correct ?? 0, total?.answers ?? 0), averageResponseMs: total?.answers ? Math.round(total.response) : null, lastPracticedAt: total?.last ?? null, corrected: total?.corrected ?? 0, modes: modeRows(modes), recent };
}
