import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useAppDialog } from '../../src/components/AppDialog';
import { PaperScreen } from '../../src/components/PaperScreen';
import { IconButton, Pill } from '../../src/components/ui';
import { useDatabase } from '../../src/db/DatabaseProvider';
import { DeckSummary, listDecks } from '../../src/features/decks/deck.repository';
import { getLanguage } from '../../src/features/decks/languages';
import { useAccessibility } from '../../src/features/accessibility/AccessibilityProvider';
import { starterDecks } from '../../src/features/starter-decks/catalog';
import { copyStarterEntries, starterEntryKey } from '../../src/features/starter-decks/starter-deck.repository';
import { useTheme } from '../../src/theme/ThemeProvider';
import { radius, ThemeColors } from '../../src/theme/tokens';
import type { LingologDeckFile } from '../../src/features/transfer/deck-transfer';
import { backOrReplace } from '../../src/navigation/back';

type EntryType = 'all' | 'word' | 'phrase' | 'sentence';
type CatalogEntry = LingologDeckFile['deck']['entries'][number];
const typeLabels = { word: 'Kata', phrase: 'Frasa', sentence: 'Kalimat' } as const;

export default function StarterDeckDetailScreen() {
  const database = useDatabase(); const { colors } = useTheme(); const styles = createStyles(colors); const { showDialog } = useAppDialog(); const { announce, reduceMotion } = useAccessibility();
  const { id } = useLocalSearchParams<{ id: string }>(); const starter = starterDecks.find((item) => item.id === id);
  const [search, setSearch] = useState(''); const [type, setType] = useState<EntryType>('all'); const [destinations, setDestinations] = useState<DeckSummary[]>([]); const [selected, setSelected] = useState(new Set<string>());
  const [destinationOpen, setDestinationOpen] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  const compatible = useMemo(() => destinations.filter((deck) => starter && !deck.isArchived && deck.sourceLanguage === starter.file.deck.sourceLanguage && deck.targetLanguage === starter.file.deck.targetLanguage), [destinations, starter]);
  const filtered = useMemo(() => { if (!starter) return []; const query = search.trim().toLocaleLowerCase(); return starter.file.deck.entries.filter((entry) => (type === 'all' || entry.type === type) && (!query || `${entry.sourceText} ${entry.translatedText} ${entry.tags.join(' ')}`.toLocaleLowerCase().includes(query))); }, [search, starter, type]);
  const chosenEntries = useMemo(() => starter?.file.deck.entries.filter((entry) => selected.has(starterEntryKey(entry))) ?? [], [selected, starter]);
  const load = useCallback(async () => { try { setDestinations(await listDecks(database, false)); } catch (cause) { console.error(cause); } finally { setLoading(false); } }, [database]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  function toggle(entry: CatalogEntry) { const key = starterEntryKey(entry); setSelected((current) => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; }); }
  async function addTo(destination: DeckSummary) { if (!starter || !chosenEntries.length || saving) return; try { setSaving(true); const result = await copyStarterEntries(database, starter, chosenEntries, destination.id); setDestinationOpen(false); setSelected(new Set()); announce(`${result.added} materi ditambahkan ke ${destination.name}`); showDialog({ title: result.added ? 'Materi ditambahkan' : 'Materi sudah ada', message: result.added ? `${result.added} materi masuk ke “${destination.name}” pada tanggal hari ini.${result.skipped ? ` ${result.skipped} materi yang sudah ada dilewati.` : ''}` : `Semua materi pilihan sudah tersimpan di “${destination.name}”.`, icon: result.added ? 'checkmark-circle-outline' : 'copy-outline', actions: [{ label: 'Buka deck tujuan', tone: 'primary', onPress: () => router.push(`/decks/${destination.id}`) }, { label: 'Pilih materi lagi', tone: 'neutral' }] }); await load(); } catch (cause) { console.error(cause); showDialog({ title: 'Materi belum dapat ditambahkan', message: 'Deck tujuan tidak berubah. Coba lagi tanpa menutup aplikasi.', icon: 'alert-circle-outline' }); } finally { setSaving(false); } }
  if (!starter) return <PaperScreen><View style={styles.state}><Ionicons name="book-outline" size={32} color={colors.inkMuted} /><Text style={styles.stateTitle}>Deck tidak ditemukan</Text><Pressable onPress={() => backOrReplace('/starter-decks')} style={styles.secondaryButton}><Text style={styles.secondaryText}>Kembali ke koleksi</Text></Pressable></View></PaperScreen>;
  const source = getLanguage(starter.file.deck.sourceLanguage); const target = getLanguage(starter.file.deck.targetLanguage);
  return <View style={styles.root}><PaperScreen keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>
    <View style={styles.top}><IconButton name="arrow-back" label="Kembali" onPress={() => backOrReplace('/starter-decks')} /><View style={styles.heading}><Text style={styles.note}>Pilih materi</Text><Text numberOfLines={2} style={styles.title}>{starter.file.deck.name}</Text><Text style={styles.pair}>{source.name} → {target.name}</Text></View></View>
    <View style={styles.guide}><Ionicons name="checkmark-circle-outline" size={23} color={colors.primary} /><View style={styles.grow}><Text style={styles.guideTitle}>Tekan materi yang ingin dipelajari</Text><Text style={styles.guideText}>Pilih satu atau beberapa materi. Deck tujuan baru dipilih saat kamu menekan Tambahkan.</Text></View></View>
    <View style={styles.search}><Ionicons name="search-outline" size={19} color={colors.inkMuted} /><TextInput accessibilityLabel="Cari materi dalam deck" autoCapitalize="none" value={search} onChangeText={setSearch} placeholder="Cari materi atau terjemahan" placeholderTextColor={colors.inkFaint} style={styles.input} />{search ? <Pressable accessibilityLabel="Hapus pencarian" hitSlop={10} onPress={() => setSearch('')}><Ionicons name="close-circle" size={20} color={colors.inkMuted} /></Pressable> : null}</View>
    <View style={styles.filters}>{(['all', 'word', 'phrase', 'sentence'] as const).map((value) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: type === value }} key={value} onPress={() => setType(value)} style={[styles.filter, type === value && styles.filterActive]}><Text style={[styles.filterText, type === value && styles.filterTextActive]}>{value === 'all' ? 'Semua' : typeLabels[value]}</Text></Pressable>)}</View>
    <View style={styles.resultHeader}><Text style={styles.resultTitle}>Isi deck</Text><Text style={styles.resultCount}>{selected.size ? `${selected.size} dipilih · ` : ''}{filtered.length} dari {starter.file.deck.entries.length}</Text></View>
    {!filtered.length ? <View style={styles.state}><Ionicons name="search-outline" size={30} color={colors.inkMuted} /><Text style={styles.stateTitle}>Materi tidak ditemukan</Text><Text style={styles.stateText}>Coba kata lain atau pilih Semua.</Text></View> : filtered.map((entry, index) => { const key = starterEntryKey(entry); const checked = selected.has(key); return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked }} accessibilityLabel={`${entry.sourceText}, ${entry.translatedText}`} key={`${key}-${index}`} onPress={() => toggle(entry)} style={({ pressed }) => [styles.entry, checked && styles.entrySelected, pressed && styles.pressed]}><View style={styles.entryCopy}><View style={styles.entryMeta}><Pill tone="plain">{typeLabels[entry.type]}</Pill>{entry.tags.slice(0, 1).map((tag) => <Pill key={tag}>{tag}</Pill>)}</View><Text selectable style={styles.source}>{entry.sourceText}</Text><Text selectable style={styles.translation}>{entry.translatedText}</Text>{entry.exampleText ? <Text style={styles.example}>{entry.exampleText}</Text> : null}</View><View style={[styles.check, checked && styles.checkSelected]}><Ionicons name={checked ? 'checkmark' : 'add'} size={21} color={checked ? colors.primaryInk : colors.primary} /></View></Pressable>; })}
  </PaperScreen>
  {selected.size ? <View style={styles.selectionBar}><View><Text style={styles.selectionCount}>{selected.size} materi dipilih</Text><Text style={styles.selectionHint}>Pilih deck tujuan pada langkah berikutnya</Text></View><Pressable accessibilityRole="button" onPress={() => setDestinationOpen(true)} style={styles.addButton}><Text style={styles.addText}>Tambahkan</Text><Ionicons name="arrow-forward" size={18} color={colors.primaryInk} /></Pressable></View> : null}
  <Modal visible={destinationOpen} transparent animationType={reduceMotion ? 'none' : 'slide'} accessibilityViewIsModal onRequestClose={() => !saving && setDestinationOpen(false)}><Pressable style={styles.scrim} onPress={() => !saving && setDestinationOpen(false)} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.sheetHeader}><View style={styles.grow}><Text style={styles.sheetTitle}>Pilih deck tujuan</Text><Text style={styles.sheetText}>{selected.size} materi · {source.short} → {target.short}</Text></View><IconButton name="close" label="Tutup" disabled={saving} onPress={() => setDestinationOpen(false)} /></View>{loading ? <View style={styles.sheetState}><ActivityIndicator color={colors.primary} /></View> : compatible.length ? compatible.map((deck) => <Pressable accessibilityRole="button" accessibilityState={{ disabled: saving }} disabled={saving} key={deck.id} onPress={() => void addTo(deck)} style={({ pressed }) => [styles.destination, pressed && styles.pressed]}><View style={[styles.dot, { backgroundColor: deck.color ?? colors.primary }]} /><View style={styles.grow}><Text style={styles.destinationName}>{deck.name}</Text><Text style={styles.destinationMeta}>{deck.entryCount} entri</Text></View>{saving ? <ActivityIndicator size="small" color={colors.primary} /> : <Ionicons name="chevron-forward" size={19} color={colors.inkMuted} />}</Pressable>) : <View style={styles.missing}><Ionicons name="albums-outline" size={28} color={colors.primary} /><Text style={styles.missingTitle}>Belum ada deck yang cocok</Text><Text style={styles.missingText}>Buat deck {source.name} → {target.name}, lalu pilihanmu tetap dapat dilanjutkan.</Text><Pressable onPress={() => { setDestinationOpen(false); router.push({ pathname: '/decks/new', params: { sourceLanguage: source.code, targetLanguage: target.code } }); }} style={styles.createButton}><Text style={styles.createText}>Buat deck tujuan</Text></Pressable></View>}</View></Modal>
  </View>;
}

const createStyles = (colors: ThemeColors) => StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.paper }, content: { paddingBottom: 112 }, top: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 17 }, heading: { flex: 1, paddingTop: 3 }, note: { color: colors.highlight, fontSize: 12, fontWeight: '900' }, title: { color: colors.ink, fontSize: 23, lineHeight: 28, fontWeight: '900', marginTop: 2 }, pair: { color: colors.primary, fontSize: 11, fontWeight: '800', marginTop: 4 }, grow: { flex: 1, minWidth: 0 },
  guide: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, padding: 14, borderRadius: radius.md, backgroundColor: colors.primarySoft, marginBottom: 18 }, guideTitle: { color: colors.ink, fontSize: 14, fontWeight: '900' }, guideText: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, marginTop: 3 }, search: { minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 9, paddingHorizontal: 13, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, input: { flex: 1, minHeight: 46, color: colors.ink, fontSize: 13 }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10 }, filter: { minHeight: 36, justifyContent: 'center', paddingHorizontal: 12, borderRadius: 18, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, filterActive: { borderColor: colors.primary, backgroundColor: colors.primary }, filterText: { color: colors.inkMuted, fontSize: 11, fontWeight: '800' }, filterTextActive: { color: colors.primaryInk },
  resultHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: 22, paddingBottom: 7 }, resultTitle: { color: colors.ink, fontSize: 17, fontWeight: '900' }, resultCount: { color: colors.inkMuted, fontSize: 11, fontWeight: '700' }, entry: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 15, paddingHorizontal: 4, borderBottomWidth: 1, borderBottomColor: colors.rule }, entrySelected: { backgroundColor: colors.primarySoft, borderRadius: radius.sm, borderBottomColor: colors.primary }, entryCopy: { flex: 1, minWidth: 0 }, entryMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginBottom: 7 }, source: { color: colors.ink, fontSize: 16, lineHeight: 22, fontWeight: '900' }, translation: { color: colors.inkMuted, fontSize: 13, lineHeight: 19, marginTop: 3 }, example: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, fontStyle: 'italic', marginTop: 5 }, check: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.primary, backgroundColor: colors.paperRaised }, checkSelected: { backgroundColor: colors.primary }, pressed: { opacity: 0.65 },
  selectionBar: { position: 'absolute', left: 14, right: 14, bottom: 14, minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, paddingLeft: 16, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised, shadowColor: colors.shadow, shadowOpacity: 0.18, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 7 }, selectionCount: { color: colors.ink, fontSize: 13, fontWeight: '900' }, selectionHint: { color: colors.inkMuted, fontSize: 9, marginTop: 3 }, addButton: { marginLeft: 'auto', minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, borderRadius: radius.md, backgroundColor: colors.primary }, addText: { color: colors.primaryInk, fontSize: 12, fontWeight: '900' },
  scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(7,10,8,0.58)' }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, maxHeight: '78%', padding: 20, paddingBottom: 35, borderTopLeftRadius: 27, borderTopRightRadius: 27, backgroundColor: colors.paper, borderTopWidth: 1, borderColor: colors.rule }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 3, backgroundColor: colors.rule, marginBottom: 16 }, sheetHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: colors.rule }, sheetTitle: { color: colors.ink, fontSize: 19, fontWeight: '900' }, sheetText: { color: colors.inkMuted, fontSize: 11, marginTop: 3 }, sheetState: { minHeight: 160, alignItems: 'center', justifyContent: 'center' }, destination: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: colors.rule }, dot: { width: 13, height: 13, borderRadius: 7 }, destinationName: { color: colors.ink, fontSize: 14, fontWeight: '900' }, destinationMeta: { color: colors.inkMuted, fontSize: 10, marginTop: 3 },
  missing: { minHeight: 220, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 }, missingTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', marginTop: 11 }, missingText: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 5 }, createButton: { minHeight: 43, justifyContent: 'center', paddingHorizontal: 14, marginTop: 15, borderRadius: radius.md, backgroundColor: colors.primary }, createText: { color: colors.primaryInk, fontSize: 12, fontWeight: '900' }, state: { minHeight: 230, alignItems: 'center', justifyContent: 'center', padding: 28 }, stateTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', marginTop: 10 }, stateText: { color: colors.inkMuted, fontSize: 12, marginTop: 5 }, secondaryButton: { marginTop: 16, paddingHorizontal: 14, paddingVertical: 10, borderRadius: radius.md, backgroundColor: colors.primarySoft }, secondaryText: { color: colors.primary, fontWeight: '900' },
});
