import { useState } from 'react';
import { BackHandler, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useFocusEffect } from '@react-navigation/native';
import { useCallback } from 'react';
import { PaperTexture } from '../src/components/PaperScreen';
import { useOnboarding } from '../src/features/onboarding/OnboardingProvider';
import { useAccessibility } from '../src/features/accessibility/AccessibilityProvider';
import { useTheme } from '../src/theme/ThemeProvider';
import { radius, ThemeColors } from '../src/theme/tokens';

const steps: { note: string; title: string; body: string; icon: keyof typeof Ionicons.glyphMap; bullets: [keyof typeof Ionicons.glyphMap, string][] }[] = [
  { note: 'Selamat datang', title: 'Catatan bahasa yang tetap milikmu.', body: 'Lingolog menyimpan deck, latihan, dan progres di perangkat. Fitur inti tetap berjalan tanpa akun dan tanpa internet.', icon: 'shield-checkmark-outline', bullets: [['cloud-offline-outline','Belajar secara offline'],['phone-portrait-outline','Data utama tersimpan lokal'],['lock-closed-outline','Tidak ada akun atau pelacakan cloud']] },
  { note: 'Langkah pertama', title: 'Mulai dari deck yang pas.', body: 'Deck mengikat satu bahasa yang dipelajari dengan satu bahasa arti. Pilih materi bawaan atau buat koleksimu sendiri.', icon: 'library-outline', bullets: [['sparkles-outline','Deck siap pakai: Jerman dan Inggris'],['add-circle-outline','Buat deck untuk topikmu sendiri'],['swap-horizontal-outline','Pasangan bahasa dikunci setelah berisi materi']] },
  { note: 'Isi catatanmu', title: 'Simpan kata sampai kalimat.', body: 'Tambahkan terjemahan, contoh, catatan, favorit, dan tag. Tombol suara membacakan materi dengan voice perangkat yang sesuai bahasa deck.', icon: 'create-outline', bullets: [['text-outline','Kata, frasa, dan kalimat'],['volume-high-outline','TTS mengikuti bahasa deck'],['pricetag-outline','Tag membantu menemukan materi lagi']] },
  { note: 'Berlatih bebas', title: 'Dengar, ingat, lalu lihat buktinya.', body: 'Kartu flash dan Dikte memakai entri dari deck-mu. Hasil latihan membentuk statistik dan mastery tanpa memaksa jadwal review.', icon: 'shapes-outline', bullets: [['copy-outline','Kartu flash dengan empat rating'],['mic-outline','Dikte audio atau arti ke tulisan'],['analytics-outline','Mastery manual atau dari bukti game']] },
  { note: 'Data & berbagi', title: 'Ekspor deck bukan backup.', body: 'Ekspor deck aman untuk berbagi materi. Backup penuh bersifat privat dan membawa seluruh progres serta preferensi untuk pemulihan perangkat.', icon: 'archive-outline', bullets: [['share-outline','Ekspor: materi dan tag saja'],['server-outline','Backup: seluruh data dan progres'],['warning-outline','Restore mengganti semua data setelah preview']] },
];
export default function OnboardingScreen() {
  const { colors } = useTheme(); const { announce } = useAccessibility(); const styles = createStyles(colors); const onboarding = useOnboarding(); const [index, setIndex] = useState(0); const step = steps[index];
  const move = (next: number) => { setIndex(next); announce(`Langkah ${next + 1} dari ${steps.length}. ${steps[next].title}`); };
  useFocusEffect(useCallback(() => { const subscription = BackHandler.addEventListener('hardwareBackPress', () => { if (index > 0) { move(index - 1); return true; } return true; }); return () => subscription.remove(); }, [index]));
  async function finish(destination: '/starter-decks' | '/decks/new' | '/(tabs)') { await onboarding.complete(); router.replace(destination as never); }
  return <View style={styles.screen}><PaperTexture /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.top}><Text style={styles.brand}>Lingolog</Text><Pressable accessibilityRole="button" accessibilityLabel="Lewati pengenalan" onPress={() => void finish('/(tabs)')} style={styles.skip}><Text style={styles.skipText}>Lewati</Text></Pressable></View>
    <View accessible accessibilityRole="progressbar" accessibilityLabel="Progres pengenalan" accessibilityValue={{ min: 1, max: steps.length, now: index + 1, text: `Langkah ${index + 1} dari ${steps.length}` }} style={styles.progress}>{steps.map((_, position) => <View key={position} style={[styles.progressLine, position <= index && styles.progressActive]} />)}</View>
    <View style={styles.illustration}><View style={[styles.page, styles.pageBack]} /><View style={styles.page}><View style={styles.pageMargin} /><Ionicons name={step.icon} size={52} color={colors.primary} /><View style={styles.penLine} /><View style={[styles.penLine, { width: 65 }]} /></View></View>
    <Text style={styles.note}>{step.note}</Text><Text accessibilityRole="header" style={styles.title}>{step.title}</Text><Text style={styles.body}>{step.body}</Text>
    <View style={styles.bullets}>{step.bullets.map(([icon, label]) => <View key={label} style={styles.bullet}><View style={styles.bulletIcon}><Ionicons name={icon} size={19} color={colors.primary} /></View><Text style={styles.bulletText}>{label}</Text></View>)}</View>
    {index === steps.length - 1 ? <View style={styles.finishChoices}><Pressable accessibilityRole="button" onPress={() => void finish('/starter-decks')} style={styles.primary}><Ionicons name="sparkles-outline" size={19} color={colors.primaryInk} /><Text style={styles.primaryText}>Pilih deck siap pakai</Text></Pressable><Pressable accessibilityRole="button" onPress={() => void finish('/decks/new')} style={styles.secondary}><Ionicons name="add" size={19} color={colors.primary} /><Text style={styles.secondaryText}>Buat deck sendiri</Text></Pressable></View> : <Pressable accessibilityRole="button" onPress={() => move(index + 1)} style={styles.primary}><Text style={styles.primaryText}>Lanjut</Text><Ionicons name="arrow-forward" size={19} color={colors.primaryInk} /></Pressable>}
    {index > 0 ? <Pressable accessibilityRole="button" onPress={() => move(index - 1)} style={styles.back}><Ionicons name="arrow-back" size={17} color={colors.inkMuted} /><Text style={styles.backText}>Kembali</Text></Pressable> : null}
  </ScrollView></View>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 54, paddingBottom: 34 }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { color: colors.primary, fontSize: 20, fontWeight: '900' }, skip: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8 }, skipText: { color: colors.inkMuted, fontSize: 13, fontWeight: '800' }, progress: { flexDirection: 'row', gap: 6, marginTop: 18 }, progressLine: { flex: 1, height: 3, borderRadius: 2, backgroundColor: colors.rule }, progressActive: { backgroundColor: colors.highlight }, illustration: { height: 198, alignItems: 'center', justifyContent: 'center' }, page: { position: 'absolute', width: 138, height: 153, borderRadius: 14, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule, alignItems: 'center', justifyContent: 'center', shadowColor: colors.shadow, shadowOpacity: 0.1, shadowRadius: 12, shadowOffset: { width: 0, height: 7 }, transform: [{ rotate: '-2deg' }] }, pageBack: { backgroundColor: colors.primarySoft, transform: [{ rotate: '6deg' }, { translateX: 10 }] }, pageMargin: { position: 'absolute', left: 17, top: 0, bottom: 0, width: 1, backgroundColor: colors.highlight, opacity: 0.35 }, penLine: { height: 3, width: 78, borderRadius: 3, backgroundColor: colors.primarySoft, marginTop: 13 }, note: { color: colors.highlight, fontSize: 13, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.5 }, title: { color: colors.ink, fontSize: 29, lineHeight: 35, fontWeight: '900', letterSpacing: -0.7, marginTop: 7 }, body: { color: colors.inkMuted, fontSize: 14, lineHeight: 22, marginTop: 11 }, bullets: { gap: 9, marginTop: 22, marginBottom: 25 }, bullet: { flexDirection: 'row', alignItems: 'center', gap: 11 }, bulletIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, bulletText: { flex: 1, color: colors.ink, fontSize: 13, fontWeight: '700' }, primary: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: radius.md, backgroundColor: colors.primary, paddingHorizontal: 17 }, primaryText: { color: colors.primaryInk, fontSize: 14, fontWeight: '900' }, secondary: { minHeight: 49, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: radius.md, borderWidth: 1, borderColor: colors.primary }, secondaryText: { color: colors.primary, fontSize: 13, fontWeight: '900' }, finishChoices: { gap: 10 }, back: { alignSelf: 'center', minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, marginTop: 7 }, backText: { color: colors.inkMuted, fontSize: 12, fontWeight: '800' } });
