import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { useAppDialog } from '../src/components/AppDialog';
import { IconButton, SectionTitle } from '../src/components/ui';
import { radius, ThemeColors, ThemeMode } from '../src/theme/tokens';
import { useTheme } from '../src/theme/ThemeProvider';
import { backOrReplace } from '../src/navigation/back';
import { speechRates, useSpeech } from '../src/features/speech/SpeechProvider';
import { SpeechSettings } from '../src/features/speech/SpeechControls';
import { useHaptics } from '../src/features/settings/HapticsProvider';
import { languages } from '../src/features/decks/languages';
import { useOnboarding } from '../src/features/onboarding/OnboardingProvider';

const themes: { value: ThemeMode; label: string; detail: string; icon: keyof typeof Ionicons.glyphMap }[] = [
  { value: 'system', label: 'Sistem', detail: 'Mengikuti perangkat', icon: 'phone-portrait-outline' },
  { value: 'light', label: 'Terang', detail: 'Kertas terang', icon: 'sunny-outline' },
  { value: 'dark', label: 'Gelap', detail: 'Kertas arang', icon: 'moon-outline' },
];
export default function SettingsScreen() {
  const { colors, mode, setMode, resolvedTheme } = useTheme(); const styles = createStyles(colors); const speech = useSpeech(); const haptics = useHaptics(); const onboarding = useOnboarding(); const { showDialog } = useAppDialog(); const [speechOpen, setSpeechOpen] = useState(false);
  const rate = speechRates.find((item) => item.value === speech.rate)?.label ?? `${speech.rate}×`; const configured = Object.keys(languages.reduce<Record<string, boolean>>((result, language) => ({ ...result, [language.code]: Boolean(speech.configuredVoice(language.code)) }), {})).filter((code) => speech.configuredVoice(code)).length;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.topbar}><IconButton name="arrow-back" label="Kembali" onPress={() => backOrReplace('/')} /><View style={styles.heading}><Text style={styles.note}>Aplikasi</Text><Text style={styles.title}>Pengaturan</Text></View></View>
    <SectionTitle>Penampilan</SectionTitle><Text style={styles.intro}>Pilih suasana kertas yang nyaman. Mode Sistem berubah bersama perangkat.</Text><View accessibilityRole="radiogroup" style={styles.themeGrid}>{themes.map((item) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: mode === item.value }} key={item.value} onPress={() => setMode(item.value)} style={[styles.themeChoice, mode === item.value && styles.selected]}><Ionicons name={item.icon} size={23} color={mode === item.value ? colors.primary : colors.inkMuted} /><Text style={[styles.choiceTitle, mode === item.value && styles.selectedText]}>{item.label}</Text><Text style={styles.choiceDetail}>{item.detail}</Text>{mode === item.value ? <Ionicons name="checkmark-circle" size={18} color={colors.primary} style={styles.check} /> : null}</Pressable>)}</View><Text style={styles.current}>Saat ini tampil {resolvedTheme === 'dark' ? 'gelap' : 'terang'}.</Text>
    <SectionTitle>Suara dan voice</SectionTitle><Pressable accessibilityRole="button" onPress={() => setSpeechOpen(true)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}><Ionicons name="volume-medium-outline" size={22} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.rowTitle}>Text-to-speech</Text><Text style={styles.rowDetail}>Kecepatan {rate} · {configured ? `${configured} voice dipilih manual` : 'voice dipilih otomatis'}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.inkMuted} /></Pressable><Text style={styles.help}>Voice tetap berasal dari paket suara perangkat. Lingolog tidak mengganti bahasa secara diam-diam jika voice belum tersedia.</Text>
    <SectionTitle>Interaksi</SectionTitle><View style={styles.row}><View style={styles.rowIcon}><Ionicons name="phone-portrait-outline" size={22} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.rowTitle}>Getaran saat latihan</Text><Text style={styles.rowDetail}>Feedback ringan saat membalik, menilai, atau memeriksa jawaban.</Text></View><Switch accessibilityLabel="Aktifkan getaran saat latihan" value={haptics.enabled} onValueChange={haptics.setEnabled} trackColor={{ false: colors.rule, true: colors.primarySoft }} thumbColor={haptics.enabled ? colors.primary : colors.inkMuted} /></View>
    <SectionTitle>Bantuan</SectionTitle><Pressable accessibilityRole="button" onPress={() => showDialog({ title: 'Ulangi pengenalan Lingolog?', message: 'Pengenalan akan dibuka dari awal. Deck, progres, dan pengaturanmu tidak berubah.', icon: 'help-buoy-outline', actions: [{ label: 'Mulai pengenalan', tone: 'primary', onPress: async () => { await onboarding.restart(); router.replace('/onboarding'); } }, { label: 'Batal', tone: 'neutral' }] })} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}><Ionicons name="help-buoy-outline" size={22} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.rowTitle}>Ulangi pengenalan</Text><Text style={styles.rowDetail}>Lihat kembali cara kerja deck, latihan, ekspor, dan backup.</Text></View><Ionicons name="chevron-forward" size={19} color={colors.inkMuted} /></Pressable>
    <View style={styles.local}><Ionicons name="shield-checkmark-outline" size={21} color={colors.primary} /><View style={styles.grow}><Text style={styles.localTitle}>Preferensi tersimpan lokal</Text><Text style={styles.localText}>Tema, voice, kecepatan, dan haptic disimpan di perangkat serta ikut dalam backup penuh.</Text></View></View>
    <SpeechSettings visible={speechOpen} languages={languages} onClose={() => setSpeechOpen(false)} />
  </ScrollView>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 42 }, topbar: { flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 28 }, heading: { flex: 1 }, note: { color: colors.highlight, fontSize: 13, fontWeight: '900' }, title: { color: colors.ink, fontSize: 27, fontWeight: '900' }, intro: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: -8, marginBottom: 13 }, themeGrid: { flexDirection: 'row', gap: 8 }, themeChoice: { flex: 1, minHeight: 112, alignItems: 'center', justifyContent: 'center', padding: 10, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, selected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, choiceTitle: { color: colors.ink, fontSize: 13, fontWeight: '900', marginTop: 8 }, selectedText: { color: colors.primary }, choiceDetail: { color: colors.inkMuted, fontSize: 9, textAlign: 'center', marginTop: 3 }, check: { position: 'absolute', right: 7, top: 7 }, current: { color: colors.inkMuted, fontSize: 10, marginTop: 8 }, row: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.rule }, pressed: { opacity: 0.65 }, rowIcon: { width: 43, height: 43, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, grow: { flex: 1 }, rowTitle: { color: colors.ink, fontSize: 14, fontWeight: '900' }, rowDetail: { color: colors.inkMuted, fontSize: 11, lineHeight: 16, marginTop: 3 }, help: { color: colors.inkMuted, fontSize: 10, lineHeight: 16, marginTop: 9 }, local: { flexDirection: 'row', gap: 11, padding: 15, marginTop: 29, borderRadius: radius.md, backgroundColor: colors.primarySoft }, localTitle: { color: colors.primary, fontSize: 12, fontWeight: '900' }, localText: { color: colors.inkMuted, fontSize: 10, lineHeight: 16, marginTop: 3 } });
