import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { IconButton, Pill, ScreenHeader, SectionTitle } from '../../src/components/ui';
import { useAppDialog } from '../../src/components/AppDialog';
import { radius, ThemeColors } from '../../src/theme/tokens';
import { useTheme } from '../../src/theme/ThemeProvider';
import { useDatabase, useReopenDatabase, useSQLiteDatabase } from '../../src/db/DatabaseProvider';
import { CatalogDeckSheet } from '../../src/features/decks/CatalogDeckSheet';
import { DeckLibraryControls, DeckListFilters } from '../../src/features/decks/DeckLibraryControls';
import { DeckSummary, duplicateDeck, listCompatibleDecks, listDecks, mergeDecks, setDeckArchived } from '../../src/features/decks/deck.repository';
import { getLanguage } from '../../src/features/decks/languages';
import { pickAndImportDeck, shareDeckFile } from '../../src/features/transfer/deck-transfer.service';
import { transferErrorMessage } from '../../src/features/transfer/deck-transfer';
import { BackupSheet } from '../../src/features/backup/BackupSheet';
import { backupErrorMessage, pickBackupForRestore, restoreFullBackup, shareFullBackup } from '../../src/features/backup/backup.service';

export default function RepositoryScreen() {
  const database = useDatabase(); const sqlite = useSQLiteDatabase(); const reopenDatabase = useReopenDatabase(); const { colors } = useTheme(); const styles = createStyles(colors); const { showDialog } = useAppDialog();
  const [decks, setDecks] = useState<DeckSummary[]>([]); const [search, setSearch] = useState(''); const [filterOpen, setFilterOpen] = useState(false); const [filters, setFilters] = useState<DeckListFilters>({ sort: 'name' }); const [selected, setSelected] = useState<DeckSummary>(); const [compatible, setCompatible] = useState<DeckSummary[]>([]); const [mergeMode, setMergeMode] = useState(false); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const [backupSheet, setBackupSheet] = useState(false);
  const load = useCallback(async () => { try { setError(''); setDecks(await listDecks(database)); } catch (cause) { console.error(cause); setError('Katalog lokal belum dapat dibuka.'); } finally { setLoading(false); setRefreshing(false); } }, [database]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const visibleDecks = useMemo(() => { const query = search.trim().toLocaleLowerCase(); return decks.filter((deck) => (!query || `${deck.name} ${deck.description ?? ''}`.toLocaleLowerCase().includes(query)) && (!filters.sourceLanguage || deck.sourceLanguage === filters.sourceLanguage) && (!filters.targetLanguage || deck.targetLanguage === filters.targetLanguage) && (!filters.status || (filters.status === 'archived' ? deck.isArchived : !deck.isArchived)) && (!filters.content || (filters.content === 'empty' ? deck.entryCount === 0 : deck.entryCount > 0))).sort((a, b) => filters.sort === 'newest' ? b.createdAt.getTime() - a.createdAt.getTime() : filters.sort === 'entries' ? b.entryCount - a.entryCount : filters.sort === 'mastered' ? b.masteredCount - a.masteredCount : a.name.localeCompare(b.name)); }, [decks, search, filters]);
  async function openActions(deck: DeckSummary) { setSelected(deck); setMergeMode(false); try { setCompatible(await listCompatibleDecks(database, deck.id)); } catch (cause) { console.error(cause); setCompatible([]); } }
  function closeSheet() { setSelected(undefined); setCompatible([]); setMergeMode(false); }
  async function archive() { if (!selected) return; const next = !selected.isArchived; closeSheet(); await setDeckArchived(database, selected.id, next); await load(); }
  function duplicate() { if (!selected) return; const source = selected; closeSheet(); showDialog({ title: `Duplikasi “${source.name}”?`, message: 'Semua entri, contoh, catatan, favorit, dan tag disalin. Statistik latihan serta mastery dimulai dari awal.', icon: 'copy-outline', actions: [{ label: 'Buat salinan', tone: 'primary', onPress: async () => { const copy = await duplicateDeck(database, source.id); await load(); router.push(`/decks/${copy.id}`); } }, { label: 'Batal', tone: 'neutral' }] }); }
  async function createBackup() { setBackupSheet(false); try { await shareFullBackup(sqlite); } catch (cause) { console.error(cause); showDialog({ title: 'Backup belum dapat dibuat', message: backupErrorMessage(cause), icon: 'archive-outline' }); } }
  async function chooseRestore() { setBackupSheet(false); try { const preview = await pickBackupForRestore(); if (!preview) return; showDialog({ title: 'Ganti seluruh data Lingolog?', message: `Backup “${preview.originalName}” berisi ${preview.decks} deck, ${preview.entries} entri, ${preview.sessions} sesi, dan ${preview.answers} jawaban. Semua data Lingolog saat ini akan diganti. Tindakan ini tidak dapat dibatalkan.`, icon: 'warning-outline', dismissible: false, actions: [{ label: 'Pulihkan backup', tone: 'danger', onPress: async () => { await restoreFullBackup(sqlite, preview, reopenDatabase); showDialog({ title: 'Backup berhasil dipulihkan', message: `${preview.decks} deck dan seluruh histori terkait sudah menggantikan data sebelumnya.`, icon: 'checkmark-circle-outline' }); } }, { label: 'Batalkan', tone: 'neutral' }] }); } catch (cause) { console.error(cause); showDialog({ title: 'Backup belum dapat dipulihkan', message: backupErrorMessage(cause), icon: 'alert-circle-outline' }); } }
  async function importDeck() { try { const result = await pickAndImportDeck(database); if (!result) return; await load(); showDialog({ title: 'Deck berhasil diimpor', message: `“${result.deck.name}” ditambahkan dengan ${result.source.deck.entries.length} entri. Statistik pribadi tidak termasuk dalam file.`, icon: 'checkmark-circle-outline', actions: [{ label: 'Buka deck', tone: 'primary', onPress: () => router.push(`/decks/${result.deck.id}`) }, { label: 'Tetap di Katalog', tone: 'neutral' }] }); } catch (cause) { console.error(cause); showDialog({ title: 'Deck belum dapat diimpor', message: transferErrorMessage(cause), icon: 'document-text-outline' }); } }
  async function exportDeck() { if (!selected) return; const deck = selected; closeSheet(); try { await shareDeckFile(database, deck.id); } catch (cause) { console.error(cause); showDialog({ title: 'Deck belum dapat dibagikan', message: cause instanceof Error && cause.message === 'SHARING_UNAVAILABLE' ? 'Perangkat ini tidak menyediakan lembar berbagi file.' : transferErrorMessage(cause), icon: 'share-outline' }); } }
  function merge(destination: DeckSummary) { if (!selected) return; const source = selected; closeSheet(); showDialog({ title: `Gabungkan ke “${destination.name}”?`, message: `${source.entryCount} entri dari “${source.name}” akan dipindahkan. Statistik, mastery, tag, dan histori tetap tersimpan. Deck sumber kemudian dihapus.`, icon: 'git-merge-outline', dismissible: false, actions: [{ label: 'Gabungkan deck', tone: 'danger', onPress: async () => { await mergeDecks(database, source.id, destination.id); await load(); router.push(`/decks/${destination.id}`); } }, { label: 'Batalkan', tone: 'neutral' }] }); }
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} tintColor={colors.primary} />}>
    <ScreenHeader note="Katalog lokal" title="Semua koleksi di perangkatmu." action={<View style={styles.headerActions}><IconButton name="server-outline" label="Backup dan restore seluruh data" onPress={() => setBackupSheet(true)} /><IconButton name="download-outline" label="Impor deck dari file" onPress={() => void importDeck()} /><IconButton name="add" label="Buat deck baru" onPress={() => router.push('/decks/new')} /></View>} />
    <View style={styles.offline}><View style={styles.offlineIcon}><Ionicons name="phone-portrait-outline" size={23} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.offlineTitle}>Tersimpan di perangkat</Text><Text style={styles.meta}>Tanpa akun, cloud, atau katalog daring.</Text></View><Pill>Offline</Pill></View>
    <DeckLibraryControls search={search} onSearchChange={setSearch} filters={filters} onFiltersChange={setFilters} open={filterOpen} onOpen={() => setFilterOpen(true)} onClose={() => setFilterOpen(false)} includeStatus />
    <SectionTitle aside={!loading && !error ? `${visibleDecks.length} dari ${decks.length} deck` : undefined}>Katalog</SectionTitle>
    {loading ? <View style={styles.state}><ActivityIndicator color={colors.primary} /><Text style={styles.stateText}>Membuka koleksi…</Text></View> : error ? <View style={styles.state}><Ionicons name="alert-circle-outline" size={30} color={colors.danger} /><Text style={styles.stateTitle}>{error}</Text><Pressable onPress={() => void load()} style={styles.retry}><Text style={styles.retryText}>Coba lagi</Text></Pressable></View> : decks.length === 0 ? <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name="albums-outline" size={29} color={colors.primary} /></View><Text style={styles.stateTitle}>Katalog masih kosong</Text><Text style={styles.stateText}>Tambahkan materi bawaan atau buat deck sendiri untuk memulai koleksi lokal.</Text><Pressable onPress={() => router.push('/starter-decks')} style={styles.primaryButton}><Text style={styles.primaryText}>Pilih deck siap pakai</Text></Pressable><Pressable onPress={() => router.push('/decks/new')} style={styles.secondaryButton}><Text style={styles.secondaryText}>Buat deck sendiri</Text></Pressable></View> : visibleDecks.length === 0 ? <View style={styles.empty}><Ionicons name="search-outline" size={29} color={colors.inkMuted} /><Text style={styles.stateTitle}>Deck tidak ditemukan</Text><Text style={styles.stateText}>Coba kata lain atau reset seluruh filter.</Text><Pressable onPress={() => { setSearch(''); setFilters({ sort: 'name' }); }} style={styles.primaryButton}><Text style={styles.primaryText}>Reset pencarian</Text></Pressable></View> : visibleDecks.map((deck) => <Pressable accessibilityRole="button" accessibilityLabel={`Kelola ${deck.name}`} key={deck.id} onPress={() => void openActions(deck)} style={({ pressed }) => [styles.catalog, pressed && styles.pressed]}><View style={[styles.book, { backgroundColor: deck.color ?? colors.primary }]}><View style={styles.bookFold} /><Ionicons name="book-outline" size={24} color="#FFFFFF" /></View><View style={styles.grow}><View style={styles.nameRow}><Text numberOfLines={1} style={styles.name}>{deck.name}</Text>{deck.isArchived ? <Pill tone="plain">Arsip</Pill> : null}</View><Text style={styles.meta}>{getLanguage(deck.sourceLanguage).name} → {getLanguage(deck.targetLanguage).name}</Text><Text style={styles.count}>{deck.entryCount} entri · {deck.masteredCount} dikuasai</Text></View><Ionicons name="ellipsis-horizontal-circle-outline" size={24} color={colors.inkMuted} /></Pressable>)}
    <View style={styles.nextStage}><Ionicons name="shield-checkmark-outline" size={20} color={colors.primary} /><Text style={styles.nextText}>File deck hanya berisi materi dan tag. Statistik latihan, mastery, favorit, serta histori pribadi tidak pernah ikut dibagikan.</Text></View>
    <BackupSheet visible={backupSheet} onClose={() => setBackupSheet(false)} onBackup={() => void createBackup()} onRestore={() => void chooseRestore()} />
    <CatalogDeckSheet deck={selected} compatible={compatible} mergeMode={mergeMode} onMergeMode={setMergeMode} onClose={closeSheet} onOpen={() => { const id = selected?.id; closeSheet(); if (id) router.push(`/decks/${id}`); }} onEdit={() => { const id = selected?.id; closeSheet(); if (id) router.push(`/decks/${id}/edit`); }} onArchive={() => void archive()} onDuplicate={duplicate} onExport={() => void exportDeck()} onMerge={merge} />
  </ScrollView>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { paddingTop: 62, paddingHorizontal: 20, paddingBottom: 36 }, headerActions: { flexDirection: 'row', gap: 7 }, grow: { flex: 1, minWidth: 0 }, offline: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 15, borderRadius: radius.md, backgroundColor: colors.primarySoft, marginBottom: 27 }, offlineIcon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperRaised }, offlineTitle: { color: colors.primary, fontWeight: '900', fontSize: 14 }, meta: { color: colors.inkMuted, fontSize: 11, lineHeight: 16, marginTop: 3 }, catalog: { flexDirection: 'row', gap: 13, alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.rule }, pressed: { opacity: 0.66 }, book: { width: 50, height: 61, borderRadius: 9, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' }, bookFold: { position: 'absolute', left: 7, top: 0, bottom: 0, width: 1, backgroundColor: 'rgba(255,255,255,0.38)' }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, name: { flexShrink: 1, fontSize: 16, color: colors.ink, fontWeight: '900' }, count: { color: colors.primary, fontSize: 11, fontWeight: '800', marginTop: 6 }, state: { minHeight: 230, alignItems: 'center', justifyContent: 'center', gap: 10 }, stateTitle: { color: colors.ink, fontSize: 16, fontWeight: '900', textAlign: 'center' }, stateText: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, textAlign: 'center' }, retry: { marginTop: 4, paddingHorizontal: 16, paddingVertical: 10, borderRadius: radius.md, backgroundColor: colors.primary }, retryText: { color: colors.primaryInk, fontWeight: '900' }, empty: { minHeight: 250, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 30 }, emptyIcon: { width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft, marginBottom: 13 }, primaryButton: { marginTop: 18, minHeight: 44, justifyContent: 'center', paddingHorizontal: 17, borderRadius: radius.md, backgroundColor: colors.primary }, primaryText: { color: colors.primaryInk, fontSize: 12, fontWeight: '900' }, secondaryButton: { minHeight: 42, justifyContent: 'center', paddingHorizontal: 14 }, secondaryText: { color: colors.primary, fontSize: 12, fontWeight: '900' }, nextStage: { flexDirection: 'row', gap: 10, marginTop: 27, padding: 15, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, nextText: { flex: 1, color: colors.inkMuted, fontSize: 11, lineHeight: 17 } });
