import { createContext, PropsWithChildren, useCallback, useContext, useMemo, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../theme/ThemeProvider';
import { useAccessibility } from '../features/accessibility/AccessibilityProvider';
import { radius, ThemeColors } from '../theme/tokens';

export type DialogAction = { label: string; tone?: 'primary' | 'danger' | 'neutral'; onPress?: () => void | Promise<void> };
type DialogOptions = { title: string; message?: string; icon?: keyof typeof Ionicons.glyphMap; actions?: DialogAction[]; dismissible?: boolean };
type DialogContextValue = { showDialog: (options: DialogOptions) => void; hideDialog: () => void };
const DialogContext = createContext<DialogContextValue | null>(null);

export function AppDialogProvider({ children }: PropsWithChildren) {
  const { colors } = useTheme(); const { reduceMotion } = useAccessibility(); const styles = createStyles(colors); const [dialog, setDialog] = useState<DialogOptions | null>(null); const [busy, setBusy] = useState(false);
  const hideDialog = useCallback(() => { if (!busy) setDialog(null); }, [busy]);
  const showDialog = useCallback((options: DialogOptions) => setDialog(options), []);
  const value = useMemo(() => ({ showDialog, hideDialog }), [showDialog, hideDialog]);
  async function act(action: DialogAction) { setDialog(null); if (!action.onPress) return; try { setBusy(true); await action.onPress(); } catch (cause) { console.error(cause); setDialog({ title: 'Tindakan belum berhasil', message: 'Coba lagi tanpa menutup aplikasi.', icon: 'alert-circle-outline' }); } finally { setBusy(false); } }
  const actions = dialog?.actions?.length ? dialog.actions : [{ label: 'Tutup', tone: 'primary' as const }];
  return <DialogContext.Provider value={value}>{children}<Modal visible={Boolean(dialog)} transparent animationType={reduceMotion ? "none" : "fade"} statusBarTranslucent accessibilityViewIsModal onRequestClose={dialog?.dismissible === false ? undefined : hideDialog}><Pressable accessibilityLabel="Tutup dialog" style={styles.scrim} onPress={dialog?.dismissible === false ? undefined : hideDialog}><Pressable accessibilityRole="alert" onPress={() => {}} style={styles.card}><View style={styles.pin}><View style={styles.pinCenter} /></View><View style={styles.icon}><Ionicons name={dialog?.icon ?? 'information-circle-outline'} size={27} color={dialog?.actions?.some((action) => action.tone === 'danger') ? colors.danger : colors.primary} /></View><Text style={styles.title}>{dialog?.title}</Text>{dialog?.message ? <Text style={styles.message}>{dialog.message}</Text> : null}<View style={styles.actions}>{actions.map((action, index) => <Pressable accessibilityRole="button" disabled={busy} key={`${action.label}-${index}`} onPress={() => void act(action)} style={({ pressed }) => [styles.button, action.tone === 'primary' && styles.primary, action.tone === 'danger' && styles.danger, pressed && { opacity: 0.72 }]}>{busy && action.onPress ? <ActivityIndicator size="small" color={action.tone === 'neutral' || !action.tone ? colors.ink : colors.primaryInk} /> : <Text style={[styles.buttonText, action.tone === 'primary' && styles.primaryText, action.tone === 'danger' && styles.dangerText]}>{action.label}</Text>}</Pressable>)}</View></Pressable></Pressable></Modal></DialogContext.Provider>;
}
export function useAppDialog() { const value = useContext(DialogContext); if (!value) throw new Error('useAppDialog must be used inside AppDialogProvider'); return value; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  scrim: { flex: 1, justifyContent: 'center', padding: 24, backgroundColor: 'rgba(7, 10, 8, 0.62)' }, card: { width: '100%', maxWidth: 430, alignSelf: 'center', padding: 22, borderRadius: radius.lg, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule, shadowColor: colors.shadow, shadowOpacity: 0.22, shadowRadius: 25, shadowOffset: { width: 0, height: 12 }, elevation: 12 }, pin: { position: 'absolute', top: 10, right: 14, width: 13, height: 13, borderRadius: 7, backgroundColor: colors.highlightSoft, alignItems: 'center', justifyContent: 'center' }, pinCenter: { width: 5, height: 5, borderRadius: 3, backgroundColor: colors.highlight }, icon: { width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper, marginBottom: 14 }, title: { color: colors.ink, fontSize: 20, lineHeight: 26, fontWeight: '900' }, message: { color: colors.inkMuted, fontSize: 13, lineHeight: 20, marginTop: 7 }, actions: { gap: 8, marginTop: 20 }, button: { minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paper }, primary: { backgroundColor: colors.primary, borderColor: colors.primary }, danger: { backgroundColor: colors.danger, borderColor: colors.danger }, buttonText: { color: colors.ink, fontSize: 13, fontWeight: '900' }, primaryText: { color: colors.primaryInk }, dangerText: { color: colors.primaryInk },
});
