import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { IconButton, SectionTitle } from '../../../src/components/ui';
import { useDatabase } from '../../../src/db/DatabaseProvider';
import { DeckStatistics, getDeckStatistics } from '../../../src/features/statistics/statistics.repository';
import { ActivityBars, EmptyStatistics, MasteryBars, Metric, ModeBreakdown } from '../../../src/features/statistics/StatisticsViews';
import { useTheme } from '../../../src/theme/ThemeProvider';
import { radius, ThemeColors } from '../../../src/theme/tokens';
export default function DeckStatisticsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const deckId = Number(id); const database = useDatabase(); const { colors } = useTheme(); const styles = createStyles(colors); const [data, setData] = useState<DeckStatistics>(); const [error, setError] = useState(''); const load = useCallback(async () => { try { setError(''); const result = await getDeckStatistics(database, deckId); if (!result) throw Error('NOT_FOUND'); setData(result); } catch (cause) { console.error(cause); setError('Statistik deck belum dapat dibuka.'); } }, [database, deckId]); useFocusEffect(useCallback(() => { void load(); }, [load]));
return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><View style={styles.top}><IconButton name="arrow-back" label="Kembali" onPress={() => router.back()} /><View style={styles.heading}><Text style={styles.note}>Statistik deck</Text><Text numberOfLines={1} style={styles.title}>{data?.deck.name ?? 'Deck'}</Text></View><IconButton name="book-outline" label="Buka isi deck" onPress={() => router.push(`/decks/${deckId}`)} /></View>{!data && !error ? <View style={styles.state}><ActivityIndicator color={colors.primary} /></View> : error ? <View style={styles.state}><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Coba lagi</Text></Pressable></View> : data ? <><View style={styles.metrics}><Metric value={data.accuracy == null ? '—' : `${data.accuracy}%`} label="Akurasi" detail={`${data.answers} jawaban`} /><Metric value={data.entries} label="Entri" detail={`${data.favorites} favorit`} /></View>{data.answers ? <><SectionTitle>14 hari terakhir</SectionTitle><ActivityBars data={data.daily} /><SectionTitle>Menurut permainan</SectionTitle><ModeBreakdown data={data.modes} /></> : <EmptyStatistics onPractice={() => router.push({ pathname: '/practice/setup', params: { mode: 'flashcard' } })} />}<SectionTitle>Distribusi mastery</SectionTitle><MasteryBars data={data.mastery} />{data.difficult.length ? <><SectionTitle>Perlu lebih banyak latihan</SectionTitle>{data.difficult.map((entry) => <Pressable key={entry.id} onPress={() => router.push(`/decks/${deckId}/entries/${entry.id}`)} style={styles.entry}><View style={styles.grow}><Text style={styles.source}>{entry.sourceText}</Text><Text style={styles.translation}>{entry.translatedText}</Text></View><View style={styles.score}><Text style={styles.scoreValue}>{Math.round(entry.correct / entry.attempts * 100)}%</Text><Text style={styles.scoreLabel}>{entry.attempts} percobaan</Text></View><Ionicons name="chevron-forward" size={17} color={colors.inkMuted} /></Pressable>)}</> : null}</> : null}</ScrollView>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, content: { paddingHorizontal: 20, paddingTop: 56, paddingBottom: 38 }, top: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 25 }, heading: { flex: 1 }, note: { color: colors.highlight, fontSize: 12, fontWeight: '900' }, title: { color: colors.ink, fontSize: 23, fontWeight: '900' }, state: { minHeight: 300, alignItems: 'center', justifyContent: 'center', gap: 9 }, error: { color: colors.danger, fontWeight: '800' }, retry: { color: colors.primary, fontWeight: '900' }, metrics: { flexDirection: 'row', gap: 9, marginBottom: 25 }, entry: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.rule }, grow: { flex: 1 }, source: { color: colors.ink, fontSize: 14, fontWeight: '900' }, translation: { color: colors.inkMuted, fontSize: 11, marginTop: 3 }, score: { alignItems: 'flex-end' }, scoreValue: { color: colors.primary, fontSize: 15, fontWeight: '900' }, scoreLabel: { color: colors.inkMuted, fontSize: 9, marginTop: 2 } });
