import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { DeckSummary } from './deck.repository';
import { getLanguage } from './languages';
import { useTheme } from '../../theme/ThemeProvider';
import { radius, ThemeColors } from '../../theme/tokens';
import { useAccessibility } from '../accessibility/AccessibilityProvider';

export function CatalogDeckSheet({ deck, compatible, mergeMode, onMergeMode, onClose, onOpen, onEdit, onArchive, onDuplicate, onExport, onMerge }: { deck?: DeckSummary; compatible: DeckSummary[]; mergeMode: boolean; onMergeMode: (value: boolean) => void; onClose: () => void; onOpen: () => void; onEdit: () => void; onArchive: () => void; onDuplicate: () => void; onExport: () => void; onMerge: (destination: DeckSummary) => void }) {
  const { colors } = useTheme(); const { reduceMotion } = useAccessibility(); const styles = createStyles(colors);
  return <Modal visible={Boolean(deck)} transparent animationType={reduceMotion ? "none" : "slide"} accessibilityViewIsModal onRequestClose={onClose}><Pressable style={styles.scrim} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><View style={[styles.cover, { backgroundColor: deck?.color ?? colors.primary }]}><Ionicons name="book-outline" size={22} color="#FFFFFF" /></View><View style={styles.heading}><Text numberOfLines={1} style={styles.title}>{deck?.name}</Text>{deck ? <Text style={styles.meta}>{getLanguage(deck.sourceLanguage).short} → {getLanguage(deck.targetLanguage).short} · {deck.entryCount} entri</Text> : null}</View><Pressable accessibilityRole="button" accessibilityLabel="Tutup" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.ink} /></Pressable></View>
    {mergeMode ? <><View style={styles.mergeHeading}><Pressable accessibilityRole="button" accessibilityLabel="Kembali ke tindakan deck" onPress={() => onMergeMode(false)} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.ink} /></Pressable><View><Text style={styles.sectionTitle}>Gabungkan ke deck</Text><Text style={styles.note}>Entri dan statistik dipindahkan. Deck ini lalu dihapus.</Text></View></View><ScrollView style={styles.destinations}>{compatible.length ? compatible.map((item) => <Pressable key={item.id} onPress={() => onMerge(item)} style={({ pressed }) => [styles.destination, pressed && styles.pressed]}><View style={[styles.dot, { backgroundColor: item.color ?? colors.primary }]} /><View style={styles.heading}><Text style={styles.destinationName}>{item.name}</Text><Text style={styles.meta}>{item.entryCount} entri · {item.isArchived ? 'Diarsipkan' : 'Aktif'}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.inkMuted} /></Pressable>) : <View style={styles.empty}><Ionicons name="git-merge-outline" size={28} color={colors.inkMuted} /><Text style={styles.emptyTitle}>Tidak ada deck yang kompatibel</Text><Text style={styles.note}>Buat deck lain dengan pasangan bahasa yang sama terlebih dahulu.</Text></View>}</ScrollView></> : <View style={styles.actions}><Action icon="book-outline" label="Buka isi deck" onPress={onOpen} styles={styles} colors={colors} /><Action icon="create-outline" label="Ubah informasi deck" onPress={onEdit} styles={styles} colors={colors} /><Action icon="copy-outline" label="Duplikasi tanpa statistik" onPress={onDuplicate} styles={styles} colors={colors} /><Action icon="share-outline" label="Ekspor dan bagikan deck" onPress={onExport} styles={styles} colors={colors} /><Action icon="git-merge-outline" label="Gabungkan ke deck lain" onPress={() => onMergeMode(true)} styles={styles} colors={colors} disabled={!compatible.length} /><Action icon={deck?.isArchived ? 'archive-outline' : 'archive'} label={deck?.isArchived ? 'Pulihkan dari arsip' : 'Arsipkan deck'} onPress={onArchive} styles={styles} colors={colors} /></View>}
  </View></Modal>;
}
function Action({ icon, label, onPress, disabled, styles, colors }: { icon: keyof typeof Ionicons.glyphMap; label: string; onPress: () => void; disabled?: boolean; styles: ReturnType<typeof createStyles>; colors: ThemeColors }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.action, disabled && styles.disabled, pressed && styles.pressed]}><View style={styles.actionIcon}><Ionicons name={icon} size={21} color={colors.primary} /></View><Text style={styles.actionLabel}>{label}</Text><Ionicons name="chevron-forward" size={18} color={colors.inkFaint} /></Pressable>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(7,10,8,0.58)' }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, maxHeight: '82%', padding: 20, paddingBottom: 35, borderTopLeftRadius: 27, borderTopRightRadius: 27, backgroundColor: colors.paper, borderTopWidth: 1, borderColor: colors.rule }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 3, backgroundColor: colors.rule, marginBottom: 16 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingBottom: 17, borderBottomWidth: 1, borderBottomColor: colors.rule }, cover: { width: 43, height: 51, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, heading: { flex: 1, minWidth: 0 }, title: { color: colors.ink, fontSize: 19, fontWeight: '900' }, meta: { color: colors.inkMuted, fontSize: 11, marginTop: 3 }, close: { width: 42, height: 42, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperRaised }, actions: { paddingTop: 7 }, action: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, borderBottomColor: colors.rule }, actionIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, actionLabel: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '800' }, disabled: { opacity: 0.4 }, pressed: { opacity: 0.64 }, mergeHeading: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingVertical: 15 }, back: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' }, sectionTitle: { color: colors.ink, fontSize: 16, fontWeight: '900' }, note: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, marginTop: 3 }, destinations: { maxHeight: 330 }, destination: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, borderBottomColor: colors.rule }, dot: { width: 12, height: 12, borderRadius: 6 }, destinationName: { color: colors.ink, fontSize: 14, fontWeight: '900' }, empty: { alignItems: 'center', padding: 30 }, emptyTitle: { color: colors.ink, fontSize: 15, fontWeight: '900', marginTop: 10 } });
