import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { masteryLevels, MasteryGrade } from './mastery';
import { useTheme } from '../../theme/ThemeProvider';
import { radius, ThemeColors } from '../../theme/tokens';

const icons: (keyof typeof Ionicons.glyphMap)[] = ['ellipse-outline', 'pencil-outline', 'leaf-outline', 'ribbon-outline'];
export function MasteryPicker({ visible, entryText, currentGrade, saving, onSelect, onClose }: { visible: boolean; entryText?: string; currentGrade: MasteryGrade; saving: boolean; onSelect: (grade: MasteryGrade) => void; onClose: () => void }) {
  const { colors } = useTheme(); const styles = createStyles(colors);
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.scrim} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><View style={{ flex: 1 }}><Text style={styles.title}>Ubah mastery</Text><Text numberOfLines={1} style={styles.entry}>{entryText}</Text></View><Pressable accessibilityLabel="Tutup" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.ink} /></Pressable></View><Text style={styles.note}>Pilih status berdasarkan pengetahuanmu sekarang. Statistik latihan tetap disimpan.</Text><View style={styles.levels}>{masteryLevels.map((level) => { const selected = currentGrade === level.grade; return <Pressable disabled={saving} accessibilityRole="radio" accessibilityState={{ checked: selected }} key={level.grade} onPress={() => onSelect(level.grade)} style={[styles.level, selected && styles.selected]}><View style={[styles.icon, selected && styles.iconSelected]}><Ionicons name={icons[level.grade]} size={21} color={selected ? colors.primaryInk : colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.name}>{level.label}</Text><Text style={styles.levelNote}>{level.note}</Text></View>{selected ? <Ionicons name="checkmark-circle" size={23} color={colors.primary} /> : <Ionicons name="chevron-forward" size={18} color={colors.inkFaint} />}</Pressable>; })}</View></View></Modal>;
}
const createStyles = (colors: ThemeColors) => StyleSheet.create({ scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(7,10,8,0.55)' }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 20, paddingBottom: 35, borderTopLeftRadius: 27, borderTopRightRadius: 27, backgroundColor: colors.paper, borderTopWidth: 1, borderColor: colors.rule }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 3, backgroundColor: colors.rule, marginBottom: 15 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12 }, title: { color: colors.ink, fontSize: 21, fontWeight: '900' }, entry: { color: colors.primary, fontSize: 12, fontWeight: '800', marginTop: 2 }, close: { width: 42, height: 42, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperRaised }, note: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: 12, marginBottom: 14 }, levels: { gap: 7 }, level: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 11, padding: 11, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, selected: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, icon: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, iconSelected: { backgroundColor: colors.primary }, name: { color: colors.ink, fontSize: 14, fontWeight: '900' }, levelNote: { color: colors.inkMuted, fontSize: 10, marginTop: 2 } });
