import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { masteryLevels, masteryReason, MasteryGrade } from './mastery';
import type { MasteryState } from './mastery.repository';
import { radius, ThemeColors } from '../../theme/tokens';
import { useTheme } from '../../theme/ThemeProvider';

const marks: (keyof typeof Ionicons.glyphMap)[] = ['ellipse-outline', 'pencil-outline', 'leaf-outline', 'ribbon-outline'];
type Props = { state: MasteryState; recent: { id: number; mode: 'flashcard' | 'dictation'; rating: 'again' | 'hard' | 'good' | 'easy' | null; isCorrect: boolean; manuallyCorrected: boolean; answeredAt: Date }[]; visible: boolean; saving: boolean; onClose: () => void; onSelect: (grade: MasteryGrade | null) => void };

export function MasterySummary({ state, onPress }: { state: MasteryState; onPress: () => void }) {
  const { colors } = useTheme(); const styles = createStyles(colors); const level = masteryLevels[state.grade];
  return <Pressable accessibilityRole="button" accessibilityLabel={`Mastery ${level.label}, buka detail`} onPress={onPress} style={({ pressed }) => [styles.summary, pressed && { opacity: 0.75 }]}><View style={[styles.summaryMark, state.grade === 3 && styles.summaryMastered]}><Ionicons name={marks[state.grade]} size={23} color={state.grade === 3 ? colors.primaryInk : colors.primary} /></View><View style={{ flex: 1 }}><View style={styles.summaryTitleRow}><Text style={styles.summaryLabel}>MASTERY</Text>{state.manualGrade !== null ? <Text style={styles.manualBadge}>MANUAL</Text> : <Text style={styles.evidenceBadge}>BUKTI GAME</Text>}</View><Text style={styles.summaryValue}>{level.label}</Text><Text numberOfLines={2} style={styles.summaryReason}>{masteryReason(state)}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.inkMuted} /></Pressable>;
}

export function MasterySheet({ state, recent, visible, saving, onClose, onSelect }: Props) {
  const { colors } = useTheme(); const styles = createStyles(colors); const attempts = state.correctCount + state.incorrectCount;
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><Pressable style={styles.scrim} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><View><Text style={styles.sheetTitle}>Jejak mastery</Text><Text style={styles.sheetNote}>Pilihanmu berlaku langsung; game tetap memberi bukti.</Text></View><Pressable accessibilityLabel="Tutup" onPress={onClose} style={styles.close}><Ionicons name="close" size={22} color={colors.ink} /></Pressable></View><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.current}><View><Text style={styles.currentCaption}>STATUS SEKARANG</Text><Text style={styles.currentGrade}>{masteryLevels[state.grade].label}</Text><Text style={styles.currentReason}>{masteryReason(state)}</Text></View><View style={styles.scoreRing}><Text style={styles.score}>{Math.round(state.masteryScore)}%</Text><Text style={styles.scoreLabel}>AKURASI</Text></View></View>
    <View style={styles.metrics}><Metric value={attempts} label="Percobaan" styles={styles} /><Metric value={state.correctCount} label="Berhasil" styles={styles} /><Metric value={state.correctStreak} label="Streak benar" styles={styles} /><Metric value={state.failureStreak} label="Streak gagal" styles={styles} /></View>
    <Text style={styles.sectionTitle}>Atur status manual</Text><Text style={styles.explain}>Status manual tidak menghapus statistik. Tiga kegagalan beruntun akan melepas pilihan manual agar status tidak menyesatkan.</Text><View style={styles.levels}>{masteryLevels.map((level) => { const selected = state.manualGrade === level.grade; return <Pressable disabled={saving} accessibilityRole="radio" accessibilityState={{ checked: selected }} key={level.grade} onPress={() => onSelect(level.grade)} style={[styles.level, selected && styles.levelSelected]}><View style={[styles.levelMark, selected && styles.levelMarkSelected]}><Ionicons name={marks[level.grade]} size={20} color={selected ? colors.primaryInk : colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.levelName}>{level.label}</Text><Text style={styles.levelNote}>{level.note}</Text></View>{selected ? <Ionicons name="checkmark-circle" size={22} color={colors.primary} /> : null}</Pressable>; })}</View>
    <Pressable disabled={saving || state.manualGrade === null} onPress={() => onSelect(null)} style={[styles.auto, state.manualGrade === null && styles.autoSelected]}><Ionicons name="analytics-outline" size={20} color={colors.primary} /><View style={{ flex: 1 }}><Text style={styles.autoTitle}>Gunakan bukti game</Text><Text style={styles.autoNote}>Hapus pilihan manual dan hitung ulang dari statistik saat ini.</Text></View>{state.manualGrade === null ? <Ionicons name="checkmark" size={20} color={colors.primary} /> : null}</Pressable>
    <Text style={styles.sectionTitle}>Bukti terbaru</Text>{recent.length ? recent.map((answer) => <View key={answer.id} style={styles.evidence}><View style={[styles.evidenceDot, { backgroundColor: answer.isCorrect ? colors.primary : colors.danger }]} /><View style={{ flex: 1 }}><Text style={styles.evidenceTitle}>{answer.mode === 'flashcard' ? `Kartu flash · ${ratingLabel(answer.rating)}` : `Dikte · ${answer.isCorrect ? 'Tepat' : 'Belum tepat'}`}</Text><Text style={styles.evidenceDate}>{new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(answer.answeredAt)}{answer.manuallyCorrected ? ' · dikoreksi manual' : ''}</Text></View></View>) : <View style={styles.empty}><Ionicons name="book-outline" size={22} color={colors.inkMuted} /><Text style={styles.emptyText}>Belum ada bukti game untuk entri ini.</Text></View>}
  </ScrollView></View></Modal>;
}
function ratingLabel(rating: Props['recent'][number]['rating']) { return ({ again: 'Lupa', hard: 'Sulit', good: 'Ingat', easy: 'Kuat' } as const)[rating ?? 'again']; }
function Metric({ value, label, styles }: { value: number; label: string; styles: ReturnType<typeof createStyles> }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({
  summary: { flexDirection: 'row', alignItems: 'center', gap: 13, padding: 16, marginTop: 17, borderRadius: radius.lg, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primary }, summaryMark: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperRaised }, summaryMastered: { backgroundColor: colors.primary }, summaryTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, summaryLabel: { color: colors.primary, fontSize: 9, fontWeight: '900', letterSpacing: 1.1 }, manualBadge: { color: colors.ink, fontSize: 8, fontWeight: '900', backgroundColor: colors.highlightSoft, paddingHorizontal: 6, paddingVertical: 3, borderRadius: 7 }, evidenceBadge: { color: colors.primary, fontSize: 8, fontWeight: '900' }, summaryValue: { color: colors.ink, fontSize: 19, fontWeight: '900', marginTop: 3 }, summaryReason: { color: colors.inkMuted, fontSize: 11, lineHeight: 16, marginTop: 2 },
  scrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.48)' }, sheet: { position: 'absolute', left: 0, right: 0, bottom: 0, maxHeight: '91%', backgroundColor: colors.paper, borderTopLeftRadius: 27, borderTopRightRadius: 27, paddingTop: 9 }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 3, backgroundColor: colors.rule }, header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingTop: 15, paddingBottom: 13, borderBottomWidth: 1, borderBottomColor: colors.rule }, sheetTitle: { color: colors.ink, fontSize: 22, fontWeight: '900' }, sheetNote: { color: colors.inkMuted, fontSize: 11, marginTop: 2 }, close: { marginLeft: 'auto', width: 42, height: 42, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paperRaised }, content: { padding: 20, paddingBottom: 42 },
  current: { minHeight: 145, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 18, padding: 20, borderRadius: radius.lg, backgroundColor: colors.primary }, currentCaption: { color: colors.primaryInk, opacity: 0.75, fontSize: 9, fontWeight: '900', letterSpacing: 1.2 }, currentGrade: { color: colors.primaryInk, fontSize: 29, fontWeight: '900', marginTop: 5 }, currentReason: { maxWidth: 215, color: colors.primaryInk, opacity: 0.86, fontSize: 11, lineHeight: 16, marginTop: 5 }, scoreRing: { width: 76, height: 76, borderRadius: 38, borderWidth: 2, borderColor: colors.primaryInk, alignItems: 'center', justifyContent: 'center' }, score: { color: colors.primaryInk, fontSize: 19, fontWeight: '900' }, scoreLabel: { color: colors.primaryInk, opacity: 0.75, fontSize: 7, fontWeight: '900' }, metrics: { flexDirection: 'row', gap: 7, marginTop: 9 }, metric: { flex: 1, alignItems: 'center', paddingVertical: 11, borderRadius: radius.md, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, metricValue: { color: colors.ink, fontSize: 18, fontWeight: '900' }, metricLabel: { color: colors.inkMuted, fontSize: 8, textAlign: 'center', marginTop: 2 },
  sectionTitle: { color: colors.ink, fontSize: 14, fontWeight: '900', marginTop: 23, marginBottom: 5 }, explain: { color: colors.inkMuted, fontSize: 11, lineHeight: 17, marginBottom: 11 }, levels: { gap: 7 }, level: { minHeight: 62, flexDirection: 'row', alignItems: 'center', gap: 11, padding: 11, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule, backgroundColor: colors.paperRaised }, levelSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, levelMark: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, levelMarkSelected: { backgroundColor: colors.primary }, levelName: { color: colors.ink, fontSize: 13, fontWeight: '900' }, levelNote: { color: colors.inkMuted, fontSize: 10, marginTop: 2 }, auto: { minHeight: 61, flexDirection: 'row', alignItems: 'center', gap: 10, padding: 12, marginTop: 9, borderRadius: radius.md, borderWidth: 1, borderColor: colors.rule }, autoSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, autoTitle: { color: colors.ink, fontSize: 12, fontWeight: '900' }, autoNote: { color: colors.inkMuted, fontSize: 9, lineHeight: 14, marginTop: 2 },
  evidence: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 53, borderBottomWidth: 1, borderBottomColor: colors.rule }, evidenceDot: { width: 9, height: 9, borderRadius: 5 }, evidenceTitle: { color: colors.ink, fontSize: 12, fontWeight: '800' }, evidenceDate: { color: colors.inkMuted, fontSize: 9, marginTop: 3 }, empty: { flexDirection: 'row', alignItems: 'center', gap: 9, padding: 15, borderRadius: radius.md, backgroundColor: colors.paperRaised }, emptyText: { color: colors.inkMuted, fontSize: 11 },
});
