import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { radius, ThemeColors } from '../../theme/tokens';
import { useTheme } from '../../theme/ThemeProvider';
import { useAccessibility } from '../accessibility/AccessibilityProvider';

export function BackupSheet({ visible, onClose, onBackup, onRestore }: { visible: boolean; onClose: () => void; onBackup: () => void; onRestore: () => void }) {
  const { colors } = useTheme(); const { reduceMotion } = useAccessibility(); const styles = createStyles(colors);
  return <Modal visible={visible} transparent animationType={reduceMotion ? "none" : "slide"} accessibilityViewIsModal onRequestClose={onClose}><Pressable accessibilityLabel="Tutup pengelolaan backup" style={styles.scrim} onPress={onClose}><Pressable style={styles.sheet} onPress={() => {}}><View style={styles.handle} /><Text style={styles.note}>Salinan pribadi</Text><Text style={styles.title}>Backup & restore</Text><Text style={styles.copy}>Backup penuh menyimpan semua deck, favorit, mastery, sesi, jawaban, tag, histori, dan pengaturan database ke satu file lokal.</Text><Action icon="archive-outline" title="Buat backup penuh" detail="Simpan atau kirim salinan seluruh data melalui share sheet perangkat." onPress={onBackup} styles={styles} colors={colors} /><Action icon="refresh-circle-outline" title="Pulihkan dari backup" detail="Pilih file backup, periksa isinya, lalu ganti seluruh data saat ini." onPress={onRestore} styles={styles} colors={colors} /><View style={styles.warning}><Ionicons name="warning-outline" size={20} color={colors.highlight} /><Text style={styles.warningText}>Restore mengganti seluruh data di aplikasi. File diperiksa sebelum konfirmasi dan tidak dikirim ke internet.</Text></View><Pressable onPress={onClose} style={styles.close}><Text style={styles.closeText}>Selesai</Text></Pressable></Pressable></Pressable></Modal>;
}
function Action({ icon, title, detail, onPress, styles, colors }: { icon: keyof typeof Ionicons.glyphMap; title: string; detail: string; onPress: () => void; styles: ReturnType<typeof createStyles>; colors: ThemeColors }) { return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.action, pressed && { opacity: 0.65 }]}><View style={styles.icon}><Ionicons name={icon} size={22} color={colors.primary} /></View><View style={styles.grow}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.detail}>{detail}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.inkMuted} /></Pressable>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ scrim: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(7,10,8,0.58)' }, sheet: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 30, borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg, backgroundColor: colors.paperRaised, borderWidth: 1, borderColor: colors.rule }, handle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: colors.rule, marginBottom: 17 }, note: { color: colors.highlight, fontSize: 13, fontWeight: '900' }, title: { color: colors.ink, fontSize: 23, fontWeight: '900', marginTop: 2 }, copy: { color: colors.inkMuted, fontSize: 12, lineHeight: 18, marginTop: 7, marginBottom: 15 }, action: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 12, borderTopWidth: 1, borderTopColor: colors.rule }, icon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft }, grow: { flex: 1 }, actionTitle: { color: colors.ink, fontSize: 14, fontWeight: '900' }, detail: { color: colors.inkMuted, fontSize: 11, lineHeight: 16, marginTop: 3 }, warning: { flexDirection: 'row', gap: 10, borderRadius: radius.md, padding: 13, marginTop: 12, backgroundColor: colors.highlightSoft }, warningText: { flex: 1, color: colors.inkMuted, fontSize: 11, lineHeight: 17 }, close: { minHeight: 48, alignItems: 'center', justifyContent: 'center', marginTop: 15, borderRadius: radius.md, backgroundColor: colors.primary }, closeText: { color: colors.primaryInk, fontWeight: '900', fontSize: 13 } });
